### ISSUE TITLE
Works. How can I help to improve it?

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#1]
Hi Alex, I was looking for a simple Radio App for my stations see https://github.com/Wikinaut/MyStreamRecorder/blob/master/rec.ini .

Your code works, but it would be indeed nice to have at least the **search** (of your to-do list) working, with a stream selection, if possible (some stations like DeutschlandRadio offer "multi-bit rate" streams, I can supply you with the stream urls).

I also suggest:
- add possibility to enter a stream Url manually (see #171)
<s>- add "sharing" tools to share a radio station / stream url (implemented now)</s>
- add a tool to import/export favorite station list per OPML https://en.wikipedia.org/wiki/OPML file, similar to what Stefan's https://play.google.com/store/apps/details?id=de.shandschuh.sparserss&hl=de does (export a list of one's seletion of RSS feeds in OPML format)

**Comment by segler-alex** [comment]
i implemented sharing, works best with installed vlc :)
