### ISSUE TITLE
App opens to blank screen

### ISSUE THREAD

**Issue by glitchphan** [segler-alex/RadioDroid#10]
On two different phones so far, I have tried to install this app. All I get when I run it, however, is a blank white screen. It does initially say "Loading...", and I can bring up the menu to select TopVote or TopClick, and it does say "Loading..." again, but nothing comes up on the screen. Am I doing it wrong? I even tried tapping all over the white area, in case it was just showing stuff in white font :). It doesn't register with the system, apparently, so I can't "open with" a pls/m3u file, either.

**Comment by segler-alex** [comment]
i am using it on multiple android devices and it works. 
Which one do you have? android version? The only time i could reproduce such a behaviour is, if i deactivate internet (WLAN and mobile data).
could you send a photo/screenshot? do you have the original android system or a mod like for example cyanogen?

**Comment by ZeZiNhOo** [comment]
> It doesn't register with the system, apparently, so I can't "open with" a pls/m3u file, either.

AFAIK, this is not the idea of this radio player, which plugs to a website. Just add the radios you need to this site!

**Comment by glitchphan** [comment]
![screenshot_20160407-185032](https://cloud.githubusercontent.com/assets/14065496/14372031/e0f94136-fcf1-11e5-9d94-4c432eb8ff43.png)
![screenshot_20160407-185300](https://cloud.githubusercontent.com/assets/14065496/14372039/fa3e25c6-fcf1-11e5-99b1-e4f8a6047a72.png)

**Comment by glitchphan** [comment]
This is a separate issue, but here is what happens if I search with two words. Single words like "pop" or "rock" just show white screen, but "pop rock" does this:

![screenshot_20160407-185547](https://cloud.githubusercontent.com/assets/14065496/14372145/aeee17ba-fcf2-11e5-890a-d1f9798c8423.png)

**Comment by segler-alex** [comment]
i tried your last bug putting in "pop rock" but it did not crash on my phone which also has a recent android 6. hmmmm :(

**Comment by glitchphan** [comment]
I just tried version 0.9 from F-Droid and this is no longer an issue. I can see tabs and lists of stations now.

By the way, a history or favorites list would be cool :). Maybe also a quicker way to hit play from the list.

**Comment by segler-alex** [comment]
cool, favourites tab is on my list :)
