### ISSUE TITLE
The RadioDroid autoplays after alarm (or switching from airplane mode to normal mode)

### ISSUE THREAD

**Issue by Iey4iej3** [segler-alex/RadioDroid#101]
It seems to me that this issue appears after I upgraded RadioDroid from 0.25 to 0.26 recently.

cyanogenmod 13 (Android Marshmallow)

I don't know whether it owes to the alarm or the switching. I catched a logcat here:

[log2.txt](https://github.com/segler-alex/RadioDroid/files/695643/log2.txt)

I cleared the data (in Android Settings -> apps), and it doesn't help. The issue maintains.

**Comment by FrankEular** [comment]
It also auto-plays (occasionally) when I connect to a WiFi.

**Comment by FrankEular** [comment]
It auto-plays when I receive a new email in K-9 Mail! I estimate that it is due to the new "audio focus of android".

**Comment by czettnersandor** [comment]
It also autoplays when there's any notification sound is playing on the phone. Sometimes during phone calls as well. Something is wrong with audiofocus.

**Comment by phirsch** [comment]
For me, it also inadvertently starts autoplay after any kind of notification sound from other apps (even if notifications sounds are muted). This behaviour started with version 0.26. Peering over recent commit messages, I agree that audio-focus seems most suspicious. (Android 5.1.1).

**Comment by segler-alex** [comment]
i will push version 0.27 shortly to the playstore beta channel and fdroid, please test the behaviour again when the version arrives

**Comment by FrankEular** [comment]
Could you please release some kind of "-dbg" version (in F-Droid, say) so that we can report more logs for that? I think it will also facilitate your debug process.
