### ISSUE TITLE
It takes very long to start playback on Android 7.0

### ISSUE THREAD

**Issue by kulmegil** [segler-alex/RadioDroid#103]
I have tested RadioDroid side by side with my 2 phones:

OnePlus 3T running Android 7.0 (stock - OxygenOS 4.0.1)
vs
OnePlus One running Android 6.0.1 (CyanogenMod 13.0)

* Testing same set of stations
* both connected using same WiFi AP, mobile data disabled

It takes a lot  longer for RadioDroid on 7.0 to start playback. This is despite the fact that buffering progress looks similar on both devices.

I did not encountered similar issues with few other online radio apps - so I suspect it's not ROM related.

Some timings (7.0 vs 6.0.1)
station: "Bandit Rock"
27,66 s
1,92 s

station: "Radio Paradise"
29,54 s
7,10 s

station ".997 Classic Rock"
34,43 s
4,43 s

station: "BBC Radio 1"
38,80 s
6:59 s

station: "RMF classic"
35,47 s
1,70 s

**Comment by segler-alex** [comment]
i don't have a android 7 device at the moment, i cannot test it.
my htc 10 did not receive android 7 yet
i will look at this as soon as i get it.

**Comment by thrillfall** [comment]
I run the app with Android 7.1.1 (LineageOS) on Moto E and i don't experience any delays. It might well be due to the different ROM.

**Comment by motatuc** [comment]
Tried RMF classic. Started within 2 seconds. Android 7.1.1. (Lineage)

**Comment by segler-alex** [comment]
i cannot reproduce that behaviour, i tried it with samsung s5 with lineage 7.1.1 and with HTC 10 android 7.0

**Comment by kulmegil** [comment]
When it comes to version <= **0.28**:

* It's still present when running in latest stable (v4.0.3, based on Android 7.0) OxygenOS - a stock rom for OnePlus 3 / 3T phones. This stock rom is the one I stick with daily ... for now.

* I haven't tested beta version of OxygenOS that is based on Android 7.1.1..

* ..but in meantime I did with LineageOS (based on 7.1.1) and issue was not reproducible there.

The latest v**0.29** works fine on my stock OxygenOS. I haven't got time to test it in other roms yet.

**Comment by segler-alex** [comment]
is this still an issue with 0.30?

**Comment by kulmegil** [comment]
Nope

Couldn't reproduce on RadioDroid v0.29 - 0.30 on either ROM.

Couldn't reproduce on any RadioDroid <=0.28 when running LineageOS or latest stock (OxygenOS 4.0.x) - based on 7.1.1 But could reproduce on earlier builds of OxygenOS based on 7.0.
