### ISSUE TITLE
Randomly starts playing again

### ISSUE THREAD

**Issue by varac** [segler-alex/RadioDroid#107]
Hi, 

I start Radiodroid, play a stream and then exit radiodroid, focussing on other apps.
Sometimes it just starts playing out of the blue again.
Is this a know issue ? How can this get fixed ?

**Comment by motatuc** [comment]
I experience the same problem. Happens under Android 6 and 7. Any more information needed about this?

**Comment by segler-alex** [comment]
it should be fixed with the current release. does it still happen with 0.27?

**Comment by Cormak** [comment]
@segler-alex this might be fixed for good with https://github.com/segler-alex/RadioDroid/pull/248

**Comment by segler-alex** [comment]
did not happen to me for quite some time
