### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by NP-Sagar-Dhakal** [segler-alex/RadioDroid#1081]
Need updates .....Please.

**Comment by FinixFighter** [comment]
I'd also like to know if this project is still alive. I hope so! :(

**Comment by werman** [comment]
The core functionality is working. There are a few things in need to be updated with newer Android versions though. And there are few functions like alarm not working properly for a long time...

**Comment by NP-Sagar-Dhakal** [comment]
Updating libraries with the new version is creating many problems and those next/prev button not working and the design looks so old need some modification. Player view automatically scrolling at that playlist recycler view.

**Comment by werman** [comment]
Don't expect design to be updated unless some wild UI/UX designer would appear. 

Prev/Next buttons are working, they switch between favourite stations.

Updating libraries... what for?

The last point - I don't understand.

**Comment by NP-Sagar-Dhakal** [comment]
On the Detail Player, it automatically scrolls at the recycler view position of Track History. I fixed it by adding
`android:descendantFocusability="blocksDescendants"`
on recycler view.

Expecting hole app update from the developer/contributor.

**Comment by Korb** [comment]
There's an unreviewed [PR from 2023-11-01](https://github.com/segler-alex/RadioDroid/pull/1187) in the Pull Requests section, and the repository [author's last comment was on Dec 26, 2024](https://github.com/segler-alex/RadioDroid/issues/1240#issuecomment-2562991546). So, yes, the repository should be archived.

---
Related to #1236 and #1262
