### ISSUE TITLE
Broken Stations

### ISSUE THREAD

**Issue by kousu** [segler-alex/RadioDroid#109]
Some stations fail for no obvious reason and the feedback from the GUI just says "Unable to connect". For example, all of soma.fm are now marked broken, and RadioDroid refuses to play them, even if I update them with working URLs:

http://www.radio-browser.info/gui/#/edit/64729 had http://somafm.com/beatblender130.pls, now it has http://ice1.somafm.com/beatblender-128-aac. Both work on my laptop and with ServeStream on my phone, but RadioDroid refuses.

Is RadioDroid taking the advice of radio-browser.info on what stations are up as truth? In that case, has radio-browser.info gotten IP banned from Soma, and other stations, perhaps?

I would like more informative feedback about what RadioDroid is doing and especially how it fails, for it to try station addresses anyway even if they are marked broken (if it's not already; if it isn't, where should I look next to figure out what's wrong?), and maybe rather than using your single source IP to poll all the stations in your catalogue, have the app do (anonymous!) tracking so tht as people listen they are implicitly voting on the reliability of stations.

**Comment by segler-alex** [comment]
yes we got blocked. please see
https://github.com/segler-alex/radiobrowser/issues/20

**Comment by segler-alex** [comment]
i don't want to show stations in radiodroid, that are broken. it would give users a bad experience

**Comment by segler-alex** [comment]
also i have to be sure of a station working or not. so i cannot rely on client info. it can be faked. i rely on this information for deletion after some time.
there are already people to try to push stations in the list to the top by directly accessing the API

**Comment by kousu** [comment]
I agree! One of the best features of RadioDroid is that it has a working directory of stations, instead of leaving you to find stations and extract their URLs on your own (as with ServeStream). That's why I thinking crowdsourcing is a good idea: so long as most users are honest, so will the data be, once you **average it**. You need to be concerned about bots intentionally skewing the data, true, but a throttling system, perhaps [hash cash](http://www.hashcash.org/), would help, and anyway these votes would not be for ranking, but just for reporting if the station works; how much does it help an attacker to make their broken station seem to work?

**Comment by kousu** [comment]
And in the meantime, @Wikinaut and I and everyone else can't use Soma, which is probably one of the best recognized internet radios on our continent, and *that's* a bad user experience too. Why does RadioDroid refuse to even try to play a stream marked broken? You have the option to hide broken stations from the listing, which is very effective and wise already; but if I want to use a station that was already in my favorites, please let RadioDroid make the attempt.

**Comment by Wikinaut** [comment]
On debian, I can use
`mplayer -playlist http://somafm.com/groovesalad.pls`

**Comment by Wikinaut** [comment]
It may make a difference, whether the stream points to a playlist (example: SomaFM urls) or not.

```
works:
mplayer -playlist http://somafm.com/groovesalad.pls

does not work:
mplayer http://somafm.com/groovesalad.pls

does not work:
mplayer -playlist http://kulturradio.de/livemp3

works:
mplayer http://kulturradio.de/livemp3
```

**Comment by kousu** [comment]
I tried editing Groove Salad to point to both in turn, refreshed RadioDroid to get the update, and neither worked. It had a big "UNAVAILABLE" next to it. Also, if I choose Use External Player in the settings and try a working station, I get prompted to launch Music or ServeStream; but if I choose one of these "UNAVAILABLE" stations that's never even attempted. So it seems to me that RadioDroid is deciding it knows better than the music player about what works or doesn't, and I wish it wouldn't make that assumption.

**Comment by Wikinaut** [comment]
@kousu Don't start Radiodroid bashing, please do not. It's the best service and code available. I think, it's a code problem, not a block from SomaFM.

**Comment by kousu** [comment]
Sorry if I came off like I'm trying to pick on anyone. I'm not. I like this program; it solves the problem of what Clementine and RhythmBox and iTunes do for Desktops: how do I find internet radio? But it is rough around the edges and I would like to advocate for it.

Also Alex said "yes we got blocked." in this thread.

**Comment by segler-alex** [comment]
i wrote an email to somafm. asking for help, telling them what radio-browser is. hoping they like it :)

**Comment by Wikinaut** [comment]
@segler-alex 
I replaced in

```
	public void PlayUrl(String theURL, String theName, String theID, final boolean isAlarm) {
		itsStationID = theID;
		itsStationName = theName;
		itsStationURL = "http://ice2.somafm.com/groovesalad-128-mp3"; // = theURL;
```

Works.

**Comment by Wikinaut** [comment]
So I really think, it's a problem of the playlist file format. If you use one of two urls, your code plays.

**Comment by segler-alex** [comment]
you don't have to prove to me that soma fm works in principle. i know that. it also works on my computer.
but on the one server it does not work.

**Comment by Wikinaut** [comment]
SomaFM groovesalad.pls

```
[playlist]
numberofentries=2
File1=http://ice1.somafm.com/groovesalad-128-mp3
Title1=SomaFM: Groove Salad (#1  ): A nicely chilled plate of ambient/downtempo beats and grooves.
Length1=-1
File2=http://ice2.somafm.com/groovesalad-128-mp3
Title2=SomaFM: Groove Salad (#2  ): A nicely chilled plate of ambient/downtempo beats and grooves.
Length2=-1
Version=2
```

**Comment by segler-alex** [comment]
also on my other servers, for different projects the streams work. it is just the one server

**Comment by Wikinaut** [comment]
see my comment https://github.com/segler-alex/RadioDroid/issues/109#issuecomment-276765281 above

**Comment by Wikinaut** [comment]
Solved.

I changed temporarily the stream url to http://stream.dradio.de/7/530/142684/v1/gnl.akacast.akamaistream.net/dradio_mp3_dkultur_m (stream of Deutschlandradio).

Then I changed it back to http://ice2.somafm.com/groovesalad-128-mp3 .

Works for me.

**Comment by segler-alex** [comment]
somafm wrote me back and unblocked radiobrowser

**Comment by Wikinaut** [comment]
Yes, this afternoon I found SomaFM working on my Radiodroid. Well done 👍
