### ISSUE TITLE
Icons in SVG

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#11]
Please replace all play and stop icons with versions in SVG. 

Implementating this wilk greatly improve the look of the app.

**Comment by segler-alex** [comment]
That is a cool idea, but i really need some help with that. i am not a graphics guy, really not :)
If anybody reads this who can help, it would be really nice!

**Comment by ZeZiNhOo** [comment]
Creating the SVG is easy with Inkscape, and I can send you the converted files. Or do you need help with the code that uses SVG instead of PNG? (i am not a code guy)

**Comment by PanderMusubi** [comment]
Ah, the two of you are the perfect match for this :smile:

**Comment by segler-alex** [comment]
i found out that there is an assistant for generating standard icons in vector graphic in android studio. they use a subset of svg, but its vector graphic :)
