### ISSUE TITLE
Integrate External Directories

### ISSUE THREAD

**Issue by kousu** [segler-alex/RadioDroid#110]
It seems like you could add a cronjob to your server to pull all of [Icecast](http://dir.xiph.org/) into your database. Look, there's even a handy XML file: http://dir.xiph.org/yp.xml

You could also integrate [SHOUTcast](http://wiki.shoutcast.com/wiki/SHOUTcast_Radio_Directory_API) if you email them and beg, or *cough* "integrate" it with BeautifulSoup and some patience.

**Comment by segler-alex** [comment]
i don't want to just add other directories to my own. but i would accept a pull request for RadioDroid that makes also use of other directories.
