### ISSUE TITLE
App no longer downloadable from Google Play on Android 13 devices (API level target requirement?)

### ISSUE THREAD

**Issue by eggsgent** [segler-alex/RadioDroid#1152]
App no longer downloadable on Google Play on Android 13 devices  (API level target requirement?).
"This app isn't available for your device because it was made for older version of Android." message shown.

https://developer.android.com/google/play/requirements/target-sdk
https://play.google.com/store/apps/details?id=net.programmierecke.radiodroid2&hl=en_US&gl=US&pli=1

**Comment by eggsgent** [comment]
Thanks!

**Comment by elliotwutingfeng** [comment]
Works on Android 14 now, I think this can be closed?
