### ISSUE TITLE
Time for a RadioDroid/RadioDroid?

### ISSUE THREAD

**Issue by mxmilkiib** [segler-alex/RadioDroid#1155]
Given apparent circumstances, moving to a repo that is managed by a collective of the core contributors seems like it could be the healthiest option for the future of the app?

Might the core contributors see merit and be interested in such an idea?

**Comment by vdbhb59** [comment]
Good idea. I am willing to help here.

**Comment by vdbhb59** [comment]
@segler-alex close this too pls.
