### ISSUE TITLE
Export/Import Favorites

### ISSUE THREAD

**Issue by YeMaOr** [segler-alex/RadioDroid#1163]
Hello,
Thanks for RadioDroid!

In the export file, the favorites are in the same order as on the Radiodroid Favorites page.

When importing the same file, the radios are not in the same order.

How can I avoid having to reorder the favorites?

Best regards

**Comment by segler-alex** [comment]
will be fixed in version 0.86

**Comment by YeMaOr** [comment]
Hello,

Thank you very much for this quick fix.

RadioDroid even more convenient.
And I like RadioDroid even more :-)

Best regards.
