### ISSUE TITLE
RadioDroid has Ceased Working on Samsung Tablet

### ISSUE THREAD

**Issue by Wendwell** [segler-alex/RadioDroid#1164]
First of all, thanks for over a year's trouble free radio listening with Radiodroid on both my tablet and smart phone. A much appreciated and used app.

The app is still working on my phone but stopped connecting on my tablet this morning. I can still listen to radio via Firefox.  I have deleted and reinstalled Radiodroid from Playstore, cleaned cache and done a virus check with AVG.  Still not able to connect.   

Any suggestions?

**Comment by segler-alex** [comment]
does it work again now?

**Comment by radraw** [comment]
It happened the same for me. Helped uninstalling version from Google Play and installing version from F-Droid (which is bit newer).

**Comment by segler-alex** [comment]
I pushed a completely new version to google play store, should also come to f-droid in a few days.
