### ISSUE TITLE
https://github.com/segler-alex/radiobrowser-api-rust : " This repository has been archived by the owner on Oct 8, 2023. It is now read-only. "

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#1179]
What happend with https://github.com/segler-alex/radiobrowser-api-rust?

You have closed all issues in https://github.com/segler-alex/radiobrowser-api-rust, are they really fixed?

**Comment by vdbhb59** [comment]
The project has moved to GitLab. See in the page itself. It is mentioned.

**Comment by segler-alex** [comment]
hmmm, seems i am too late. gitlab is not the hot thing anymore...
some time ago people were telling me i should leave github and move to gitlab. microsoft is bad this things, you know.
now i finally do it and it is not cool anymore.
never heard of codeberg.
i am using gitlab at my workplace as a devops engineer and I love it. way better than github featurewise. i want to go there to finally make building and deployment better for radio-browser. i want the features. but I understand that it is a serious hurdle for many people to provide credit card information.

BUT:
I tried it now myself. new email adress, new account on gitlab. and I did NOT have to provide credit card information. I will therefore keep migrating to gitlab.

**Comment by davidhedlund** [comment]
> The project has moved to GitLab. See in the page itself. It is mentioned.

Oh, sorry, I missed that. So the link to the new repo is: https://gitlab.com/radiobrowser/radiobrowser-api-rust

**Comment by davidhedlund** [comment]
@segler-alex But I don't see any Issues link at https://gitlab.com/radiobrowser/radiobrowser-api-rust

Where have the issues from https://github.com/segler-alex/radiobrowser-api-rust been merged to?

**Comment by segler-alex** [comment]
https://gitlab.com/radiobrowser/radiobrowser-api-rust/-/issues

**Comment by davidhedlund** [comment]
> https://gitlab.com/radiobrowser/radiobrowser-api-rust/-/issues

Oh, it was located under "Plan", I expected it to be visible like on GitHub.

**Comment by davidhedlund** [comment]
> hmmm, seems i am too late. gitlab is not the hot thing anymore... some time ago people were telling me i should leave github and move to gitlab. microsoft is bad this things, you know. now i finally do it and it is not cool anymore. never heard of codeberg. i am using gitlab at my workplace as a devops engineer and I love it. way better than github featurewise. i want to go there to finally make building and deployment better for radio-browser. i want the features. but I understand that it is a serious hurdle for many people to provide credit card information.
> 
> BUT: I tried it now myself. new email adress, new account on gitlab. and I did NOT have to provide credit card information. I will therefore keep migrating to gitlab.

Check out https://gitlab.com/gitlab-org/gitlab-foss -- I found the link at https://directory.fsf.org/wiki/GitLab so it is approve by the Free Software Foundation.

**Comment by davidhedlund** [comment]
> @segler-alex moving to GitLab is bad. GitLab is forcing users to provide credit card even if one wants to contribute, even if CI is not being used.
> 
> https://gitlab.com/fdroid/admin/-/issues/159#note_1594923208
> 
> https://gitlab.com/fdroid/admin/uploads/40260a8755be037affe1df46d42ee445/image.png ![Screenshot_20231009_150734](https://user-images.githubusercontent.com/60728004/273547081-0b8241a6-7372-492f-909b-f4fc9a8cdf43.jpg)
> 
> Suggest to move to Codeberg instead or some other open source which is not an issue for users.

2 years ago and seems just like a UX error for some abuse though

**Comment by davidhedlund** [comment]
> hmmm, seems i am too late. gitlab is not the hot thing anymore... 

GitLab is perfectlyu fine. It's used by:
* F-Droid: https://gitlab.com/groups/fdroid/
* GNOME: https://gitlab.gnome.org/
* Trisquel: https://gitlab.trisquel.org/

**Comment by vdbhb59** [comment]
> > hmmm, seems i am too late. gitlab is not the hot thing anymore...
> 
> GitLab is perfectlyu fine. It's used by:
> 
> * F-Droid: https://gitlab.com/groups/fdroid/
> * GNOME: https://gitlab.gnome.org/
> * Trisquel: https://gitlab.trisquel.org/

That issue of CC was reported in F-Droid and confirmed by the F-Droid team on the day I posted it. Not 2 years old.

**Comment by davidhedlund** [comment]
> > > hmmm, seems i am too late. gitlab is not the hot thing anymore...
> > 
> > 
> > GitLab is perfectlyu fine. It's used by:
> > 
> > * F-Droid: https://gitlab.com/groups/fdroid/
> > * GNOME: https://gitlab.gnome.org/
> > * Trisquel: https://gitlab.trisquel.org/
> 
> That issue of CC was reported in F-Droid and confirmed by the F-Droid team on the day I posted it. Not 2 years old.

Alright, that sounds interesting. I'll check it up. Thank you for the notification.
