### ISSUE TITLE
Full-screen Mode Bug Since v0.85

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#1181]
Click the bottom to enter the full-screen mode, then click the play icon in the middle to play a station and pause it, but the icon fails to change back to the play icon. And the star icon on the right side used to favorite & unfavorite stations also fails to change after clicking. All the problems disappear after being switched back from the background.

**Comment by vdbhb59** [comment]
Relates to https://github.com/segler-alex/RadioDroid/issues/1177
You can close this out and add a comment there.
Thanks.
