### ISSUE TITLE
Advertising on radiofrance radios

### ISSUE THREAD

**Issue by pled** [segler-alex/RadioDroid#1182]
Hi,
There is now a 30s advertising message when connecting to radiofrance stations (France Inter, France Culture, etc...).
This is explained [here](https://mediateur.radiofrance.com/infos/la-publicite-sur-les-plateformes-decoute/) : they say you have 30s ad message when connecting out of the official android application (radio france) or the website (radiofrance.fr).

I was wondering if these ads could not be removed by radiodroid, as it seems some app like Radioplayer succeeds to initiate streaming without that "annoying" advertising message.

PS : I understand this is a bit out of your scope, but if by any means...

**Comment by vdbhb59** [comment]
Does the RadioPlayer app have a source code? Maybe it can be checked there.

**Comment by hista** [comment]
I have found this way: https://forum.hardware.fr/hfr/gsmgpspda/android/applications-android-noob-sujet_21184_1485.htm#t2693994

**Comment by pled** [comment]
Very interesting, thank you !
So it appears RadioBrowser is potentially  using old links for streaming like listed [here](https://gist.github.com/JV-conseil/7063daeadf0041cb845d0ec22f8c418f) (aac format) and this is why the ads appears (note it is all icecast... links).
As explained in the link above, user created a new radio on RadioBrowser using default radiofrance links (stream.radiofrance.fr etc links), and then no more ads when starting to listen those radios.

So could it just because RadioBrowser database needs to be updated ? I don't know how the link in the database is selected, and the database is write protected for security reason.

**Comment by hista** [comment]
You're welcome.
I sniffed the traffic from the official website to get its streaming url without ads.
Since there is no way to modify RadioBrowser database (to avoid vandalism: https://github.com/segler-alex/radiobrowser-api-rust/issues/49), I created new radios in the RadioBrowser database.
You just need to select them to continue to listen them without these damn pre-roll ads :)

**Comment by vdbhb59** [comment]
Probably close this out now?

**Comment by pled** [comment]
Sure, this can be closed, situation is clear.
