### ISSUE TITLE
Could you add a CLOSE button? 

### ISSUE THREAD

**Issue by lolo83560** [segler-alex/RadioDroid#120]
Need to go kill the app when I want to stop listening,  which is inconvenient.

**Comment by segler-alex** [comment]
there is already a stop button for the current stream. you can reach it from within the app in the left hand menu entry "Player Status".
or you can also reach it in the android top menu in the notification of radiodroid (by clicking it)

**Comment by zoff99** [comment]
the service keeps on running even when you press the stop button
