### ISSUE TITLE
Crash when opening alarm clock settings after app update

### ISSUE THREAD

**Issue by Neudrino** [segler-alex/RadioDroid#121]
I had troubles that the app was crashing every time when going to alarm clock settings after I updated to version 0.29 (from 0.27?). Sorry, that I don't know exactly, however, I did not have the weekly alarms before, so I suspect that I was on 0.27 before. And this might occur when doing an update 0.27 --> 0.28 if new alarm settings are introduced there. I had 3 alarms configured before. One of them active.

It was not enough to wipe the application cache to solve it.
However, deleting the complete application data restarting the app did the trick for me. Of course you loose all favorites and configured alarms by this. This might make some users "nervous".
(But I think, I am using a great open source tool, somebody does in his spare time, so I can invest 10 min to re-add my favorites and alarms. And maybe another 20 to let you know about this. :wink: )

I do _not_ consider this a "real bug" which needs fixing, as this will solve itself as soon as all users are on version 0.28 or newer. Anyway I wanted to let you know. (Maybe you make a comment somewhere about this for the users?)

Thanks for the great app! I will love the new feature of weekday alarms! :grinning:

**Comment by thrillfall** [comment]
This is most probably to the new alarm which now also holds an array of weekdays. If there are alarms in the "old" format the parser crashes. I thought this was backward compatible but i missed something. Sorry for that. I hope the new weekdays option compensates for loosing favorites and preset alarms.

**Comment by exmosis** [comment]
Also being affected by this - although in my case I have an alarm which is set and seems to go off, but I can't go into the alarm settings to turn it off! My workaround is to make sure wifi is disabled for the time it's set for, but any fix (or even just a way to remove the alarms without losing other data) would be greatly appreciated...

**Comment by Neudrino** [comment]
@exmosis : If you installed via F-Droid, you might be able to downgrade to 0.27 until the fix is available in the repo.

@thrillfall @segler-alex : Thank you very much for your work!
And yes, for me the option compensates it! :grinning:
