### ISSUE TITLE
Support equalizer

### ISSUE THREAD

**Issue by dalb8** [segler-alex/RadioDroid#122]
I think it only has to implement this: https://developer.android.com/reference/android/media/audiofx/AudioEffect.html. The Vanilla app managed it with 10 lines: adrian-bl/vanilla@141aef2

**Comment by dalb8** [comment]
Sorry: vanilla-music/vanilla@141aef2

**Comment by shadowbone94** [comment]
Yes, please add support for inbuilt (preferably)  equalizer.

**Comment by werman** [comment]
Resolved by #204 which adds support for external equalizers.
