### ISSUE TITLE
Feature request: Add buttons to the bottom of the screen

### ISSUE THREAD

**Issue by trustable-code** [segler-alex/RadioDroid#127]
I think it would be handy to have a Stop button at the bottom/top of the screen, which is always visible while a station is playing

**Comment by maikst** [comment]
+1
and also play, pause, forward etc
thx

**Comment by wired2051** [comment]
Stop on bottom or top would be fine!

**Comment by Wikinaut** [comment]
ok, I will try to implement this.

**Comment by Cormak** [comment]
@wired2051 @Wikinaut Bottom would be best because the big phones we have today will just mean our fingers have to travel all the way up to control the player. Also, pretty much every audio player has it on the bottom.

**Comment by davidhedlund** [comment]
The play button can be transformed to a pause button once it has been clicked on.

**Comment by davidhedlund** [comment]
@werman Ping.

**Comment by davidhedlund** [comment]
@trustable-code Can you please change the title to "Feature request: Add buttons to the bottom of the screen."

**Comment by davidhedlund** [comment]
@Wikinaut Thank you for your work on this project.

**Comment by werman** [comment]
There are button at the bottom.
![radio_droid_bottom_bar](https://user-images.githubusercontent.com/3993671/41194694-6a324cb6-6c28-11e8-9b46-4511c0415d3c.png)

**Comment by davidhedlund** [comment]
@werman Thank you very much.

**Comment by davidhedlund** [comment]
@werman How can I install the latest version on my smartphone? I'm using the f-droid.org build for the moment but it's outdated.

**Comment by davidhedlund** [comment]
@werman I can see it in my f-droid build sorry.

**Comment by werman** [comment]
Nice, issue resolved =) But yes there are some issues with versions from time to time.

**Comment by davidhedlund** [comment]
https://github.com/segler-alex/RadioDroid/issues/350

**Comment by trustable-code** [comment]
The now existing pause button is what I needed.
Closing.
