### ISSUE TITLE
Add a station

### ISSUE THREAD

**Issue by Raffaele74** [segler-alex/RadioDroid#128]
You say everyone can do, but you don't say how one can do.

Exemple:  http://www.nonsolosuoni.it/noflash.html

**Comment by 4rz0** [comment]
You look for the stream link, go to [http://www.radio-browser.info](http://www.radio-browser.info), click "_New Station_", add in the needed information and submit your entry.
Then you wait a bit, search for the added station and refresh a few times if it doesn't show up already.

**Comment by Korb** [comment]
> You look for the stream link, go to [http://www.radio-browser.info](http://www.radio-browser.info/), click "_New Station_"

> ATTENTION: ADDING is DISABLED
> Because of a massive push of illegal content and of other ways to break this service, I had to stop accepting new stations (FOR NOW). Jun 12. 2025

https://github.com/segler-alex/RadioDroid/issues/370#issuecomment-3296579747
