### ISSUE TITLE
[FR] support for lyric apps to display lyrics

### ISSUE THREAD

**Issue by conrad-heimbold** [segler-alex/RadioDroid#129]
Could you broadcast the metadata (esp. artist name, song name, album name, if possible) sent via Internet radio stream / displayed in the notification 
via the namespace com.android.music.* ? 
That would make it possible for the app Lyrically to search for and display Lyrics for the played songs. 
Thank you in advance!

**Comment by nicolas-raoul** [comment]
Issue also described at https://github.com/QuickLyric/QuickLyric/issues/222 :

> While [RadioDroid] does seem to show the artist name and title in the notification, I suspect it's just a formatted string that the webradio sends along with the audio stream.
> The point is, RadioDroid does not seem to handle the metadata in any way and also does not share it with other apps.

**Comment by conrad-heimbold** [comment]
Other possibility: Whenever the sent metadata **changes**, record the first few seconds and send those to the Lyric app in the background. Most lyric apps can also recognize songs just by analyzing these first few seconds.

**Comment by werman** [comment]
Solved in #203, works with QuickLyric.
