### ISSUE TITLE
FR: Export starred stations as playlist.

### ISSUE THREAD

**Issue by gerroon** [segler-alex/RadioDroid#132]
Hi

It would be nice if the user can export the starred stations as regular playlist files.

thanks

**Comment by Wikinaut** [comment]
Similar to #33.

Dear @gerroon please can you check, if #33 would fulfil your requirement as it would allow export/import of starred stations (Favorites)?

**Comment by gerroon** [comment]
@Wikinaut 

That sounds like what I was talkign about.

**Comment by Wikinaut** [comment]
@gerroon If you think so, then you could close this issue. The #33 will stay open and I will try to implement it.
