### ISSUE TITLE
Livestreamadressen Deutschlandradio

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#133]
Die Livestreams haben sich am 08.06.2017 geändert, die neuen Adressen (OGG und MP3) sind unter 
http://www.deutschlandradio.de/unsere-streaming-adressen-im-einzelnen.3236.de.html
zu finden.

**Comment by Wikinaut** [comment]
Die OGG Streams sind schon korrekt.

**Comment by centic9** [comment]
As far as I understand the application makes use of http://www.radio-browser.info/, RadioDroid does not keep a list of radio-stations, but rather fetches it from there. 

So it would help if manage to get them updated at http://www.radio-browser.info/ directly. Also it seems the ones found now do work fine again now, or?

**Comment by Wikinaut** [comment]
These work now, because I corrected the links.
