### ISSUE TITLE
Window state is not remembered

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#136]
I almost always use the Starred window but  the default window is opened when I
* hide the RadioDroid window (fixed) and switch back to RadioDroid. (fixed)
* turn off the screen, and then turn it on again.

**Comment by werman** [comment]
Should be solved by #188, last selected menu item is saved when app is paused and restored when app resumes.

**Comment by davidhedlund** [comment]
@werman Thanks.

**Comment by davidhedlund** [comment]
I updated the issue above:

> I almost always use the Starred window but  the default window is opened when I
> * hide the RadioDroid window (fixed) and switch back to RadioDroid. (fixed)
> * turn off the screen, and then turn it on again.
