### ISSUE TITLE
RadioDroid when clicked on notification do not go the the default mode

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#137]
When I click on RadioDroid on notifications I expect the app to open in default mode (as seen when I click on Apps -> RadioDroid). Instead a weird window without all the radio stations is being listed. The feautures in this non-default mode can be implemented in the default window.

Also, it is already possible to stop RadioDroid from Notifications.

**Comment by Wikinaut** [comment]
@davidhedlund With commit https://github.com/segler-alex/RadioDroid/commit/b72ec9472e5bb864f30b5aad8adcd0e339038201 (not yet available in the GooglePlay release) a new setting has been introduced so that you can define one of three start views (default=the old station view, your favorites, or your history).

To start with the "history" is what I recommend.

If you think, that this solves your issue, you could consider to close it.

**Comment by davidhedlund** [comment]
Have you changed the default mode to "history"?

**Comment by Wikinaut** [comment]
No, this is not possible, because after installation, there is no history then.

After a fresh installation, the behaviour is unchanged and RD starts with the view of stations, but you can manually select one of the mentioned three start views later. It works very well.

**Comment by davidhedlund** [comment]
I'm pretty sure that anyone agree that the view should be the last used view.

**Comment by Wikinaut** [comment]
Yes! I will discuss this with @segler-alex . It is his program...

I could code this:
* after installation, if the history is empty, show list of stations (like in the current release).
* as soon as one station has been played, set automagically to "start with history".
* users can override this default by selecting on the the three views.

I think, this makes sense, and I will code that. Thanks

**Comment by davidhedlund** [comment]
Good luck.

**Comment by Wikinaut** [comment]
fixed in version 0.44

total redesign: there are now four options to start:

* last played station (history)
* favorites
* all stations (search) view
* last view

**Comment by davidhedlund** [comment]
Great job @Wikinaut. Is it ok if I evaluate the new functions once the version has been uploaded to f-droig.org before I close this issue?

**Comment by Wikinaut** [comment]
@davidhedlund The quicker you close the better (in order to let us see only really "open issues", which require coding).
@segler-alex When do plan to upload to f-droid, when to Google Play? Just asking.

**Comment by davidhedlund** [comment]
Fixed. Thank you very much @Wikinaut.
