### ISSUE TITLE
Add an option to manually and periodically update the radio station database

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#138]
"A daily backup of the MariaDB tables is at www.radio-browser.info/backups/ and latest." - http://www.radio-browser.info/

I noticed early that a few stations works on radio-browser.info but the same stations do not work on RadioDroid. I assume RadioDroid updated an internal database but each time the app is being updated to a new version. There should be two options:
* to manually update the database if your favorite station(s) don't work.
* to periodically update the database, say every day, week, month (the default option is "On RadioDroid upgrades").

For example, **psyradio * fm - psytrance**:
* Works with  [Radio Browser](http://www.radio-browser.info/gui/#/byname/psyradio%20*%20fm%20-%20psytrance) stream in VLC.
* Works with the RadioDroid-like app [Internet Radio](https://f-droid.org/packages/community.peers.internetradio/)
* Do not work on RadioDroid

**Comment by davidhedlund** [comment]
For example, *psyradio * fm - psytrance*:
* Work on http://www.radio-browser.info/gui/#/byname/psyradio%20*%20fm%20-%20psytrance
* Do not work on RadioDroid

**Comment by Cormak** [comment]
@davidhedlund @segler-alex That station works fine on Radiodroid 0.46. You just had to update the URL.

**Comment by davidhedlund** [comment]
@Cormak How do I update the URL?

**Comment by Cormak** [comment]
@davidhedlund That's very odd because Radiodroid 0.46 is definitely streaming that station for me. It plays fine on the wiki as well. What version of radiodroid are you using? 

To update the URL, you simply find that station in the Wiki and update the info for that station. 

http://www.radio-browser.info

Search for it there. It plays fine on the wiki when you press the play button for that station, so there's no need to edit it.

**Comment by davidhedlund** [comment]
@Cormak Ah, my version is 0.37. That's the current version on f-droid.org. Thank you.

**Comment by Cormak** [comment]
@davidhedlund I just installed 0.37 to confirm your issue, but it seems that 0.37 also streams psyradio * fm - psytrance perfectly fine. Perhaps there is another issue on your end? Can you play it on the stream's homepage?

**Comment by davidhedlund** [comment]
Fixed. Version 0.51 (F-Droid build) streams psyradio.fm - psytrance.
