### ISSUE TITLE
add favourites tab

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#14]
let the user mark stations as favourites, maybe with stars
display them in a separate tab

**Comment by DJaeger** [comment]
+1

**Comment by buche** [comment]
+1

**Comment by segler-alex** [comment]
added in version 0.10

**Comment by Wikinaut** [comment]
Thanks for implementing that. 

Would be nice to have the Favorite list as default start tab (instead of "most clicks")

**Comment by hurzl** [comment]
Yes please add it as tab, not in the menu.
