### ISSUE TITLE
Show play link

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#140]
I only find "Weblink" when I click on the options for any radio station.

Please add "Copy play link", the link used by RadioDroid to play the music, so people can share, debug, rip, and analyse the stream.

**Comment by Wikinaut** [comment]
Do you mean "Share (copy) the Station's Stream Url" ?

**Comment by Wikinaut** [comment]
@davidhedlund Do you mean "Copy stream Url to clipboard" ? Then pls. can I ask you to re-edit the issue title (yes, you can).

**Comment by Wikinaut** [comment]
This is implemented in https://github.com/segler-alex/RadioDroid/pull/188

**Comment by davidhedlund** [comment]
@Wikinaut Thanks. I'll usually close issues when they have been solved in the latest version published on F-Droid.

**Comment by davidhedlund** [comment]
Fixed.
