### ISSUE TITLE
Proprietary-free flavor for F-Droid

### ISSUE THREAD

**Issue by relan** [segler-alex/RadioDroid#142]
Could you please provide a Gradle flavor without Google Play Services? Google Play Services libraries are proprietary software and their inclusion in 0.36 prevents RadioDroid from updating in F-Droid.

**Comment by segler-alex** [comment]
Hi, i did not know that you can do flavours with gradle. If you can help, i would accept pull requests.
do you know how i tell fdroid to only use one flavour?

**Comment by relan** [comment]
> If you can help, i would accept pull requests.

Can't help with this right now, unfortunately.

> how i tell fdroid to only use one flavour?

Change `gradle=yes` to `gradle=flavor_name` in the [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/net.programmierecke.radiodroid2.txt). Or just ping me.
