### ISSUE TITLE
Play randomly resumed after a pause

### ISSUE THREAD

**Issue by werman** [segler-alex/RadioDroid#150]
Sometimes radio starts playing again after a pause, it can happend after 1 min or 30 or any time. This is the issue with mine pull request #148.

I'll try to fix it soon, shouldn't be hard.

**Comment by werman** [comment]
It seems I managed to resolve the issue with some other improvements. Will test for a day and see if everything is ok.

**Comment by SpotComms** [comment]
@segler-alex after @werman fixes this, can a new release be pushed?
