### ISSUE TITLE
If station icons are shown in the station list view, then use the icon-click as "set as favorite"

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#187]
If station icons are shown, then:

* in the station list: use icon-click as "set as favorite"
* in the History list: use icon-click as "remove from History"
* in the Favorite list: use icon-click (perhaps) as "delete as favorite"

**Comment by werman** [comment]
I have uncommitted changes in the UI which may satisfy the need in a fast way to do something with station. I have removed floating context menu and made station items expandable, added flags (signify country of the station) and made tags clickable:

![radio_droid_new_station_item_design](https://user-images.githubusercontent.com/3993671/31886398-cb4cec9e-b7fc-11e7-9028-39e61eed63be.png)

Since I made this I didn't have the time to finish changes but I think I will have it soon.

**Comment by Wikinaut** [comment]
Can you rebase your changes to the present master branch and supply a regular pull request? Then I will be happy to test your improvement (I am not the core developer, just a helper...).

**Comment by Wikinaut** [comment]
@werman Can you rebase your changes to the present master branch and supply a regular pull request? Then I will be happy to test your improvement (I am not the core developer, just a helper...).

**Comment by werman** [comment]
Yes, I'll do it soon (when time permits), also I'll add "remove from history" as you proposed.

**Comment by Wikinaut** [comment]
@werman see also #172

**Comment by Wikinaut** [comment]
@werman There is also a request to share the stream url as  text (copy stream url to clipboard), perhaps you can implement this as well.

**Comment by Wikinaut** [comment]
@werman Click onto station logo -> Play **and** set as favorite. Would you like that?

**Comment by werman** [comment]
@Wikinaut I find assigning separate action for an icon will be a bit confusing for a user because icon doesn't indicate any separate action and ui should follow rules which user expects.

In the end it can be made as option turned off by default.

And about removing from history - I'll try to add it soon.

**Comment by Wikinaut** [comment]
@werman personally I am an "optionist" (I **like** user options). And I fully agree with your view, that this may puzzle (standard) users.

Summary:
let me propose a new option "Click onto station logo adds station as favorite".

**Comment by Wikinaut** [comment]
@werman Hi, can I kindly ask you to help with implementing this basically? This would be great. I had a look to the new code, and it may be quicker and easier, if you implement it.

I will then implement the new option (as proposed above) so that users then can enable or disable the feature that a click onto the station logo adds that station to the favorite list.

**Comment by werman** [comment]
@Wikinaut I can do this.

**Comment by Wikinaut** [comment]
@werman I started work. See my partial fix - my branch "fix-187" - for the "holder" section, this already works. So when the detailed view is active, a click onto the icon adds this station to the favourites.

There is more work to be done in FragmentStations and ItemAdapterStation, but until now I was unable to get that working, perhaps you can help to fix this there.

**Comment by werman** [comment]
@Wikinaut Hi, what exactly you have troubles to do? And why add to favorites only in expanded state, there is a star icon already, to test it?

**Comment by Wikinaut** [comment]
@werman yes, for a test, and this was easy to add therein. I do (currently) not know how to add a clickhandler for the imageViewIcon where there is part of the Layout list_item_station and added many lines of code, decided then to ask you.

**Comment by werman** [comment]
@Wikinaut Could you clarify, clicks aren't working for imageViewIcon when station item is being in the RecyclerView?

**Comment by Wikinaut** [comment]
@werman Currently they work like the whole station item click (and start playing). I simply do not know how to setup a dedicated clickhandler for the station icon. May be very simple.

**Comment by werman** [comment]
@Wikinaut Now I understand, I am looking into it.

**Comment by werman** [comment]
@Wikinaut I do not get any issues by assigning callback to imageViewIcon - when clicking on icon I get 
 callback from the icon, when I click outside - station starts playing. I have added star/unstar on image click for both item states and it just works.

**Comment by Wikinaut** [comment]
@werman Where can I find the code? You haven't pushed a branch yet.

**Comment by werman** [comment]
@Wikinaut Here it is: 1a2e2747ebaecaf2f94d47c82129ccf8ddee8979

**Comment by Wikinaut** [comment]
@werman Thank you very much, danke, you saved my day. I now start further work on this issue - adding a user preference for this, for example.
