### ISSUE TITLE
make fullsize start/stop button on station detail view

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#19]
- [ ] make fullsize start/stop button on the station detail view <img src="https://i.imgur.com/g0MQNLQ.png"><br/>(picture taken from my version https://github.com/Wikinaut/RadioDroid ) 

"Fullsize" means: use available remaining space

**Comment by glitchphan** [comment]
I suggest a circle Play button at bottom right, material design style. Praise DuARTe :).
