### ISSUE TITLE
Missing artwork

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#20]
I just added Intergalactic FM to http://www.radio-browser.info/gui/ They show up immediately in the app, but the artwork is missing or blank. Sometimes space is reserved for the artwork and sometimes not. Changes after playing one of the channels.

**Comment by PanderMusubi** [comment]
With all the updates of the app recently, this is unfortunately still a problem.

**Comment by segler-alex** [comment]
which stations do you mean?
if the artwork does not show up, java is not able to read the image. i think only jpg and png work.

**Comment by PanderMusubi** [comment]
Serach for `intergalactic` in the web interface. That will result in for streams with PNG images. These are just a few examples of streams that do not have an image in the app.

**Comment by segler-alex** [comment]
should be fixed now
