### ISSUE TITLE
Feature Request: Auto-stop on headphones disconnect

### ISSUE THREAD

**Issue by glitchphan** [segler-alex/RadioDroid#22]
Please implement auto-stop when headphones (wired or Bluetooth) are disconnected. An option to auto-start the last station on connect would be nice too, if possible, but not as important.

**Comment by tanty** [comment]
This is an important one!

**Comment by davidhedlund** [comment]
Yeah, its simply not convenient to listen to music without this feature. If the headphones cable loosening it will be embarrassing if use on boring events where the audience is silent. Everyone will look at you.

**Comment by glitchphan** [comment]
I'm using 0.37 version now. Connected Bluetooth headphones, hit play, heard music through headphones, turned off headphones, music stopped. Same experience with wired. Also, started playing unplugged, plugged in headphones and music kept playing through them, unplugged and music stopped. Beautiful.

**Comment by davidhedlund** [comment]
https://github.com/ram-on/SkyTube/issues/435

**Comment by davidhedlund** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/81
