### ISSUE TITLE
[Improvement] Expanded view: add delete button (waste bin icon) to delete that station item from history or favorite list

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#225]
see also #212

**Comment by Wikinaut** [comment]
@werman A task for you :-)

**Comment by Wikinaut** [comment]
@werman I mean to  add a fifth icon in the expanded view to remove that station item from either the favorites respectively the history list.

**Comment by werman** [comment]
@Wikinaut In #212 you suggested to add 'Swipe to remove' so additional button will be a duplication of the functionality if swipe will be implemented, on the other hand one may prefer a button to a gestures. 
I'll add swipe first and then we will see if additional button is needed.

**Comment by Wikinaut** [comment]
I think, a button _could_ be added, if you want (I am in favour of it, but not insisting).

Closing this, because functionality is present since https://github.com/segler-alex/RadioDroid/commit/298ed27325231b3d63a218967403b75287f92ad9
