### ISSUE TITLE
Music keeps playing when call comes in

### ISSUE THREAD

**Issue by glitchphan** [segler-alex/RadioDroid#23]
When I'm playing a stream in the car, connected via Bluetooth, and a call comes in, the music stops playing over the stereo but keeps playing in the earpiece while on the call. It seems the caller doesn't hear it, just me. Same behavior without being connected with Bluetooth, just using phone speaker.

**Comment by werman** [comment]
It was fixed by #148

**Comment by glitchphan** [comment]
Using 0.37 now. Started playing some music on phone, called myself from another phone and could no longer hear music. Once I hung up, music playback resumed. Excellent.
