### ISSUE TITLE
[Improvement] Change the notification icon according to play or pause status

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#230]
Icon in the notification should reflect the Player status.

**Comment by Zykino** [comment]
It would be nice to have the icon of the radio playing in notification too (when downloaded, wich should be the default for me)

**Comment by Cormak** [comment]
There should be a button even if the notification is not expanded. Makes using it a lot quicker than flicking it down and pressing pause or stop.
