### ISSUE TITLE
 [Improvement] Make search function "suggesting"

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#231]
Make search function suggests **as you type** (after entering 2 or 3 characters).

**Comment by Wikinaut** [comment]
@segler-alex @werman can you? I really wish like to see this implemented.

**Comment by werman** [comment]
@Wikinaut I definitely can implement this, but I don't have the time for it as for now. Anyway I can help if you are willing to implement it.

There is a lot to improve in the search like narrowing search by tags, bitrate, country, ... However quick suggestions will be a good start.

Some details I have thought of:

- Results should be displayed even if one character is typed but from local station lists (to reduce requests amount).
- When there is a small number of suggestions or query is like 3 - 4 characters long - make a search request.
- Search request is forced if user presses a search button.
- N last search results should be cached to reduce requests amount and improve responsiveness.

**Comment by Wikinaut** [comment]
Implementation idea:

* recycle (use) code from the Wikipedia App https://github.com/wikimedia/apps-android-wikipedia , most likely from https://github.com/wikimedia/apps-android-wikipedia/tree/master/app/src/main/java/org/wikipedia/search

**Comment by Wikinaut** [comment]
* Soll ich mich hier ranwagen, oder kann es einer von Euch machen ?
* Would prefer if someone of you can implement that in the near future.

**Comment by Wikinaut** [comment]
Updated a new issue #309.
