### ISSUE TITLE
On small devices, when playing, STOP button is hidden in additional 3-dot-settings

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#24]
see images, the left one shows the status *while* playing. On small screens, no Stop button is apparent.

After starting PLAY, the STOP button is "hidden" under the three-dot-settings. It's therefore difficult to find, and not user-friendly.

Suggestion: change style (layout) for the buttons, or implement #19 .

<img src="https://i.imgur.com/f9bfE0L.jpg" width=250> <img src="https://i.imgur.com/6eUw74l.jpg" width=250>

**Comment by segler-alex** [comment]
detail view does not exist anymore

**Comment by Wikinaut** [comment]
but see #31 (it would be nice to have the detail view back as such via the (new) three-dot-context menu on the station list view. it was always nice to see the tags, to be able to got to the station's home page etc.)
