### ISSUE TITLE
[Bug] When rotating the phone, the selected tab (view) is not preserved

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#240]
This problem is also present in older versions, so it appears not to be a "regression" due to the implementation of the startup-view preference.

**Comment by werman** [comment]
You mean the selected tab and its state in "Stations" is not preserved, right?

**Comment by Wikinaut** [comment]
See also changes introduced in https://github.com/segler-alex/RadioDroid/commit/cfce79ba2009a92a4d57036e4ae3897913ba4c6e . The bug was though present before this change.

**Comment by avently** [comment]
@Wikinaut please, check current source code. I think the issue can be closed

**Comment by Wikinaut** [comment]
@avently yes, indeed. Problem appears to be solved. Closing this issue now.
