### ISSUE TITLE
[Bug] Streamtitle character encoding issue in ActivityPlayerInfo with certain stations such as "rbb kulturradio"

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#241]
Text in PlayerInfo and notification has incorrectly coded non-ASCII-characters

![screenshot_20171118-105054](https://user-images.githubusercontent.com/1151915/32979080-cba0ad0a-cc4e-11e7-8c7d-eab8c7031970.png)

Willkommen in der KodierungshÃ¶lle !

**Comment by ZeroDot1** [comment]
When I listen to a station, ÄÖ and Ü are not displayed correctly for some songs.
Screenshots:
![bildschirmfoto_2018-04-13_17-08-28](https://user-images.githubusercontent.com/28985171/38742602-53c61650-3f3d-11e8-862d-6d44318d0893.png)
![bildschirmfoto_2018-04-13_17-07-53](https://user-images.githubusercontent.com/28985171/38742603-53fb7caa-3f3d-11e8-9acb-8e9ad413d4b1.png)

The app is really great.
I have already added some radio stations and fixed some broken ones.
http://www.radio-browser.info/gui/#/bytag/h%C3%B6rspiel
In the future I will add stations to the database and fix broken ones.

**Comment by Wikinaut** [comment]
@ZeroDot1 danke für's Hier-melden!

**Comment by ZeroDot1** [comment]
@Wikinaut No problem, I hope the little bug is fixed soon.

**Comment by segler-alex** [comment]
i will look into it, some stations do not follow specifications.
i have to do some kind of guessing for encoding

**Comment by ZeroDot1** [comment]
@segler-alex Thank you very much :) Very good work!

**Comment by Wikinaut** [comment]
It looks to me as if this problem is solved in the current master branch, thus I close the issue I reported.
