### ISSUE TITLE
[Improvement] Layout changes in Favorites list

### ISSUE THREAD

**Issue by olaf4** [segler-alex/RadioDroid#245]
Typographic changes: 

- change **station names** to bold typeface, about 2 pt bigger
- make the **station description** about 2 pt smaller
- add about 0.2 mm **padding** between icon and both text fields

Example of modified Screenshot: 
[http://www.engon.de/temp/github/Radiodroid_img01.png](http://www.engon.de/temp/github/Radiodroid_img01.png)

**Comment by werman** [comment]
The UI you have is the old one, there were a lot of changes that probably aren't in Google Play or F-Droid. You can see them in #188.

@segler-alex  @Wikinaut I think it can be a good idea to add screenshots, general capabilities of the app and maybe changes in last versions to the readme.

**Comment by Wikinaut** [comment]
@werman @segler-alex When will you update the Google Play version?
