### ISSUE TITLE
Improvement of favorites list

### ISSUE THREAD

**Issue by hoppalfi** [segler-alex/RadioDroid#249]
Hi, 
RadioDroid is great for me!
I just got an idea with the favorites list ... I think it should provide a possiblity to change the order of the items (currently, it only seems to be entry-ordered). I thought it might be easy to provide an option at each favorite entry like (move up one positon) or (move down one position), if possible?

Best regards,
Olaf

**Comment by Wikinaut** [comment]
duplicate of #72.
pls. close if you think, I am correct.

**Comment by Wikinaut** [comment]
see also #78 (closed, because duplicate of #72)

**Comment by hoppalfi** [comment]
Agreed :-)
