### ISSUE TITLE
Feature Request: Start playing by long press

### ISSUE THREAD

**Issue by buche** [segler-alex/RadioDroid#25]
The radio app Transistor (found on F-Droid) has the feature to start playing when you do a "long press" on the radio entry in the list of radio stations. You need not to open the detail view just to listen to a radio station. It would be nice to have a similar feature in RadioDroid.

**Comment by Wikinaut** [comment]
I think, this is implemented now (short press starts playing), I like it. Detail view (context menu for station in the list) can be opened by clicking the three dots.

(issue can be closed, in my view)
