### ISSUE TITLE
Add version number in About

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#254]
I couldn't see the version number in About. Can you please add it?

**Comment by Cormak** [comment]
I can confirm that 0.37 stable does not show the version number, but 0.46 beta does. 

We should have the version number in nice bold text for every version of Radiodroid henceforth.

**Comment by Wikinaut** [comment]
@davidhedlund This is already implemented in the master branch version, which is now also available with Google Play (you need to download the BETA version), or f-droid (version 0.46).

**Comment by davidhedlund** [comment]
Fixed.
