### ISSUE TITLE
Cast is broken on 0.47 beta

### ISSUE THREAD

**Issue by kulmegil** [segler-alex/RadioDroid#258]
The cast icon is there.
It connects to my chromecast (RD interface is visible on TV).
Playback still starts on phone.

Env:
RadioDroid v0.47, Play Store variant
OnePlus 3T with Android 7.1.2
Chromecast Ultra firmware 1.28.100555

**Comment by werman** [comment]
@segler-alex Is there any way to test chromecast support without having the device itself?

**Comment by segler-alex** [comment]
fixed in 0.48 in the beta channel
