### ISSUE TITLE
[Improvement] Better integration of ExoPlayer to improve experience with unstable connection

### ISSUE THREAD

**Issue by werman** [segler-alex/RadioDroid#259]
At the moment with unstable connection stream is stopped many seconds before buffered content ends. E.g. we have 25s buffered, connection dropped when 15s left and playback is stopped until connection restored, but we had those 15s to play while restoring the connection.

The issue is that local proxy is used to deliver content to ExoPlayer which is suboptimal approach and it is a legacy needed for MediaPlayer. While ExoPlayer itself can play streams with DefaultHttpDataSource it doesn't retrieve shoutcast data. So the solution is to create custom HttpDataSource based on okhttp3 (like currently done in proxy). This way buffers will be copied less times and the solution is much cleaner.

I have made custom HttpDataSource and it works with stable connection.

Current issues:
- I don't see documentation where is specified how to correctly restore failed connection, from code ExoPlayer doesn't handle lost connection so HttpDataSource should handle it. I try to reconnect when any exception on read data from stream occurs and reconnect is itself retried when failed. I haven't tested it yet but there may be an issue with stream discontinuity since I don't see requirements for HttpDataSource if there any to mitigate it (there is a logic in ExoPlayer which mitigates discontinuities but it is not clear how and when it works). 
- Recording of a stream is done before ExoPlayer processes the data but it seems it is possible to capture processed output where discontinuities should probably be fixed and it will work a lot better with hls streams which I will describe in another issue. In https://github.com/google/ExoPlayer/issues/1167 is mentioned that it's possible to override the method in [MediaCodecAudioRenderer ](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L312) which processes the output.
- With these changes code that support MediaPlayer and ExoPlayer will diverge so now it should be considered to drop MediaPlayer support.

I will post the progression here and I'm open to any suggestions.

**Comment by Cormak** [comment]
I mentioned dropping Mediaplayer support before and I really think Exoplayer is more than enough to handle all streams, You can even see the proxy being mentioned in the notification, leading me to believe that this whole approach to streaming is unfinished and should just be redone solely with Exoplayer.

**Comment by segler-alex** [comment]
the use of the default mediaplayer helps to get radiodroid working on older android versions. please think of that and of people with older phones

**Comment by werman** [comment]
@segler-alex Yes, that's why I only consider the option of removing it. It's still possible to left the old code to support MediaPlayer - it just won't have new features, I'll try to make it this way. Still, new features are needed to be done to have stable radio playback.

**Comment by Cormak** [comment]
@segler-alex According to the latest Android statistics, only 1% of users has a phone older than 4.1 and most people have 6.0 or higher. Android users tend to be very enthusiastic about having the latest OS on their device. A person who installs Radiodroid instead of a very popular mainstream player like iHeartRadio is way more likely to keep their device up to date than be stuck.

https://developer.android.com/about/dashboards/index.html

You can easily drop support for anything below Android 4.1 and not have any complaints. 

If people are stuck on a version of Android older than 4.1 they should do themselves a favor and get a new phone or install a custom ROM instead of making themselves vulnerable to malware.

**Comment by werman** [comment]
@Cormak @segler-alex I would consider the following - are there users on this android version at the moment (maybe there is statistics in play store console, never worked with it)? 
If there is no one - I think old MediaPlayer should be dropped for the sake of maintainability. If there are such users we should consider to left it for now. 

Also next questions should considered:
- Will user of old android see old version of RadioDroid in Play Store or nothing at all.
- Will user of old android see old version of RadioDroid in F-Droid or nothing at all.

Since the server api is stable user will be able to just use old version if it can be supplied to him.

**Comment by Cormak** [comment]
@werman People will always be able to get the old version. We have to start looking into the future of the project and fix the stability of streams instead of worrying about people who probably already have a new enough version of Android.

Mediaplayer if anything, is holding this project back.

**Comment by segler-alex** [comment]
123 people from 5298 are currently using android versions older than 4.1 i only have numbers from google but not fdroid of course

**Comment by werman** [comment]
@segler-alex Thanks for the stats! We should keep it then.

**Comment by werman** [comment]
Update: reconnection works perfectly, if there is some buffered data left - reconnection will be seamless as it should.

**Comment by werman** [comment]
I have done most of the work, see https://github.com/werman/RadioDroid/commit/2e7cc1e8cd4511e7d367008405efe66f3ce82b00. There are still a lot of things to improve and test, I hope I'll finish it soon.

About recording:
It is still recorded directly from station's stream, because intercepting data before it goes into a codec in ExoPlayer proved to be dead end since it is stripped of all metadata which is needed to save file. Another option is to encode data with codec into another format but I think we don't need this.
