### ISSUE TITLE
Have new 0.49 Miniplayer expand to fullscreen player when tapped?

### ISSUE THREAD

**Issue by ghost** [segler-alex/RadioDroid#267]
The changes in 0.49 are great but the miniplayer seems limited to just that, a bar that switches between record button and a play button when tapped. 

Wouldn't it be more consistent to have the miniplayer expand to a fullscreen player with a record button, timer, information when tapped? Swiping down on the fullscreen player would then allow you to minimize it to a miniplayer. That would be a lot more consistent and intuitive than what we have now.

**Comment by werman** [comment]
If no one will start before me on this I'm planning to implement the player's page.

My current list of features:
- Radio station name, current song name, downloaded bytes.
- Current song's album art or whatever supplied by station if any.
- Playback buttons: pause/start, record/stop recording, mute/unmute (see #262)
- Recording status: file, size
- List of last songs played on current station. Maybe it would be better to have e.g. 30 last songs played. Songs could be searched, could be launched lyrics app, maybe some other options.

Any suggestions/improvements to this list are welcomed.

**Comment by Cormak** [comment]
@werman Sounds just about perfect but I'd need to use the player page for myself to give any proper feedback. If you post a test apk when you're done, I'd be glad to test it and give whatever feedback I can.

**Comment by avently** [comment]
@werman I have just one suggestion. Please, make this page with height equals half of a screen or smaller. Radio doesn't need many controls or huge place for artwork so half of the screen will be enough. As an example,  take a look at the screenshot from FastHub.
![screenshot_20180109-165720](https://user-images.githubusercontent.com/7953703/34724326-778a228a-f55e-11e7-9157-53fdb7802c36.png)

**Comment by werman** [comment]
@avently There is enough information to fill the whole screen, like displaying a list of played songs, but I like your idea to have half screen version of the page. I think may be good to have three states: 
- Mini player.
- Half screen player with all controls and current artwork.
- Fullscreen player with list of past songs and whatever we can think of.
The switch between them can be done by swipes or clicks.

**Comment by werman** [comment]
@segler-alex  @avently @zo-shin 

[Video of work-in-progress full screen player](https://i.imgur.com/MfMydVI.mp4)

- Some information is still missing.
- Recording part is not functional
- I'm not sure what to do when there is no album art or if user will opt out of downloading it. My current idea is  this lib: https://github.com/gauravk95/audio-visualizer-android
- And some other smaller issues.

**Comment by avently** [comment]
Take a look at this picture. I think these bottom controls for play/pause and other actions looks better than we have now.  ![](https://i.imgur.com/dwGK6Zi.png)

**Comment by werman** [comment]
> You added a list of some songs like Wait and bleed, Lifetime, etc. What these songs are? Is it a played history or recordings? 

That's a history of played tracks.

**Comment by werman** [comment]
> You added a list of some songs like Wait and bleed, Lifetime, etc. What these songs are? Is it a played history or recordings? 

That's a history of played tracks.

> Where did you get an artwork and other info about song?

Via lastfm api.

> From my point of view, this down arrow with expandable list is too heavy for a fullscreen player. Without down arrow user will be able to tap on a list item and Alert window will show up with all interesting information. So your main player will be lightweight (without expandable list at all) and you can show all interesting info in alert.

That's could be a good idea, thank.

> Also buttons should be without text but with icons (lyrics, copy info). IconNinja is a good resource for svg icons if you need some.

Icons without the text are confusing, that's of course my opinion but I often cannot decipher icons meaning, however having them + text in a popup window could be a good idea.

> What text 3:44 and 00:30 means?

Still don't know a good way to display them, it will be a total time played and buffered time.

> Also while you are opening the player appbar is hiding After player but should do it before player.

Yep, that's one minor glitch.

> At the bottom you have empty space for a button. Maybe it is the best place for a button which opens an alert with recordings.

Hmmm, may be, may be.

> Take a look at this picture. I think these bottom controls for play/pause and other actions looks better than we have now. 

Yes, but I think play button should be filled with colour since it should be visible on background.
