### ISSUE TITLE
APP Crash

### ISSUE THREAD

**Issue by axel-rank** [segler-alex/RadioDroid#286]
Googl Play Version (0.51) doesn't start, crashes immediately on ASUS Zenfone 2 Laser (ZOOED), Android/Lineage 7.1.2. 
F-Droid Version working, but doesn't have the same features/settings (theme, recording) like Google Play Version

**Comment by werman** [comment]
Hello, could you attach logs from logcat if possible? I have successfully installed and launched v0.51 on Nexus 5 with Lineage 7.1.2. 
Did you update the app or installed it from scratch?

Thank you for the report!

**Comment by axel-rank** [comment]
Sorry, logs from logcat? Dont't know where to find.
Just reinstalled Lineage again, same problem with Google Play Version: Crash after start.
But now: F-Droid Version Working has the same features like Google Play Version and everythings working!
Great App!

**Comment by werman** [comment]
@axel-rank Great, and it means we can narrow the issue, google play version has also chrome cast support, for other features they are equal.
