### ISSUE TITLE
Unable to record radio

### ISSUE THREAD

**Issue by Psykukumber** [segler-alex/RadioDroid#287]
Hello.

When I try to record radio station, its just a red round and nothing more. If I tap on that round than a square blinks less than a second and nothing happens.

Android version: 6.0 (Marshmallow)

![Recording bug](http://i103.fastpic.ru/big/2018/0121/22/444ab189e03543c5a251577136c4bd22.png)

**Comment by werman** [comment]
Hello, could you specify the station?

**Comment by werman** [comment]
Also, stupid question: is the station playing at the moment of recording attempt? There is a lack of feedback to user about what's wrong with the recording at the moment...

**Comment by Psykukumber** [comment]
@werman Yes, station plays when I try to record.

**Comment by werman** [comment]
@Psykukumber Could you attach logs from logcat if possible? I cannot spot any obvious issue here.
Also did recording work in previous versions?

**Comment by Psykukumber** [comment]
@werman I just tried versions 0.48 and 0.37. In both of them I can start recording, but unable to stop and cant see any saved recordings.

**Comment by Psykukumber** [comment]
Here a log that I take by alogcat. Hope this will be useful

--------- beginning of system
D/ActivityThread( 1238): ACT-AM_ON_PAUSE_CALLED ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-PAUSE_ACTIVITY handled : 3 / android.os.BinderProxy@6013658
V/ActivityThread( 1238): Finishing stop of ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}: show=false win=com.android.internal.policy.PhoneWindow@a482b97
--------- beginning of main
V/PhoneWindow( 1238): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{2d7c7e8 org.jtb.alogcat/org.jtb.alogcat.LogActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{2c03417 I.E...... R.....ID 0,0-720,1280}
D/ActivityThread( 1238): ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@6013658
D/Surface ( 1238): Surface::disconnect(this=0xafb6fa00,api=2)
D/GraphicBuffer( 1238): unregister, handle(0xaa7b0b80) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/GraphicBuffer( 1238): unregister, handle(0xb3af89a0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/GraphicBuffer( 1238): unregister, handle(0xaa7b0cd0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
I/System  ( 1238): FinalizerDaemon: finalize objects = 1
V/ActivityThread( 1238): Performing resume of ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-AM_ON_RESUME_CALLED ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
V/ActivityThread( 1238): Resume ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} started activity: false, hideForNow: false, finished: false
V/ActivityThread( 1238): Resuming ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} with isForward=true
V/PhoneWindow( 1238): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{2d7c7e8 org.jtb.alogcat/org.jtb.alogcat.LogActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{2c03417 V.E...... R.....ID 0,0-720,1280}
V/ActivityThread( 1238): Scheduling idle handler for ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-RESUME_ACTIVITY handled : 1 / android.os.BinderProxy@6013658
D/WindowClient( 1238): Add to mViews: android.widget.LinearLayout{bccc184 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@6c37d0b
D/ViewRootImpl( 1238): disable hardware acceleration by APP!!!, this = ViewRoot{41671f0 Toast,ident = 2}
D/Surface ( 1238): Surface::connect(this=0xafb6fa00,api=2)
D/GraphicBuffer( 1238): register, handle(0xa946cc40) (w:720 h:1280 s:720 f:0x2 u:0x000933)
V/InputMethodManager( 1238): onWindowFocus: null softInputMode=272 first=true flags=#810100
V/InputMethodManager( 1238): START INPUT: com.android.internal.policy.PhoneWindow$DecorView{2c03417 V.E...... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@3e5d369 controlFlags=#104
D/GraphicBuffer( 1238): register, handle(0xa946ccb0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/Surface ( 1238): Surface::connect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): register, handle(0xa946cd20) (w:425 h:88 s:432 f:0x1 u:0x000933)
D/GraphicBuffer( 1238): register, handle(0xa946ce00) (w:720 h:1280 s:720 f:0x2 u:0x000933)
V/InputMethodManager( 1238): START INPUT: android.widget.ListView{43989f7 VFED.VCL. .F....ID 0,0-720,1136 #102000a android:id/list} ic=null tba=android.view.inputmethod.EditorInfo@fcb60a controlFlags=#100
D/Surface ( 1238): Surface::disconnect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): unregister, handle(0xa946cd20) (w:425 h:88 s:432 f:0x1 u:0x000933)
D/WindowClient( 1238): Remove from mViews: android.widget.LinearLayout{bccc184 V.E...... ......I. 0,0-425,88}, this = android.view.WindowManagerGlobal@6c37d0b
D/WindowClient( 1238): Add to mViews: android.widget.PopupWindow$PopupDecorView{73403e0 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@6c37d0b
D/ViewRootImpl( 1238): disable hardware acceleration by APP!!!, this = ViewRoot{9941699 PopupWindow:a4212,ident = 3}
V/InputMethodManager( 1238): Not IME target window, ignoring
D/Surface ( 1238): Surface::connect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): register, handle(0xa9470910) (w:424 h:422 s:432 f:0x1 u:0x000933)
D/GraphicBuffer( 1238): register, handle(0xa9470980) (w:424 h:422 s:432 f:0x1 u:0x000933)

**Comment by Psykukumber** [comment]
Here a log that I take by alogcat. Hope this will be useful

--------- beginning of system
D/ActivityThread( 1238): ACT-AM_ON_PAUSE_CALLED ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-PAUSE_ACTIVITY handled : 3 / android.os.BinderProxy@6013658
V/ActivityThread( 1238): Finishing stop of ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}: show=false win=com.android.internal.policy.PhoneWindow@a482b97
--------- beginning of main
V/PhoneWindow( 1238): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{2d7c7e8 org.jtb.alogcat/org.jtb.alogcat.LogActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{2c03417 I.E...... R.....ID 0,0-720,1280}
D/ActivityThread( 1238): ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@6013658
D/Surface ( 1238): Surface::disconnect(this=0xafb6fa00,api=2)
D/GraphicBuffer( 1238): unregister, handle(0xaa7b0b80) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/GraphicBuffer( 1238): unregister, handle(0xb3af89a0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/GraphicBuffer( 1238): unregister, handle(0xaa7b0cd0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
I/System  ( 1238): FinalizerDaemon: finalize objects = 1
V/ActivityThread( 1238): Performing resume of ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-AM_ON_RESUME_CALLED ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
V/ActivityThread( 1238): Resume ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} started activity: false, hideForNow: false, finished: false
V/ActivityThread( 1238): Resuming ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} with isForward=true
V/PhoneWindow( 1238): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{2d7c7e8 org.jtb.alogcat/org.jtb.alogcat.LogActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{2c03417 V.E...... R.....ID 0,0-720,1280}
V/ActivityThread( 1238): Scheduling idle handler for ActivityRecord{d6cdf3b token=android.os.BinderProxy@6013658 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}}
D/ActivityThread( 1238): ACT-RESUME_ACTIVITY handled : 1 / android.os.BinderProxy@6013658
D/WindowClient( 1238): Add to mViews: android.widget.LinearLayout{bccc184 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@6c37d0b
D/ViewRootImpl( 1238): disable hardware acceleration by APP!!!, this = ViewRoot{41671f0 Toast,ident = 2}
D/Surface ( 1238): Surface::connect(this=0xafb6fa00,api=2)
D/GraphicBuffer( 1238): register, handle(0xa946cc40) (w:720 h:1280 s:720 f:0x2 u:0x000933)
V/InputMethodManager( 1238): onWindowFocus: null softInputMode=272 first=true flags=#810100
V/InputMethodManager( 1238): START INPUT: com.android.internal.policy.PhoneWindow$DecorView{2c03417 V.E...... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@3e5d369 controlFlags=#104
D/GraphicBuffer( 1238): register, handle(0xa946ccb0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
D/Surface ( 1238): Surface::connect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): register, handle(0xa946cd20) (w:425 h:88 s:432 f:0x1 u:0x000933)
D/GraphicBuffer( 1238): register, handle(0xa946ce00) (w:720 h:1280 s:720 f:0x2 u:0x000933)
V/InputMethodManager( 1238): START INPUT: android.widget.ListView{43989f7 VFED.VCL. .F....ID 0,0-720,1136 #102000a android:id/list} ic=null tba=android.view.inputmethod.EditorInfo@fcb60a controlFlags=#100
D/Surface ( 1238): Surface::disconnect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): unregister, handle(0xa946cd20) (w:425 h:88 s:432 f:0x1 u:0x000933)
D/WindowClient( 1238): Remove from mViews: android.widget.LinearLayout{bccc184 V.E...... ......I. 0,0-425,88}, this = android.view.WindowManagerGlobal@6c37d0b
D/WindowClient( 1238): Add to mViews: android.widget.PopupWindow$PopupDecorView{73403e0 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@6c37d0b
D/ViewRootImpl( 1238): disable hardware acceleration by APP!!!, this = ViewRoot{9941699 PopupWindow:a4212,ident = 3}
V/InputMethodManager( 1238): Not IME target window, ignoring
D/Surface ( 1238): Surface::connect(this=0xa1e1c300,api=2)
D/GraphicBuffer( 1238): register, handle(0xa9470910) (w:424 h:422 s:432 f:0x1 u:0x000933)
D/GraphicBuffer( 1238): register, handle(0xa9470980) (w:424 h:422 s:432 f:0x1 u:0x000933)

**Comment by werman** [comment]
Thank you, nothing about our app here (is there anything in log if filtered by radiodroid? Sorry didn't specified this beforehand). Does the app have "storage permission" (it should ask but who knows what might happen)? Do you have free space?
![image](https://user-images.githubusercontent.com/3993671/35196502-897726ba-fedb-11e7-810a-be4269ddf1b0.png)
If everything is ok the only way to investigate further will be for me to add more logs and send you custom version of the app if you'll agree.

**Comment by Psykukumber** [comment]
@werman
Hello, yes, storage permission is enabled and I have free storage. Unfortunately, I got nothing when try to filter logcat.

**Comment by avently** [comment]
@werman maybe it would be a good idea to make an option in settings to save debug log to internal storage. Then user will be able to upload it here.

**Comment by werman** [comment]
@avently It's a good idea to make debug logs accessible for users. I think writing them on storage should be optional (since it requires permission) and there should a screen with them in our app where they can be copied or saved.

Also I don't think it's an issue with codecs because they aren't involved in saving of stream, the stream content is just directly saved to file. Maybe something wrong with writing to file and as I said earlier error handling there isn't great so we need logging.

**Comment by orschiro** [comment]
I am having the same problem with the latest version 0.51. Recording works with previous versions. 

I hit the record button, it's creating the file but when opening the file after recording (with VLC), it doesn't play the file. I guess because it's empty?

I am on Android 4.3.

**Comment by Psykukumber** [comment]
Hi, since release of v0.53 it looks like problem was resolved, so I decide to close this bug.

Thanks.
