### ISSUE TITLE
Copy streamed title

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#297]
RadioBrowser 0.5.1.

It is not possible to "Copy title" of the streamed stations. Can you please add such function?

**Comment by Wiredframe** [comment]
It would indeed be great to be able to copy the title of the currently played song. Maybe a longpress on the title would do it?

**Comment by Wiredframe** [comment]
Absolutely agree. It just would be awesome if it was possible at all. :)

**Comment by werman** [comment]
I planned to add maximized version of the player where such functionality will be available but still wasn't even able to start.

**Comment by Wikinaut** [comment]
Currently, the title appears to be cropped (shortened). When you implement the function, pls. make sure that the full string is copied, thanks.

**Comment by Wiredframe** [comment]
Thank you all for this awesome app btw! Just discovered it a couple of days ago.

**Comment by davidhedlund** [comment]
@Wiredframe Welcome! Did you know that you can add and edit the stations directly on radio-browser.info used by RadioDroid?

**Comment by Wiredframe** [comment]
Yes I saw that its based on that library. All the stations I was looking for were already there. Really great.

**Comment by davidhedlund** [comment]
@Wiredframe Awesome.

**Comment by davidhedlund** [comment]
> I planned to add maximized version of the player where such functionality will be available but still wasn't even able to start.

This idea is a bit old now so I forgot that I submitted it. Is it possible to implement this function now?

**Comment by werman** [comment]
In the new full screen player there is a track history, you can copy track information from there (click history item in the list and there will be button you want). However this is in master and not in any released version.

**Comment by davidhedlund** [comment]
> In the new full screen player there is a track history, you can copy track information from there (click history item in the list and there will be button you want). However this is in master and not in any released version.

I'm glad to hear this. =) Did you implement this or what?

**Comment by werman** [comment]
Yes in https://github.com/segler-alex/RadioDroid/pull/495

**Comment by davidhedlund** [comment]
> Yes in #495

That's very helpful of you, thanks once again.

**Comment by segler-alex** [comment]
is implemented in the next release
