### ISSUE TITLE
String compare operations

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#3]
In https://github.com/segler-alex/RadioDroid/blob/master/src/net/programmierecke/radiodroid/RadioStation.java#L26 and other lines you compare strings using != operator. 

On Java, equals() is your friend.

See https://stackoverflow.com/questions/3405928/how-to-check-if-edittext-has-a-value-in-android-java and https://stackoverflow.com/a/3406005

**Comment by segler-alex** [comment]
fixed
