### ISSUE TITLE
History ("Verlauf") should - in my view - show only unique entries, and should not show doublures

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#30]
I notice in my history this (Example)
- (Station) A
- B
- C
- A
- A
- A
- B
- A
- A

I suggest to show a "cleaned" list, at least directly following same selections should be reduced to one entry:
- (Station) A
- B
- C
- A
- <s>A</s> (removed)
- <s>A</s> (removed)
- B
- A
- <s>A</s> (removed)
### resulting in (Variante 01)
- (Station) A
- B
- C
- A
- B
- A

or - this is what i prefer -

All (duplicate) previous entries are cleared, so that the history shows only the latest played stations, only one entry per station:
- <s>(Station) A</s>  (removed)
- <s>B</s>  (removed)
- C
- <s>A</s>  (removed)
- <s>A</s>  (removed)
- <s>A</s> (removed)
- B
- <s>A</s> (removed)
- A
### resulting in (Variante 02; I prefer this)
- C
- B
- A

**Comment by Wikinaut** [comment]
Algorithm Variante 01:
```
if (new station item to be added to history list) {
  if (new item == previous item) {
  delete previous item;
  add new item;
  }
}
```

Algorithm Variante 02:
```
if (new station item to be added to history list) {
  if (new item == previous item somewhere in the list) {
  delete previous item somewhere in the list;
  add new item;
  }
}
```

**Comment by hurzl** [comment]
👍

**Comment by Wikinaut** [comment]
@segler-alex Hi, can we have this ? Would be very nice...

**Comment by Wikinaut** [comment]
@segler-alex Any progress on this issue ?

**Comment by Wikinaut** [comment]
@segler-alex für den Anfang würde es schon reichen, d.h. eine Verbesserung sein, wenn Du einen neuen Verlaufseintrag *nicht* hinzufügst, wenn der gleich dem schon existierenden (vorherigen) ist.

**Comment by Wikinaut** [comment]
@segler-alex Es sieht so aus, als ob Du "einen neuen Verlaufseintrag nicht hinzufügst, wenn der gleich dem schon existierenden (vorherigen) ist.", stimmt's ?
