### ISSUE TITLE
[Suggestion][WIP] Make the station search a "suggesting" search which suggests as you type

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#309]
see #231 .

Make search function suggests as you type (after entering 2 or 3 characters).

I wish that someone of you co-developers perhaps also have the time to concentrate on an implementation of this really useful improvement.

**Comment by emes27** [comment]
Hello, if this will be implemented, please think of this might slow down the app at old phones. Maybe a on/off option for this function would be a good compromise? But imho please keep the app as simple as possible. Thanks for this app!

**Comment by Wikinaut** [comment]
@emes27 Don't worry about this. All modern apps are working this way since years, a partial query is only fired (sent to server) when a certain minimum amount of characters is typed (usually 2 or 3). I coded such things many times in the last two decades!

**Comment by werman** [comment]
Just my random thoughts: It would great if we store all stations locally on device in a database and just receive deltas or rare full updates thus enabling fast search and not relying on the server.

**Comment by Wikinaut** [comment]
I really would like to have this implemented. Has someone of you already implemented such a function elsewhere?

**Comment by werman** [comment]
@Wikinaut While I didn't make such thing in android, I can give you directions if you want to implement it.

**Comment by Wikinaut** [comment]
@werman I have experiences in implementing suggesting searches since two decades - but not in Android. I also have a working test version for Android which uses a small (fixed) list of stations.

Thanks offering your help.

**Comment by werman** [comment]
I have other issues to fix so if you van do this it would be wonderful. There should be an easy official way of doing this.

**Comment by Wikinaut** [comment]
Some years ago, there was (unfortunately) no such an easy official for suggesting searches and lists. It also requires (some) certain server work (who maintains the backend?), in order to prevent (D)DoS and overloads. So I need contact to the person who maintains the server.

**Comment by segler-alex** [comment]
i maintain the server

**Comment by segler-alex** [comment]
i think this is possible to do, i can handle more requests

**Comment by Wikinaut** [comment]
@segler-alex Ok.

**Comment by Wikinaut** [comment]
I think I normally send query after user has typed 3 or 4 characters. But for now I will be away from keyboard for some hours...

**Comment by Wikinaut** [comment]
@werman @segler-alex Here is a first *working* test version which uses *suggestions* to query station names from the radio-browser:

https://github.com/Wikinaut/AutoSuggestTextViewAPICall (branch: radiobrowser)

Idea and code forked from: https://www.truiton.com/2018/06/android-autocompletetextview-suggestions-from-webservice-call/

Not yet modified for example to start queries only when at least three characters are typed (which I would suggest to use).

**Comment by Wikinaut** [comment]
@zo-shin see above

**Comment by werman** [comment]
Some thoughts: 
I think it may be a good idea to perform local search first (through the current page, without sending requests) and also give ability to perform search in all stations which will be the one you are currently working on.

**Comment by Wikinaut** [comment]
@werman No, in my view this would make the (currently simple) suggesting autocomplete algorithm too complicated and think we should start with a plain vanilla replacement of the current search.

When this becomes working however, we could the highlight or otherwise mark such station entries (in the result list) which are already favorites and/or history members.

**Comment by werman** [comment]
Ok, it's better to have something stable working.

**Comment by Wikinaut** [comment]
Would someoneof you @werman @zo-shin @segler-alex be willing to implement the https://github.com/Wikinaut/AutoSuggestTextViewAPICall code in RadioDroid (I am not so experienced as you).

**Comment by werman** [comment]
I can, but I don't know when I will have a will to implement this.

**Comment by Wikinaut** [comment]
I am now starting to work on this!

**Comment by Wikinaut** [comment]
Hello, I am giving up (don't want to be #cookielicking). It looked to be easy but isn't in our current code layout. The internet has quite a few interesting tutorials how to add AutoCompleteTextView, for example https://stackoverflow.com/a/45140199 , but I feel overstrained to implement it. Perhaps, @werman, it's an easy task for you (it really could be).

**Comment by werman** [comment]
Ok, I'll see to it.

**Comment by Wikinaut** [comment]
@werman just as a reminder: on https://github.com/Wikinaut/AutoSuggestTextViewAPICall I prepared a *working* version of AutoSuggest which uses the radio-browser data.

**Comment by Wikinaut** [comment]
@werman I may be possible and easier to use the built-in autocomplete feature of SearchView (instead of using AutoCompleteTextView).

>I solved my problem. Actually the SearchView has built-in autocomplete feature but it needs a contentprovider. Instead of setting AutoCompleteTextView and its necessary functions, I simply create a ContentProvider that only does query not insert, delete. And it is solved. – tasomaniac Jul 19 '13 at 9:09
> https://stackoverflow.com/a/19990962

**Comment by werman** [comment]
I'm trying to go with slightly different route. I think that it would be better to display found stations in the current recycler instead of just their name like in AutoCompleteTextView. Thus I'm using https://developer.android.com/reference/android/widget/Filter . This way it would be possible to search by other attributes than name (if needed in future) and it should be easier to find the station this way (I think). I already wrote most code yesterday.

**Comment by Wikinaut** [comment]
any implementation which shows results as I type is welcome. Let me see code, and I will test a.s.a.p.

**Comment by werman** [comment]
Here is first working branch https://github.com/werman/RadioDroid/commits/feature/search-stations-as-typed

**Comment by Wikinaut** [comment]
Basically solved in https://github.com/segler-alex/RadioDroid/pull/626 . Closing this to get rid of it.
