### ISSUE TITLE
RadioDroid is affected by a bug on certain Custom ROMs

### ISSUE THREAD

**Issue by STPKITT** [segler-alex/RadioDroid#311]
Hello,
using a Samsung Galaxy Grand DUOS GT-I9082 running LineageOS 13.0 6.0.1_r79 from July 2017 I discovered that RadioDroid is affected by the bug treated in the following links. In those links you can see that the whole problem is fixed on recent Custom ROMs. Trouble is that a lot of devices are stuck on older ROM releases so RadioDroid development should do the necessary steps to avoid it like the developers on the app "Conversations" did (look at the last link).

https://issuetracker.google.com/issues/64434571

https://jira.lineageos.org/browse/BUGBASH-1052

https://gitlab.com/fdroid/fdroiddata/issues/979

https://github.com/siacs/Conversations/issues/2785

Thanks and greetings!

**Comment by werman** [comment]
Hello, thanks for the notification! The issue can be resolved by updating the build tools version to 27.x so it will be done soon.

**Comment by STPKITT** [comment]
Awesome! Thanks very much on behalf of all users of oldschool devices :-)

**Comment by DJCrashdummy** [comment]
is there an ETA for a new release, since the current version (0.53) is still effected?

btw: does someone know which version is the latest without this issue, which can be used until then?

**Comment by segler-alex** [comment]
you could try the version from fdroid. it comes without cast support. but maybe it works.
i am currently working on the backend. so radiodroid currently not on my list if there is no huge breaker for everyone. could you investigate more?

**Comment by DJCrashdummy** [comment]
sorry for not mentioning that: for sure i installed RadioDroid via F-Droid... :wink:
unfortunately i don't own the affected device so i hadn't enough time to test/find a working version myself, hence the additional question.
