### ISSUE TITLE
[Bug] The upgrade to version 0.54 cleared all my "favorites" and "last played"

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#318]
I am quite unhappy with the new version, which cleared all my "favorites" and "last played", what I regard as a bug, see also #305.

**Comment by Wikinaut** [comment]
see also #305

**Comment by avently** [comment]
And why did you create duplicate? Is one issue not enough to see the bug?

**Comment by Wikinaut** [comment]
@avently I personally did notice this problem _only_ when upgrading to the 0.54, not when upgrading earlier versions.
