### ISSUE TITLE
Version 0.13: back button closes App and views (looks strange)

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#32]
Was it intended ? A feature, or a bug ?

How to reproduce:
- start RadioDroid
- goto settings
- goto About ("Über")
- click "back button" (Android)

App shuts down, uh.

**Comment by hurzl** [comment]
👍

**Comment by segler-alex** [comment]
at the moment it's a feature.
but i am thinking about changing it to open another activity, so the stations activity stays.
would you change the behaviour of all items in the left drawer menu or only the ones you listed?

**Comment by davidhedlund** [comment]
RadioDroid 0.51

I get this message:

> Press back once more to exit:

when I press the back button in these windows:
* Settings
* TAGS
* COUNTRIES
* LANGUAGES

It should go back to the previous window.

Unaffected windows:
* Settings -> Statistics
* Settings -> About RadioDroid

**Comment by davidhedlund** [comment]
@segler-alex Can you please re-open the issue?

**Comment by davidhedlund** [comment]
Thank you very much!

**Comment by davidhedlund** [comment]
@segler-alex Perhaps you want to change the title too?

**Comment by davidhedlund** [comment]
@Wikinaut Why did you close the issue?

**Comment by davidhedlund** [comment]
This has still not been fixed in RadioDroid 0.53.

**Comment by Wikinaut** [comment]
This appears to be fixed. Use the beta channel version 0.53. There is then a notification "Press back once more to exit", so no unintended closing anymore.

**Comment by davidhedlund** [comment]
@Wikinaut I just said that it hasn't been fixed in RadioDroid 0.53 -- the F-Droid build to be exact.

**Comment by davidhedlund** [comment]
@Wikinaut Oh, https://github.com/segler-alex/RadioDroid/issues/32#issuecomment-361683979 is a separate issue, I'll open a new issue for it.

**Comment by Wikinaut** [comment]
@davidhedlund for me, it is fixed. As I reported the issue, I closed it.

If you still have a problem, which you think is similar, then can I ask you to reopen a new issue under your name, and add the steps how to reproduce it please?

**Comment by davidhedlund** [comment]
https://github.com/segler-alex/RadioDroid/issues/302

**Comment by davidhedlund** [comment]
@Wikinaut Thanks, see https://github.com/segler-alex/RadioDroid/issues/302
