### ISSUE TITLE
[Suggestion] New Icon for the App

### ISSUE THREAD

**Issue by cedenoruel** [segler-alex/RadioDroid#320]
As you may have noticed, app icons that look very simple (minimalist) are trending right now so here are my suggestions. What do you think? Which design and color scheme looks better? I will be happy to make adjustments. 

![radiodroid_showcase](https://user-images.githubusercontent.com/38007519/38351656-abd1d064-38da-11e8-832a-1a8c9aed6764.png)

**Comment by werman** [comment]
Good work! I like the first column more, I'm not sure about the colour though.

**Comment by cedenoruel** [comment]
Thanks. Please let me know what colors you prefer, I will make many color variations.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by werman** [comment]
I tried to say that personally I don't have any preferred color =). @segler-alex @Wikinaut @avently What do think about the icons?

**Comment by avently** [comment]
@cedenoruel which apps you use for inspirations for icons's background? I thought gradient for background is not usable anymore with "simple" style of icons.

Also I can be wrong but are headphones from 2 and 3 have rounded but not circular shape? I mean it looks distorted for me.

**Comment by cedenoruel** [comment]
What do you suggest then?

**Comment by avently** [comment]
@cedenoruel from my point of view background should have solid color. Icon should be circular (maybe in the future app will support multiple icon styles like in android 8) or without background at all (like Google translate or AFWall or Brave browser).
About inspiration. You can use Dives app for that. Thousands of icons. Most of them are beautifully designed. 
If you are asking me about my graphic example for RadioDroid I don't plan to do the icon. I have Nova Launcher and I can choose whatever icon I want.

**Comment by cedenoruel** [comment]
@avently I believe the purpose of logo and icons is to create branding and identity of the app. Choosing generic icons from Nova Launcher will not establish the brand's identity. And the logo and icons should ideally be similar to make it memorable to the users. 

I hope to hear the opinion of the lead developer and other contributors as well. Would love to hear more suggestions. Cheers! 

![radiodroid_3](https://user-images.githubusercontent.com/38007519/38536665-96324184-3cb4-11e8-9654-eeaf799217bb.png)

**Comment by avently** [comment]
1, 2, 3, 4, 7, 12 are cool. 10 and 11 looks interesting too, maybe the idea with colored sign on a white background is even better than others but i'm not 100% sure. I mean plain white circle as a background with red/blue colored sigh without red/blue space around circle. Something like inverted 1, 2, 3, 4. Did you try it? Is is good?

**Comment by cedenoruel** [comment]
![radiodroid_5](https://user-images.githubusercontent.com/38007519/38546528-16353630-3cd7-11e8-8315-d29c0381013e.png)

**Comment by avently** [comment]
Yes! Now I like 1, 2, 3, 4, 7, 12 from previous example and 1,2,3,4 from current:)

What do you like more?

**Comment by cedenoruel** [comment]
Glad you like it! Please let me know if the team makes a decision. I will send the vectors (.svg, .eps) and complete set of png files in different sizes once you selected the final design.

**Comment by avently** [comment]
@segler-alex @Wikinaut @werman what you think about provided icons?

**Comment by werman** [comment]
Great work! I like this icon design:
![image](https://user-images.githubusercontent.com/3993671/38554598-d9ec7306-3ccb-11e8-9f85-15258087422d.png)

But I'm not sure about color (maybe blue since app's light theme is blue) and form... I only can say that I don't find last three icons suitable.

**Comment by cedenoruel** [comment]
Here are some blue variations. 

![radiodroid_6](https://user-images.githubusercontent.com/38007519/38561210-a1eaf870-3d01-11e8-9f25-1cdceed6ef57.png)

**Comment by segler-alex** [comment]
thank you for your great work! this project really needed an artist.
but there is one point i wanted to make: i really like the theme of the current icon. which means the earth listening to music. it gives me the feel of internationality. of building bridges.
your icons look really cool, and modern. like so many other apps have.
but your icons for me, make radiodroid look like any other music app.
i always thought the earth made it special. and i mean special in the good way, not the crazy way :) maybe i am in the minority here but would it be possible to add any kind of earth abstraction to the icon?
please do not kill me, this is just my hones opinion. i really appreciate that you want to help with the artwork!!!

**Comment by werman** [comment]
@segler-alex You voiced the only issue I had internally with the icons. These icons are cool but they are like many other music apps, which isn't bad in itself but it could be better to have something unique.
@cedenoruel As you can see it's hard for us to tell what design would be good, at best we can give general direction and then tell if we like a result or not. Sorry for pushing you in different directions.

**Comment by avently** [comment]
@cedenoruel it is grenade

**Comment by werman** [comment]
Cool grenade =) Abstract icons look good but I won't throw out colorful ones. At this moment I like 2,3,8 and 8.

**Comment by avently** [comment]
@werman he changed the icons since my comment:) before that it was really grenade like in any image from search.
@cedenoruel 2, 3, 7, 8 are just WOW now.
Awesome. I prefer 2 and 3.

**Comment by cedenoruel** [comment]
Glad you like it! Let me know if you have further suggestions.

**Comment by segler-alex** [comment]
i like 2,3,7,8 also
the world abstraction is really cool. do you think it is possible to add a waves representation. somewhere? or replace the music icon. but maybe it would be cool to have both.
then we could say the 3 things in one icon: worldwide, radio, music
we could also replace the word music, with the word community or open. to tell people about the openness of the project.
sorry, i am going wild here. i would be fine with one of the current ones. but maybe you have an idea, for one of my suggestions :)
thanks for your great work! it is much appreciated!

**Comment by segler-alex** [comment]
i like the ones on the bottom. thanks!

**Comment by avently** [comment]
@cedenoruel take a look at the first icons from this PR. Compare them with the latest icons. See, how cool new icons are? Thanks for that.
I like 2 and 3 from previous image with 8 icons (not the latest) but 5 and 6 from the latest image are good too. 

P.s. the white/blue shape under "music" sign on the circle is soooo cool idea.

**Comment by cedenoruel** [comment]
Happy to hear that. Let me know which version you prefer and I will send vector files & png files.

**Comment by segler-alex** [comment]
i would choose one of the last 2 ones. thank you very much!!!

**Comment by segler-alex** [comment]
do you think it would look better to exchange the music symbol with the waves?

**Comment by segler-alex** [comment]
thanks!!
yes i like them :)
do you think it is a good choice?

**Comment by cedenoruel** [comment]
No problem. I'm just doing this as a hobby during my free time. I'll

**Comment by cedenoruel** [comment]
![color](https://user-images.githubusercontent.com/38007519/38831260-fee1534e-41e8-11e8-920a-160d0e88787d.png)


Yes, I think so. Here are the vectors and png files. Please let me know the icon sizes you need and I will add them. Looking forward to seeing the updated logo and icons in the app and in this repository. 

[Vector and Png Files](https://drive.google.com/drive/folders/1CC5cN2N3068DfuuupQ06dF7ljM0yhCZP?usp=sharing)

**Comment by cedenoruel** [comment]
Please let me know if you need further adjustments.

**Comment by segler-alex** [comment]
i choose the second from the left in the bottom line.
could you export the following sizes?
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)
512 × 512 (Google Play store)
thank you very much!

if it is not too much trouble for you, could you also in addition:
split background and foreground into 2 images,
make the background square, without the round edges.
i found this in the google android documentation and i wanted to also provide android 8.0 new style icons. but i would still need the other ones as fallback.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

thank you very much! your help is greatly appreciated!

**Comment by cedenoruel** [comment]
No problem. I included the required sizes and split background on this [link](https://drive.google.com/open?id=1CC5cN2N3068DfuuupQ06dF7ljM0yhCZP). 
Please let me know if you need more sizes.
Can we put this logo on the README file of this repo? 
![color](https://user-images.githubusercontent.com/38007519/39290477-e1bac174-4959-11e8-9229-836355a74a7c.png)

**Comment by Cormak** [comment]
I just saw the new icon and I love it. @segler-alex you picked just the right icon for this app. It will go a long way in making this app more modern.

**Comment by cedenoruel** [comment]
Thanks for the appreciation @comlak!

**Comment by rodrigoswz** [comment]
@segler-alex Is there a version with an adaptive icon already? Eager for this, RadioDroid is one of the only remaining apps on my device to have all adaptive
