### ISSUE TITLE
Unicode Bug

### ISSUE THREAD

**Issue by ZeroDot1** [segler-alex/RadioDroid#321]
When I listen to a station, ÄÖ and Ü are not displayed correctly for some songs.
Screenshots:
![bildschirmfoto_2018-04-13_17-08-28](https://user-images.githubusercontent.com/28985171/38742602-53c61650-3f3d-11e8-862d-6d44318d0893.png)
![bildschirmfoto_2018-04-13_17-07-53](https://user-images.githubusercontent.com/28985171/38742603-53fb7caa-3f3d-11e8-9acb-8e9ad413d4b1.png)

The app is really great.
I have already added some radio stations and fixed some broken ones.
http://www.radio-browser.info/gui/#/bytag/h%C3%B6rspiel
In the future I will add stations to the database and fix broken ones.

**Comment by Wikinaut** [comment]
This is a duplicate to #241.

**Comment by Wikinaut** [comment]
I suggest, you close this and comment on the #241
