### ISSUE TITLE
[Suggestion] Make Favorite list exportable/importable

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#33]
I wish to transfer my list of favorites to my other devices (export/import). For this, I suggest an export/import function (json? or xml? or text? or OPML format https://de.wikipedia.org/wiki/Outline_Processor_Markup_Language for export/import RSS feeds like in https://github.com/doits/Sparse-RSS/search?utf8=%E2%9C%93&q=opml ).

**Comment by gerroon** [comment]
Hi
I just would like to bump this fr to see if it can be implemented this year.


I personally think that m3u should be considered as an export format.
thanks

**Comment by davidhedlund** [comment]
I cannot load any radio playlists to VLC (nor any other audio player) for Android so a feature to import playlists would indeed be extremely useful.

**Comment by Wikinaut** [comment]
Implemented in 0.66 https://github.com/segler-alex/RadioDroid/commit/d0b7d1979cd23880123b023b77ad812cc4771a1f

**Comment by davidhedlund** [comment]
Good work @segler-alex

**Comment by Vrihub** [comment]
I've noticed that only playlists that were previously created with radiodroid can be loaded.
Nothing happens if I try to load a (correct) .m3u file, e.g. exported from the http://www.radio-browser.info/ website. Can you allow this?

**Comment by Wikinaut** [comment]
@Vrihub see https://github.com/segler-alex/RadioDroid/issues/439 - most likely as a consequence of some missing RADIOBROWSERUUIDs for older entries, and because these UUIDs were introduced recently.
