### ISSUE TITLE
[Suggestion] Improve recorded stream filenames: add station name, compact date

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#34]
The **filename** format of recorded streams could be improved.

I suggest to

* add station name
* compact date to YYYYMMDDHHMM or YYYYMMDDHHMM-HHMM (Start/Stoptime; I use this format on my recordings)

Examples:
* 201605101603-1608_Deutschlandradio_Kultur_(MP3_HQ_stereo_128 kBit/s).mp3
or a shorter versions
* 201605101603-1608_Deutschlandradio_Kultur.mp3 (term in parentheses removed)
or this one
* 201605101603_Deutschlandradio_Kultur.mp3 (stop time omitted)

i have no idea, what you would prefer.

**Comment by Wikinaut** [comment]
And: In the settings there should be a text, where (internal ? SD-Card ? Foldername...) exactly the recording is saved in the device. I had difficulties to find the recording on my device.

**Comment by segler-alex** [comment]
fixed in 0.20
