### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by WulftheNordicRanger** [segler-alex/RadioDroid#340]
Thank you for making this great app. This is in my opinion the best and most feature rich implementation of radio browser. This app is a reminder that internet radio isn't necessarily something like Pandora or Spotify but there are actual radio stations that stream online. The best part about it is there quite a few stations that I've found that are ad free so what's not to love? Anyways, keep up the good work and Rock On!😁😎

**Comment by Wikinaut** [comment]
@WulftheNordicRanger ty, but wait until https://github.com/segler-alex/RadioDroid/issues/309 is implemented...

**Comment by WulftheNordicRanger** [comment]
Sounds awesome! Looking forward to the next update! 😁
