### ISSUE TITLE
Add proxy settings 

### ISSUE THREAD

**Issue by gappleto97** [segler-alex/RadioDroid#341]
It would be nice if I could use this app proxied through Orbot. I cannot do this unless it supports either HTTP or SOCKS proxies. I tried using it through Orbot's VPN mode, and it worked, but I cant use the VPN all the time since I also need it for work.

**Comment by werman** [comment]
I've started to work on it.
Work scope:
- Add option with proxy address/port, selection between HTTP and SOCKS, login/password, connection testing
- Make all requests through okhttp library to have central proxy settings

**Comment by gappleto97** [comment]
Awesome! Cant wait for this to be merged
