### ISSUE TITLE
Move to Gitlab!

### ISSUE THREAD

**Issue by ZeroDot1** [segler-alex/RadioDroid#347]
Would it be possible to leave Github completely and continue the entire development of RadoDroid on Gitlab?
With Microsoft there is no good future, that's why I moved all my important projects to Gitlab.
I'll delete all of my data from Github in the future.

Here is one of my projects as an example: https://gitlab.com/ZeroDot1/CoinBlockerLists

**Comment by ZeroDot1** [comment]
I understand the problems, and I hope Gitlab continues to progress so well.
I didn't know on which infrastructure Gitlab runs, but I think it's not Amazon. 
https://twitter.com/gitlab/status/1004033746897719298

**Comment by jasonyu1996** [comment]
I am just curious about why you believe 'with Microsoft there is no good fortune.'

**Comment by Vistaus** [comment]
Don't enforce your views on others. Maybe @segler-alex doesn't feel uncomfortable with Microsoft on-board.

**Comment by segler-alex** [comment]
i love gitlab, very much so, i even use it a lot at work and teach people about it.
but for now i will stay with github for personal projects. 
and may it be for taking money away from microsoft ;)
