### ISSUE TITLE
Frame the streamed station

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#350]
I often just click on a station and don't remember it's name. It would be nice to frame the streamed station it to indicate that it's active, so I don't waste time and click on it again.

Here's an example how it could look if I've clicked on SomaFM Groove Salad:

![radiodroid-1-mod](https://user-images.githubusercontent.com/6416073/41194470-affd7cfa-6c1b-11e8-9f8b-1f111ae0cb4a.png)

**Comment by werman** [comment]
The name of current playing station is highlighted. Your version seems to be older than the current one so probably there is no such functionality.

**Comment by davidhedlund** [comment]
@werman Thanks.

**Comment by davidhedlund** [comment]
@werman Are play/pause/stop visible in RadioDroid?

**Comment by werman** [comment]
Are paused/stopped stations being highlighted? They are not, probably this should be changed. If I understood your question correctly.

**Comment by davidhedlund** [comment]
@werman I update this issue, please read the top post.

**Comment by davidhedlund** [comment]
https://github.com/segler-alex/RadioDroid/issues/127

**Comment by werman** [comment]
You probably right, I may be better to make it clearer that it's a bottom bar.
