### ISSUE TITLE
Allow user to use Bluetooth Switch Track Back and Forth Buttons

### ISSUE THREAD

**Issue by beccon4** [segler-alex/RadioDroid#358]
Most modern cars have entertainment systems which allow to control the player on a Bluetooth connected device using the switch track keys. It would be nice and contribute to safety and  convenience to be able to switch stations on RadioDroid by pressing the keys in the steering wheel.

**Comment by werman** [comment]
Hi, which stations do you think it should be possible to switch? 
Between station in the list were playing the station from? If station is playing from history - select next from history, if from local station - next/prev local station and so on? I see the point point in switching the stations in favourites/history lists.

By the way, for cars there is android auto which I'm slowly implementing (#315) and I'll probably add your proposal to the feature list or implement it out of order.

**Comment by beccon4** [comment]
I marked my stations as favourites so it would be nice to flip stations at least here without taking the hands off the wheel and - more importantly the eyes off the road. Not all cars have Android Auto - not even all new models - but Bluetooth audio is more widespread.

**Comment by werman** [comment]
Ok, I see, it will be done. Also Android Auto is just an app you can install it on any android phone, some cars seems to have built-in ones.

**Comment by ewired** [comment]
Any updates on this feature? I have a pair of wireless earbuds that have track back/forward functionality which works with VLC, where double tapping e.g. the right-side earpiece's button will skip to the next track. The expected behavior in RadioDroid would be to start playing the next radio station on whatever screen I was last on (e.g. favorites). Play/pause button functionality works as expected.

**Comment by werman** [comment]
Nothing to add at this moment and I cannot promise any exact time. But it probably would be a subset of the features I'm working on.

**Comment by morckx** [comment]
I can provide a quick intermediate solution to support `ACTION_SKIP_TO_NEXT` within the next week, I guess. I have it anyway and we can revert it when @werman is ready.

**Comment by morckx** [comment]
This should be resolved by 369fdbaf39b00a2cd5564a705cebc26463aa6ad1

**Comment by StreakyCobra** [comment]
From 0.74 it is now possible to use the media buttons / headphone controls to change tracks. It is working well for me, but I do not know about the car entertainment systems though.

Thanks @morckx :)

**Comment by morckx** [comment]
Thanks @StreakyCobra for the feedback! The issue can be closed then, I guess.
