### ISSUE TITLE
Mark RadioDroid notifications as non-sensitive

### ISSUE THREAD

**Issue by denilsonsa** [segler-alex/RadioDroid#363]
Problem: If the phone is locked and [configured to hide sensitive data from notifications][1], then I can't see the current song from the lock screen.

Likely solution:
* https://stackoverflow.com/questions/39059027/show-notification-data-when-hide-sensitive-information-is-active
* https://gitlab.com/sebast331-android/agdq-2016/commit/d8a134800694859f26120049ca0bb5def9e9a1b3

[1]: https://support.google.com/android/answer/6111294

**Comment by werman** [comment]
Good suggestion, will be done.
