### ISSUE TITLE
[Bug] save/load playlist screen background doesn't follow dark theme

### ISSUE THREAD

**Issue by spaceof7** [segler-alex/RadioDroid#364]
If I'm using the dark theme and try to save or load the playlist none of the folder names are visible since the text is white, as expected, but the background is white also.

Tanks!

**Comment by werman** [comment]
Tanks!
![image](https://user-images.githubusercontent.com/3993671/43163034-916fbf76-8f95-11e8-831e-3a701ddb9923.png)

**Comment by h3298** [comment]
**Came to open this issue, see its already here.  Posting screenshot anyway =)**

![radiodroid save to playlist](https://user-images.githubusercontent.com/20834957/43712616-c2d95cbc-9944-11e8-92c2-ffcb5c51759b.png)

**Comment by werman** [comment]
My pull request #367 is waiting to be merged. @segler-alex disappeared somewhere.
