### ISSUE TITLE
Feature request: a "Now Playing"-tab

### ISSUE THREAD

**Issue by Spielmops** [segler-alex/RadioDroid#368]
This request came allready up in #352, but the thread went a little aside. Thats the reason, why I created a new request. In #325 there is mentioned a "status page" with similar content?

My reasons for that wish: 
- I want to see the information "Station" and "Title - Artist" displayed big! and not in font-size 6 elsewhere, as if this were unimportant. And: if I use the app on my headunit of my car, I can read nothing.
- now if I want to stop the player and I tap not precise onto the  pause-icon, I get a new station or another tab or a recording. In a "Now Plying-window the play/pause-button can be real big and there would be space enaugh for a "Record"-button.

I tried several radio-streaming-apps, which do not listen to me and don't show ads, this one, Transistor, Servestream, Webradio and some more from Playstore. This best in " displaying" is so far "Simple Radio Player" from Playstore (but a bit complicated in adding a station).

Spielmops

**Comment by werman** [comment]
Yeah #352 indeed derailed. My description of the player window in #352 seems to include your wishes. If not - I'm open to suggestions.

> And: if I use the app on my headunit of my car, I can read nothing.

This part will be handled separately and tracked in #315

**Comment by Vrihub** [comment]
+1 I think this is the most needed feature still missing in the app. Please also see suggestions in #267

**Comment by Vrihub** [comment]
In the meantime, I suggest a quick fix that would improve the current situation: remove from the "miniplayer" the  MB counter and the kbps info, to leave space for the "artist - title" line; currently in most cases only (part of) the artist is displayed, because there is no space for the title.

If you really care (who cares?) about the MB counter, it could be shown only in recording mode; as for the kbps info, I only find it useful in the stations lists, when I want to choose between stations that offer multiple kbps options; when I'm already listening to a station, it's not important to have it constantly displayed

**Comment by werman** [comment]
At the moment I'm putting some work into maximized player screen; mini player will be improved too. I think MB counter is useful when you have metered connection (most mobile networks), bitrate may be indeed not that useful. I'll see what can be done to make enough space for the title.

**Comment by werman** [comment]
I found knowing how much traffic was used when listening to a station useful for myself - to estimate how much will be used in future. However with full screen player it may not be that important to be placed in mini player. I'll think about it.

**Comment by Spielmops** [comment]
Shall this topic derail again?

**Comment by werman** [comment]
@Spielmops It's ok, I've started implementing the player but need to find some time to finish it.

**Comment by SiqingYu** [comment]
It would be a bliss to show the name of the song currently playing on the radio station.
![screenshot_20181012_110456](https://user-images.githubusercontent.com/22290018/46845742-427b2c80-ce0f-11e8-96a7-e29bae07f5c4.png)
Instead of showing just a few words in the beginning.
![screenshot_radiodroid_20181012-110443](https://user-images.githubusercontent.com/22290018/46845823-b3badf80-ce0f-11e8-99ba-754892732ed3.png)

**Comment by duckwork** [comment]
I would also appreciate this feature. I just installed the app and like everything about it except I can't tell what I'm listening to.

**Comment by AdityaMH** [comment]
Maybe if you lack of idea, try to see droidsoud-e

**Comment by segler-alex** [comment]
added in next release

**Comment by Spielmops** [comment]
Fine! Now we have a special tab for the player. Great. 
What I did wish for: 

> I want to see the information "Station" and "Title - Artist" displayed big! and not in font-size 6 elsewhere, as if this were unimportant. And: if I use the app on my headunit of my car, I can read nothing.

So, now we have the player tab and I can see the station "load and clear". But the mor important information "artist and title" are still not readable. Sad.More sad as there's a lot of space on the screen for that ....

Spielmops

**Comment by Wikinaut** [comment]
This was the case in the very first versions of Radiodroid. I never understood, why that page has been dropped.

So: +1 from my side.

**Comment by werman** [comment]
We could swap artist+track with station name, thus allowing both to have bigger font.

We also could try linearize the full screen player, leaving only essential things and for anything else user will have to scroll down.

From another point of view having one ui for all use cases may not be a good idea. It could be easier to create a separate fragment for car/wall radio mode.

And the last point is that we don't have ui/ux contributors so all suggestions with in this direction with examples are welcomed.

**Comment by Spielmops** [comment]
Original from small Phone:

![Radiodroid-01-klein](https://user-images.githubusercontent.com/3194177/75878973-c83fb380-5e1a-11ea-8a01-34d53274439f.png)

and as I want it:


![Radiodroid-Beispiel-klein](https://user-images.githubusercontent.com/3194177/75878984-d097ee80-5e1a-11ea-82ee-1e7593fb6a66.png)
Spielmops
