### ISSUE TITLE
Not good for battery wakelock service

### ISSUE THREAD

**Issue by gerroon** [segler-alex/RadioDroid#37]
Hi

I was checking my battery stats and I see that radiodroid is topping the partial wakelocks. The phoen has been up for 4 hours and MyWakelockTag has been active for 4 hours, it also asked for %96 of the wake locks done in the system. And I was not even using the radio at all and the screen was off the whole time. It is probably in the background. The next app that is close to this kind of usage only uses couple seconds.

I use external player (Vlc), and I generally do not need this app to keep the device awake.

I am using Android 5.1.1

thanks

**Comment by segler-alex** [comment]
i changed to it, so the app gets the wakelock only when playing
thank you, i found another bug with wifilock through your reported issue!

**Comment by segler-alex** [comment]
fixed in 0.14.4
