### ISSUE TITLE
How to add my favorite radio stations that are not on RadioDroid?

### ISSUE THREAD

**Issue by rodrigoswz** [segler-alex/RadioDroid#370]
Is there any tutorial for this? Thanks

**Comment by chipsnblip** [comment]
add a station using this link: [http://www.radio-browser.info/gui/#/add](http://www.radio-browser.info/gui/#/add)

**Comment by rodrigoswz** [comment]
Awesome! Very easy and is added instantly, thank you.

**Comment by Korb** [comment]
> add a station using this link: http://www.radio-browser.info/gui/#/add

This method is no longer available. Also, the procedure for changing database data has been complicated. Now, to do this, you need to fork the repository, create a station data file following the syntax and request a merge. The change is approved manually within a couple of months.
