### ISSUE TITLE
Playing recorded files crashes RadioDroid (NPE?)

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#377]
(I don't know, if this is a regression) In the past, recording and playing these songs worked. Yesterday I noticed, that this does not work any longer.

When I want to play a recorded song, the RadioDroid crashes. It appears to want to start Vanilla Music even when this is not the standard App for playing files.

When navigating manually with the file manager to the recordings folder, playing works.

Can anyone confirm my observation?

Device:

* HUAWEI P8 LITE 2017
* Android 8.0.0

**Comment by werman** [comment]
I'll be able to see what's wrong later this week.

**Comment by werman** [comment]
Indeed it's crashing. Same issue reported in comment for #360

**Comment by werman** [comment]
Ughhh I see what Android did there: https://developer.android.com/reference/android/support/v4/content/FileProvider
Will fix it soon.
