### ISSUE TITLE
Usefulness of the PLAYING tab

### ISSUE THREAD

**Issue by Vrihub** [segler-alex/RadioDroid#384]
Maybe I am missing something? What's the use of the "PLAYING" tab in the "Stations" section?

If it's supposed to list all stations that are currently playing something, that seems pretty useless, and I'd rather remove it. There are already too many tabs, and also the "playing" name is misleading: one would expect to find the currently playing radio station details.

**Comment by segler-alex** [comment]
this tab shows stations that where clicked by other people lately
