### ISSUE TITLE
Radio Droid TV Support

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#386]
I have been watching TV on Radio Droid with an external video player for several months. Since radio browser accepts TV links, why does Radio Droid not support video playback? It should have its own core for video playback and be compatible with Android TV set-top box, so more people will benefit from it.

**Comment by werman** [comment]
Because it's an app for radio, playing video is too far away from its goals. Also there are a lot of tasks which need to be done.

**Comment by zo-shin** [comment]
An app should develop more functions to attract more people and become more influential. Anyway, I'm satisfied with current function.

**Comment by azumukupoe** [comment]
I wish if they wern't listed
We need an option to hide them
