### ISSUE TITLE
Google Playstore fails, because of Android Auto

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#389]
i tried to publish a new version of radiodroid to the google play store. 
but after some time they sent me the following email:

---
Hi Developers at segler.alex,

Thanks for submitting your app for Android Auto. We reviewed your app, RadioDroid 2, with package name net.programmierecke.radiodroid2, and noticed some eligibility issues.

App status: Your app has not been accepted into Android Auto, and the update is not live on Google Play.

Voice commands
Your app does not support all of the required voice commands. The app acknowledge the voice commands, but does not start a new track.You can read more about how to support Voice Actions in the Android Developers Help Center.

---

can somebody fix this? i don't have a car and can not test this.

thanks in advance
alex

**Comment by werman** [comment]
Huh, I'm sorry, I didn't think that it will automatically try to be submitted as Android Auto application (I thought there is some checkbox...). I'll remove offending parts from the manifest tomorrow.

**Comment by segler-alex** [comment]
thank you! for now this helps a lot!
but it would be nice if more people could use android auto, if it is there in the code. are you using it in your car?

**Comment by werman** [comment]
I have added partial Android Auto support but the voice commands are indeed missing, I thought it won't be submitted as Android Auto. 
I don't have a car and I don't use Android Auto, I have tested the code on my device with local Android Auto and it worked (as I understand there are two mods: Auto app and user's app on one phone or they are on different devices).
I committed it half done because it worked and was rotting for quite some time in my repo. I want to return to it after the player window.

**Comment by werman** [comment]
I decided to re-read Android Auto docs and in https://developer.android.com/distribute/best-practices/launch/distribute-auto found:

>  Before you can upload your APK and publish the app for review, the developer account owner must agree to the Android Auto terms from the Pricing and Distribution section of the Play Console. Agreeing to the terms means that you want your app to be made available to Android Auto users through Google Play, and that your app meets the Auto app quality guidelines.
> 
> Your Auto app can be uploaded only after you have agreed to the terms. 

Did you agree to such terms? Can you the agreement?

**Comment by segler-alex** [comment]
yes i agreed to it

**Comment by werman** [comment]
And could you revoke it? Because then the issue not in the manifest.

**Comment by segler-alex** [comment]
no, i had to accept it on upload. he checks the manifest

**Comment by werman** [comment]
Ok, I see, I'll comment it then.

**Comment by segler-alex** [comment]
thank you a lot for all your contributions!
