### ISSUE TITLE
alarm does not always go off

### ISSUE THREAD

**Issue by uzen** [segler-alex/RadioDroid#393]
alarm clock doesn't work if the station is not available or there is no Internet. add an option so that can use the standard alarm ringtone to Wake up.

**Comment by werman** [comment]
Yes, that's not good, alarm should never fail. However I probably won't have time to fix this anytime soon.
It would be cool if anyone else could fix it.

**Comment by uzen** [comment]
ok, try to do 
make it as a separate option because some alarm signal is not needed 
Add NotificationManager which will be called in case of a connection error in AlarmReceiver.

**Comment by werman** [comment]
Nice.
From my perspective alarm should always go off (notification that station playback failed will be a good addition) and option is not necessary. 

Also keep in mind that if connection fails during the alarm it would be good to play default alarm ringtone.

**Comment by werman** [comment]
> not all at once grinning This will cause problems when the station is played in an external player.

Didn't think about this case, we won't know if external player fails so nothing can be done in such case.
Yes it may be done not all at once, it just something that should be kept in mind.
