### ISSUE TITLE
Material Design launcher icon

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#4]
Please, replace the launcher icon with one that complies with Material Design. For this you could use https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by segler-alex** [comment]
i am no graphics guy. even if i use this tool, i will still not have a nice icon :(
can anybody help?

**Comment by PanderMusubi** [comment]
I will have a go at it and let you know.

**Comment by PanderMusubi** [comment]
https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.space.trim=1&foreground.space.pad=0.15&foreground.clipart=res%2Fclipart%2Ficons%2Fav_volume_up.svg&foreColor=fff%2C0&crop=1&backgroundShape=square&backColor=009688%2C100&effects=score

**Comment by segler-alex** [comment]
the new icons should be in version 0.6
