### ISSUE TITLE
Broken: Favorites -> Save to playlist

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#400]
Version: 0.67 (git aa285cd) 2018-10-12 01:23:02

* Go to Favorites
* Click on "Save to playlist"
* Unfortunately, RadioDroid has stopped.

I rebooted my smartphone but RD keeps crashing.

**Comment by davidhedlund** [comment]
> So it is only crashing when saving to playlist?

It doesn't crash when I click on the "Load from playlist" menu item (but I have not actually loaded anything since I cannot save them).

Could you get an error from the logcat through adb? Or what stations are in this list?

This will take to much time for me.

**Comment by werman** [comment]
Ok, I'll see what's wrong with it.

**Comment by davidhedlund** [comment]
> Ok, I'll see what's wrong with it.

What is it then?

**Comment by werman** [comment]
I mean, I'm going to see why saving to playlist is crashing even without additional info.

**Comment by davidhedlund** [comment]
> I mean, I'm going to see why saving to playlist is crashing even without additional info.

Sorry, I misunderstood, thanks.

**Comment by werman** [comment]
Sorry that I wasn't able to check this for some time. From what I currently see it's an issue with folder selection dialog and I don't see anything wrong there, also it's an external library...

So for now I'm not able to fix this. I'll try to give it another shot but it would be after I finish with full screen player.

**Comment by morckx** [comment]
Fixed by #472

**Comment by Wikinaut** [comment]
@davidhedlund I think this issue is solved and can be closed.

**Comment by davidhedlund** [comment]
@morckx Can you please verify that your patch will fix this bug?

**Comment by Wikinaut** [comment]
Perhaps, this https://github.com/segler-alex/RadioDroid/issues/612 is the real issue.

**Comment by davidhedlund** [comment]
I cannot reproduce this issue in RadioDroid 0.79.

**Comment by davidhedlund** [comment]
> Perhaps, this #612 is the real issue.

That's another issue that I also noticed. Thanks for the report.

**Comment by davidhedlund** [comment]
> Fixed by #472

Thanks.
