### ISSUE TITLE
Progulus can not be accessed

### ISSUE THREAD

**Issue by BaumGuard** [segler-alex/RadioDroid#407]
For a longer time, the radio station Progulus can not be accessed. I looked online and there you can play it. It's a radio station that plays progressive rock. Progulus is my favourite radio station. So it'll be nice if that could be fixed.

**Comment by werman** [comment]
Hi,
http://www.radio-browser.info/gui/#/byname/Progulus - the station is listed as "Broken", probably link became obsolete and needs update, however edit functionality is suspended...

**Comment by segler-alex** [comment]
you don't have to rely on edit functionality.
just add the station as a new station with the correct link.
Broken stations will get remove automatically.

**Comment by werman** [comment]
Oh I see

**Comment by BaumGuard** [comment]
Okay, now I added the URL and named the station "progulus" and I didn't change the port. When I search for "progulus", it displays nothing, or how can I listen to the stations which I added myself?
![ScreenshotRadioDroid](https://i.imgur.com/vznlI2y.jpg)

**Comment by werman** [comment]
@BaumGuard There is no way to add station via RadioDroid, you should follow the link segler-alex provided: http://www.radio-browser.info/gui/#/add and add the station there. The option you found in the app is for [MPD](https://en.wikipedia.org/wiki/Music_Player_Daemon)
