### ISSUE TITLE
Please indent source with spaces instead of tabs

### ISSUE THREAD

**Issue by hurzl** [segler-alex/RadioDroid#41]

**Comment by buche** [comment]
I'm preferring tabs

**Comment by segler-alex** [comment]
i don't understand what you mean. please describe it more detailed.

**Comment by hurzl** [comment]
More detail? Indentation in the source code is done with tabs. I thought this was unusual.

**Comment by segler-alex** [comment]
aaaaaaahhhh :) you meant in the source code!!! :)

**Comment by segler-alex** [comment]
i am using android studio so i am using whats the default there

**Comment by hurzl** [comment]
my android studio wants to change it to spaces ;)
