### ISSUE TITLE
Option to add radio to home screen

### ISSUE THREAD

**Issue by orschiro** [segler-alex/RadioDroid#417]
Dear @segler-alex,

What do you think of an option to add a starred radio to the home screen to directly play/pause it?

Happy New Year!

**Comment by Wikinaut** [comment]
Great, I also planned to propose this, it should be possible to add any number of stations to the home screen, so that for each (manually-added-to-home-screen) station a dedicated icon is shown.

**Comment by orschiro** [comment]
@Wikinaut yes, great idea!

**Comment by jo99jo** [comment]
Is this meaningful to certain manufacturers or Android versions?

When I am playing RD2, the icon is in the notification bar area.  If I swipe down on the bar, I can Stop or Pause/Play the source.

**Comment by morckx** [comment]
Resolved by #508 and #510
