### ISSUE TITLE
App Crashes After Wrong Proxy Saved

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#419]
Go to proxy, select HTTP or SOCKS, input anything illegal for a host name as it, like random letters or numbers, save it, then the app crashes and fails to restart. It is required to erase the app data to run it again.

**Comment by werman** [comment]
I believe it was fixed in master

**Comment by zo-shin** [comment]
I tested many times, and it happened.

**Comment by werman** [comment]
Indeed happens

**Comment by zo-shin** [comment]
By the way, does Login mean User name? Why does it accept numbers only?

**Comment by werman** [comment]
> the way, does Login mean User name? Why does it accept numbers only?

Because I blindly copy-pasted it...
