### ISSUE TITLE
Filtering by a multi-word key gives empty result

### ISSUE THREAD

**Issue by scrantr** [segler-alex/RadioDroid#42]
Examples would be "Country" then "United States of America", or
"Tags" then "classical music".

Project is coming along nicely, and much appreciated.  Thanks.

**Comment by Wikinaut** [comment]
I encountered the same problem when looking with entry "radio gold" for "Radio Gold" --> zero results in the Android app.

Web browser http://www.radio-browser.info/gui/ has currently four matching station hits.

**Comment by Wikinaut** [comment]
@segler-alex 

When entering "radio_gold", the search is performed correctly.

So the obvious solution is to replace spaces in the query by an underscore "_".

**Comment by Wikinaut** [comment]
And I would like to have "show results as you type" (when 3 or more characters are entered).

**Comment by Wikinaut** [comment]
appears to be fixed now in https://github.com/segler-alex/RadioDroid/commit/04c1ca91ea4b7bf2aa61a58e4fc68df79585467c

(issue can be closed)

**Comment by scrantr** [comment]
Coonfirmed.  Index look-up appears to work correctly now.  Checked on Android 5.0 and 4.4.
