### ISSUE TITLE
Character encoding issue: on one device, Umlaut incorrectly

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#43]
On my modern Huawei P8 Lite, the title text is not correct, the older Y201 does not have this problem.
See images.

<img src="https://i.imgur.com/Z2ZMk1p.jpg">
- Left: HUAWEI P8 LITE (Android 5.0.1)
- right: HUAWEI Y201 (older device with Android 4.0.3)
  <img src="https://i.imgur.com/aa43EjM.jpg">

My MEDION tablet with Android 4.0.4 shows the Umlauts _correctly_,

**Comment by Wikinaut** [comment]
Info: this problem is still present in 0.14.6

**Comment by segler-alex** [comment]
this is a harder bug to fix than it looks :(
the http standard allows only ASCII characters. (basic ASCII)
JAVA does use UTF8, which some standards say is a good solution. but some german radio stations do use ISO 8859-1
i tried to reimplement the whole http request with low level sockets. which works, but maybe there are radio stations out there, which use UTF-8....
this is bad, there is no real solution which works for all. at least as far as i can see it :(
it would be interesting to know how for example japanese or chinese stations do their encoding.

**Comment by segler-alex** [comment]
i think different phones do behave differently because of different java versions inside. at the moment i use pure java API to get the strings for the radio station name. so that means, some android versions do it one way, some do it the other way.... :(

**Comment by Wikinaut** [comment]
thanks so far for your efforts.

**Comment by pvagner** [comment]
I think UTF-8 should become the default sooner than later. Latest versions of icecast and shoutcast are defaulting to UTF-8 I guess.
Then for known older versions we should fall back to iso-8859-1 if this will persist and no better solution will be found.
It'll be additional extra work trying to identify those older servers inspecting their ICY headers, however hopefully there is a way.
I am just going through the code to have better understanding on how this is currently implemented.
I know people building desktop apps such as VLC or Foobar 2000 are facing similar issues.

**Comment by Wikinaut** [comment]
see #241
