### ISSUE TITLE
shoutcast issue

### ISSUE THREAD

**Issue by Panshangka** [segler-alex/RadioDroid#431]
hello, I looked through your code, but I don't understand what does the shoutcast stuff doing here. Does that mean the shoutcast streaming server framework is used here?

**Comment by segler-alex** [comment]
what do you mean with shoutcast stuff?

**Comment by Panshangka** [comment]
> what do you mean with shoutcast stuff?

In the data package, there is a java class named ShoutcastInfo, I wanna know what the usage of it. Does it mean that you build a Shoutcast server or we can add our own server?

**Comment by werman** [comment]
It is used to parse shoutcast data sent by a station's stream (if it has that data).

**Comment by Panshangka** [comment]
> It is used to parse shoutcast data sent by a station's stream (if it has that data).

thanks, by the way, this software isn't open sourced yet right?
