### ISSUE TITLE
Song info scrolling

### ISSUE THREAD

**Issue by aabm197** [segler-alex/RadioDroid#432]
Can a long song info line be made to scroll so that the complete info is viewable while the phone is in portrait orientation.
Thanks and Regards for a great App.

**Comment by werman** [comment]
Hi, sorry for the late answer. 

You you are talking about station name and current track name - then yes scrolling will be a part of bigger changes I'm working on.

**Comment by aabm197** [comment]
That's splendid. Thank you.
On a side note, is it possible to have this info scrolling also on the lock screen notification? Excuse me if it's a stupid question.

**Comment by werman** [comment]
That's not a stupid question =)
Yes it's possible and I forgot about it, thanks for asking!

**Comment by aabm197** [comment]
That's very nice.
Thank you very much.
