### ISSUE TITLE
Record does not work

### ISSUE THREAD

**Issue by michas0602** [segler-alex/RadioDroid#447]
Record does not work here...tried 0.66 from Google Playstore and 0.69 with Fdroid: 

When a track plays I press the black button, it asks for permission to access storage, the button gets red - and nothing more happens.

I'd post any logfile if you tell me how and  which logfile exactly.

Os is the latest LineageOS on a S5, klte.

**Comment by werman** [comment]
Hi, thanks for the report.

> When a track plays I press the black button, it asks for permission to access storage, the button gets red - and nothing more happens.

And after pressing red button record doesn't start? Nothing changes, no message?

If yes then I would need logs from logcat: https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/

**Comment by EdgeOfForever** [comment]
Unfortunately the tool is not checking, if the folder to write into is existing. This means, you have to create the folder emulated/0/Music/Recordings by your self.

**Comment by michas0602** [comment]
@EdgeOfForever Thats it!

Unfortunately I still haven't had the time to try to get a logfile - but your hint works.
I just created /Music/Recordings in /emulated/0/, and now it works.

Many thanks

**Comment by werman** [comment]
Thanks for finding this out!

**Comment by werman** [comment]
And I now could reproduce it having android 9.

**Comment by michas0602** [comment]
Yes, Music and Recordings were both missing here

**Comment by morckx** [comment]
Simply using `folder.mkdirs` instead of `folder.mkdir` should fix the problem.
