### ISSUE TITLE
MediaStyle Notifications

### ISSUE THREAD

**Issue by rdebeasi** [segler-alex/RadioDroid#449]
Currently, RadioDroid displays an expandable notification with the currently playing station. Users must swipe to expand this notification in order to access playback controls.

It would be awesome if RadioDroid used [MediaStyle notifications](https://developer.android.com/training/notify-user/expanded#media-style) instead! These notifications provide easily accessible playback controls, and they also display album art.

RadioDroid rocks - thank you for making it!!! :smile:

**Comment by werman** [comment]
Hi, thanks for suggestion. It's possible that it would be implemented.

**Comment by morckx** [comment]
I can handle this later today.
