### ISSUE TITLE
Display station name on bluetooth car stereo

### ISSUE THREAD

**Issue by beccon4** [segler-alex/RadioDroid#462]
RadioDroid works fine - I can flip channels using the << and >> keys :-) but unfortunately the station name doesn't appear on the screens. (unlike in VLC)

RadioDroid does display artist name and title on stations which feature this. The Station name (album title??) displays as unknown.

Version RadioDroid: 0.70. ca5ea65 2019-04-15
Car Stereo: Mercedes (year 2017 - official basic stock  entertainment system - everything analogue - can't see software version )

**Comment by morckx** [comment]
I can handle this later. Will you be able to test a pull request? I don't have a bluetooth car stereo...

While we are at it: Can your car stereo also display icons?

**Comment by beccon4** [comment]
> I can handle this later. Will you be able to test a pull request? I don't have a bluetooth car stereo...
Yes, of course though I've never built an Android app
 
> While we are at it: Can your car stereo also display icons?
I don't know. It hasn't displayed anything with VLC. How would I be able to find out?

**Comment by morckx** [comment]
> > While we are at it: Can your car stereo also display icons?
> > I don't know. It hasn't displayed anything with VLC. How would I be able to find out?

VLC tries to show the album art, but only if you have activated something like "show cover art on lock screen".

For RadioDroid there should be a more appropriate option to just set an icon that doesn't get displayed on the lock screen (`MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON`).

**Comment by beccon4** [comment]
> VLC tries to show the album art, but only if you have activated something like "show cover art on lock screen".

Well I don't have this as I made my owm playlist with the station's URLs - I would have to generate one.

**Comment by morckx** [comment]
You can test the pull request with something like:
````shell
git clone git@github.com:segler-alex/RadioDroid.git
cd RadioDroid
git pull origin pull/463/head
./gradlew installPlayDebug
````
Please let me know if it works.

**Comment by beccon4** [comment]
> Please let me know if it works.
Well - the app became flaky and stops working all the time. Often the app doesn't react on << >> keys (nor the jog dial - which is I hope the same bluetooth signal) to flip stations.

We can now display some meta data though:
- for the stations which show title information such as e.g. Apolloradio we see the titles and nothing else. (no station info)
- other stations do show their info from the server - which is not always the station name

See for instance "RCN La Cariñosa / Antena 2"  - as it appears radiobrowser's station list. (image 1) The stream says "This is my server name" :-) 

![IMG_20190510_173347](https://user-images.githubusercontent.com/12436716/57567862-cfa35580-73df-11e9-923a-d97d34610ed4.jpg)

Stations with tags for track titles show them above where not "Unbekannt" and "This is my server name" is. The station name appears to the right of the progress gauge. (and gets cut frequently - but this is not your fault :-)  )

Interestingly - when I go into "show favorites" - it shows me a list of stations with their names from the radio browser but I cannot switch to them - nothing happens. (see 2nd image)

![IMG_20190510_180643](https://user-images.githubusercontent.com/12436716/57567868-e6e24300-73df-11e9-8e9f-318393795762.jpg)

**Comment by morckx** [comment]
Thanks for the detailed report!

> Well - the app became flaky and stops working all the time. 

I think the fix for that is already merged and should be in the next beta. Or have you built the app yourself?

> Often the app doesn't react on << >> keys (nor the jog dial - which is I hope the same bluetooth signal) to flip stations.

That's strange. Did this problem exist before the extended metadata commit? Otherwise, the only possible reason I can imagine is that the icon now also gets transmitted and that it confuses the car stereo or consumes to much bandwidth.

 
> 
> We can now display some meta data though:
> 
> * for the stations which show title information such as e.g. Apolloradio we see the titles and nothing else. (no station info)

That's a bit strange, but I have an idea how to improve the behaviour. (Currently, when there is no artist in the metadata, the title gets transmitted as artist and the track is transmitted as empty string.) 

> * other stations do show their info from the server - which is not always the station name
> 
> See for instance "RCN La Cariñosa / Antena 2" - as it appears radiobrowser's station list. (image 1) The stream says "This is my server name" :-)

We can't change that, I guess. Maybe you can send a bug report to Antenna 2. It seems that all their streams send "This is my server name" as station name. Or do other radio players handle this better? 

> Stations with tags for track titles show them above where now "Unbekannt" and "This is my server name" is. The station name appears to the right of the progress gauge. (and gets cut frequently - but this is not your fault :-) )
> 
> Interestingly - when I go into "show favorites" - it shows me a list of stations with their names from the radio browser but I cannot switch to them - nothing happens. (see 2nd image)
> 

Yes, that´ s another issue. Playing stations by their media id is largely implemented in RadioDroid, but not completely. I don't have the full overview about what's going on there. This could be fixed quite easily but then it would probably in conflict with ongoing android auto implementation.
