### ISSUE TITLE
Version 0.71 crashes(NPE?) when restarting

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#468]
Current version https://github.com/segler-alex/RadioDroid/commit/c87fbb93c39481254bd2cd72f2f245a22acd0790 crashes after restarting. (This is, how it looks like to the users).

How to reproduce:
* Start Radiodroid
* Play a station
* Leave RadioDroid: press "back button" twice
* (notice: the RadioDroid is stll listed in the App list)
* When you now click the RadioDroid icon on your home screen in order to start the app, then it crashes (looks, as if the App is now closed)
* Only the second click on the icon starts the App properly. This appears to be independent of the AutoPlay setting.

**Comment by morckx** [comment]
Thanks for the report! I have the same problem, but thought it was androidx related. I'll fix this later.
