### ISSUE TITLE
changelog file

### ISSUE THREAD

**Issue by alex1702** [segler-alex/RadioDroid#47]
Please make a changelog file and link in fdroid.

**Comment by segler-alex** [comment]
i already tried to send them the link for changelog:
https://github.com/segler-alex/RadioDroid/releases

i did not receive an answer yet, i will try to contact the good people at fdroid again

**Comment by alex1702** [comment]
ok thanks

**Comment by Cwpute** [comment]
The changelog file does not seem to be recognized by Fdroid yet, as its details de not appear directly on the Fdroid page.
See screenshot: 
![Screenshot_20231006-132214](https://github.com/segler-alex/RadioDroid/assets/80604512/389318ed-0ce8-4ca2-a56d-081b7e1d115d)

Should we contact Fdroid again or through some other means ?
