### ISSUE TITLE
Station logo doesn't get updated

### ISSUE THREAD

**Issue by PersianAstroman** [segler-alex/RadioDroid#470]
When the station logo/icon cannot be retrieved or the station has no logo, the logo of the previously played station stays on the notification panel.

**Comment by morckx** [comment]
Do you have a radio station at hand with which we can reproduce and test this?

**Comment by PersianAstroman** [comment]
Of course, in my case "bbc world service" doesn't have any logo within RadioDroid (0.69) app.

Stream URL:
http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-einws
