### ISSUE TITLE
V0.71 Crashes When History Deleted

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#473]
Go to History, click the trash can icon to delete all stations in history, the app crashes.

**Comment by morckx** [comment]
Are you on Android O or P and have something like:
`Not allowed to start service Intent { cmp=net.programmierecke.radiodroid2/.PlayerService }: app is in background` in your logs?

**Comment by morckx** [comment]
I think this can be easily fixed on P, but the target SDK upgrade seems to be a nightmare on O. I've just tested this for the first time, unfortunately, on an API 27 emulator...

**Comment by zo-shin** [comment]
I didn't find those strings in the log. I tested the app on Android 4.4.2 / 5.1 / 6.0.1.

**Comment by morckx** [comment]
Ah OK. The bug is probably already fixed, but not yet in the beta.

**Comment by zo-shin** [comment]
OK, we'll see.
