### ISSUE TITLE
Auto-play Not Work Well with External Player

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#474]
With **Auto-play** & **Enable external player** enabled, after RadioDroid calls the external player to play, try to exit it by pressing exit button or the build-in menu in the player if available, but RadioDroid will keep calling the player again and again unless itself is ended first.
Tested Player: **MX Player**, **VLC** (TV stations only), **Wuffy Player**

**Comment by werman** [comment]
I think these options should be made mutually exclusive

**Comment by zo-shin** [comment]
Did you mean when enable external player is activated, auto-play should be hidden? No other better solution?

**Comment by werman** [comment]
Not hidden, just indicated that it is disabled. I didn't look into it so maybe there is a better solution but we don't know what other player is doing after we called it.

**Comment by zo-shin** [comment]
OK
