### ISSUE TITLE
Radio Meuh preparing stream

### ISSUE THREAD

**Issue by alan-camilo** [segler-alex/RadioDroid#48]
I just add radio meuh to the wiki. It works fine on the website but the app stays with "preparing stream". Radio meuh streams with the aac codec. I run the 0.17 version. Thanks for the help.

**Comment by segler-alex** [comment]
the internal mediaplayer of android which i use does not play all AAC type formats nicely, especially if you don't have most current android version. 
but there is a workarround, just install VLC from the PlayStore or FDroid, then you can share radio stations with VLC from RadioDroid and play all of them.

**Comment by segler-alex** [comment]
you can even set "open external" by default in the settings
