### ISSUE TITLE
Problem with Exoplayer 2.10.0 

### ISSUE THREAD

**Issue by satyres** [segler-alex/RadioDroid#482]
The app works fine with exoplayer 2.9.6 ,but i've tried to update to last version of explayer 2.10.0
and the sound start to glitches and i've this in my logcat.
05-11 16:23:30.877 29921-971/net.programmierecke.radiodroid2 E/ACodec: OMXCodec::onEvent, OMX_ErrorStreamCorrupt
05-11 16:23:30.877 29921-971/net.programmierecke.radiodroid2 W/AHierarchicalStateMachine: Warning message AMessage(what = 'omx ', target = 7) = {
      int32_t type = 0
      int32_t node = 898
      int32_t event = 1
      int32_t data1 = -2147479541
      int32_t data2 = 0
    } unhandled in root state.

please try to update to exoplayer 2.10.0 ! this is really odd.
by the way sound works fine for HLS streams.
Regards

**Comment by satyres** [comment]
Hi again , 
please if you have time please try exoplayer 2.10.0 .
i'm facing a problem when playing any radio except for HLS stream
please how to fix it
Regards

**Comment by werman** [comment]
There is no point in updating exoplayer in RadioDroid so we can ignore these issues for now...

As was asked in https://github.com/google/ExoPlayer/issues/5853 - does it happen in their demo app?

Since there are a lot of things with much higher priority I won't look into it for now, sorry. If anyone wants - they are welcomed.

**Comment by satyres** [comment]
Thanks so much for your time , i thought it's important to have the last version of exoplayer.
By the way in the demo app it's working fine . it's just in your app.
this is quite odd. i hope we can find a solution because i really like your app.
Best regards

**Comment by morckx** [comment]
Upgrading to ExoPlayer 2.10 seems to be quite a step, as it supports icy metadata support by itself and also seems to require a minimum API upgrade to 16.

Is there anything in 2.10 that makes it worth it?

**Comment by satyres** [comment]
@morckx ,For now the last version of exoplayer 2.9.6 is working quite good.
but i'm thinking of the futur , maybe it will be important to move the the new version.
for now 2.10.0 has problem when playing (the sound glitches )
but for HLS it's working fine, so we stick with the 2.9.6 version.
 i hope we can find a way to fix it.
Regards

**Comment by Pentaphon** [comment]
@satyres has 2.10.4 fixed your issues?

**Comment by satyres** [comment]
Hi sorry for late reply i'll check it out
regards

**Comment by satyres** [comment]
The problem is only when i use RadioDroid . 
it was working fine with the 2.9.6 and from the 2.10.x 
the sound glitches ! this quite weird !

**Comment by Pentaphon** [comment]
You probably shouldn't try to update Exoplayer yourself. 2.9.6 works because its been tested.

**Comment by satyres** [comment]
i hope they will be able to fix to get the last version of Exoplayer
please if you don't mind (and if you have time) 
give it a try [RadioDroid](https://github.com/segler-alex/RadioDroid)
don't forget to try the last version of Exoplayer
Regards
