### ISSUE TITLE
Lists for tag, country, language et cetera

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#5]
Please add lists after choosing a tag, country, language or any other metadata you have available. If the lists are too long to choose from, don't offer that list of choices or offer only the most used (e.g. in case of the tags).

**Comment by Hariama** [comment]
I second this, a list per country would be quite useful, as right now finding any Belgian radio-channels seems to be a rare oddity.

**Comment by PanderMusubi** [comment]
Tes, the lack of this option prevents me to access the channels I added and prefer to listen too. Major step forwards when, albeit a limited version of, filtering certain tags etc becomes available.

**Comment by segler-alex** [comment]
i added tags, countries and languages

**Comment by PanderMusubi** [comment]
Thanks, the app just made a major forwards.
