### ISSUE TITLE
[Suggestion] Add an option to use phone speaker as alarm audio output

### ISSUE THREAD

**Issue by skygate2012** [segler-alex/RadioDroid#502]
Before sleep I would listen to some sleep induction audio with earphones. In the morning my earphones would fall out but the alarm clock of Radiodroid only outputs audio to earphones when it's plugged-in, so I wouldn't hear it. Therefore, can you add an option to make it work like the regular alarm clock app, which outputs both to earphone and speaker?

**Comment by morckx** [comment]
What RadioDroid and Andoid versions do you use?

On 0.73 and P this works as it should for me, the alarm using the alarm volume and playing though earphones and speaker.

**Comment by skygate2012** [comment]
@morckx I'm on 0.72 and KK and not using external player.
Just tried again and I realized it was because of my low alarm volume, when alarm is started the volume keys would only affect the media volume, so I did not notice, don't know if this is a bug or not.
