### ISSUE TITLE
No UI response when pressing the delete button in alarm clock

### ISSUE THREAD

**Issue by Surras** [segler-alex/RadioDroid#503]
When I press the delete button of an alarm entry, the row is correctly. I expect an dialog wich ask me "do I really want delete? yes, delete. no." and if I press yes, the entry removes from list.

I figure out, that the entry is already deleted in data structure, because if I leave the view and comes back, the entry is gone. I think its just an UI bug, and the RecyclerView needs to notify of the delete.

Device: Sony xperia XZ1 Compact, Android 9
RadioDroid Version: 0.72 (from F-Droid)

**Comment by morckx** [comment]
Thanks for the report! I can reproduce this and it should indeed be easy to fix. Maybe we can replace the delete button also with swipe to delete, like in the favorites view.

**Comment by Surras** [comment]
swipe to delete sounds like a modern way. All in all it's maybe better to arrange the three Buttons ("on/off", "delete", "repeat at") horizontal as a second row. Actually its vertical on the right side, wich cause to wrong user behavior, like reported in #191 
In horizontal, you have more space for the buttons I though.
