### ISSUE TITLE
Redesign Settings Layout

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#507]
There are more and more options added to settings over time, making it a little bit lengthy. It may look snappy to show them on the sub-menus, only keeping the categories on the main menu.

**Comment by Wikinaut** [comment]
Hmmm, I found the "one-stop" entry not so bad. In other words, I don't see a reason to change the current layout. More important would is, in my view, the implementation of a search with suggestions #309.

**Comment by werman** [comment]
I also think that options doesn't need redesign however I think we need some kind of "welcome screen" with several core options, like: theme, warn when not on wifi, download icons/art - something like this.

**Comment by zo-shin** [comment]
OK. Anyway, it's the app with the most options on one screen I have.
Maybe search suggestion can be given a consideration.

**Comment by morckx** [comment]
I think we'll indeed this in the medium run with more options being added. I already  find myself not adding any new options for fear of the size of preferences screen.

**Comment by zo-shin** [comment]
There will be another three options in the pre-recording pull request, which will make the screen more lengthy.

**Comment by morckx** [comment]
I've made a first attempt:

![Screenshot_1559505591](https://user-images.githubusercontent.com/1309388/58766708-ffc6ba00-8581-11e9-9a7f-4b2ee0c6f606.png)

![Screenshot_1559506015](https://user-images.githubusercontent.com/1309388/58766778-e2462000-8582-11e9-9234-dfab36f65e78.png)

It is indeed already quite a long list just for the categories and there is in addition a startup category (plane taking off icon) needed.

What do you think?

TODOs:

- make preference search open nested screens
- make correct toolbar titles more robust
- (make dependencies across screens work will be clumsy)

**Comment by zo-shin** [comment]
The changes are good, and a pull request can be made.
I also think the “audio player” option in alarm needs improvements. Maybe there’s a better way to show it.
See #498

**Comment by werman** [comment]
@morckx Looks good.

**Comment by morckx** [comment]
> @morckx Looks good.

Thanks, but some details are still giving me a headache.

I currently have two versions; One using `setPreferenceScreen` to switch between the two preference levels and one using the fragment manager. Both are not working with the [SearchPreference](https://github.com/ByteHamster/SearchPreference) library and both have different little problems with either the toolbar back button or with the standard back button in connection with RadioDroids other fragments. My plan is to have a closer look at [k9mail](https://github.com/k9mail/k-9), that also uses nested preference screens and the SearchPreference library, use their solution, if possible, and solve remaining issues with RadioDroid's fragment navigation, afterwards. If  SearchPreference remains a problem, we could probably do without it for the time being.
