### ISSUE TITLE
app crash when changing station (when already a station is playing)

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#51]
<pre>
android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
</pre>

06-09 20:48:17.785 D/AndroidRuntime( 6028): Shutting down VM
06-09 20:48:17.794 E/AndroidRuntime( 6028): FATAL EXCEPTION: main
06-09 20:48:17.794 E/AndroidRuntime( 6028): Process: net.programmierecke.radiodroid2, PID: 6028
06-09 20:48:17.794 E/AndroidRuntime( 6028): android.os.NetworkOnMainThreadException
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:249)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okio.Okio$2.read(Okio.java:113)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:512)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:495)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okhttp.internal.Util.skipAll(Util.java:227)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:216)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:540)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:198)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:181)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.StreamProxy.stop(StreamProxy.java:303)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.PlayerService.PlayUrl(PlayerService.java:338)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.PlayerService$1.Play(PlayerService.java:70)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.PlayerServiceUtil.play(PlayerServiceUtil.java:65)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.Utils$1.onPostExecute(Utils.java:188)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at net.programmierecke.radiodroid2.Utils$1.onPostExecute(Utils.java:172)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.os.Looper.loop(Looper.java:135)
06-09 20:48:17.794 E/AndroidRuntime( 6028): 	at android.app.ActivityThread.main(ActivityThread.java:5310)

**Comment by segler-alex** [comment]
fixed in 0.19
