### ISSUE TITLE
[0.74] Does not work on Android 6.0 and Android 8.0: "cannot connect to Radiostation" (certain stations)

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#516]
After updating to 0.74, I cannot connect to certain Radio Stations on older smartphones (Huawei Y6, Huawei P8 Light 2017) any more, other stations work.

* Adnroid 6.0
* Android 8.0

Android 9.0.1 works.

**Comment by Wikinaut** [comment]
Update: I found, that after re-searching the stations it works. So probably, for some reasons, olders stream Url did work in pre-074 versions, but no longer in 074+ version.

**Comment by morckx** [comment]
> Update: I found, that after re-searching the stations and using alternate streams (Examples were the Deutschlandfunk Kultur streams), these appear to work. So probably, for some reasons, olders stream Url did work in pre-074 versions, but no longer in 074+ version.

Due to d0030c655a7ffef45055ef503ee9f325b773f561 ?
Is there a way RadioDroid can help to migrate old playlists?

**Comment by segler-alex** [comment]
i tried it locally with my device to upgrade from the previous version. this worked. i think this only fails if your local lists do not have uuid for some stations. they have to be filled.

**Comment by segler-alex** [comment]
basically search each station by id that does not have uuid and then set it locally.

**Comment by Wikinaut** [comment]
Is there a way to see the station details on the Android device? The very old RadioDroid software had such a station detail page.

**Comment by morckx** [comment]
> Is there a way to see the station details on the Android device? The very old RadioDroid software had such a station detail page.

I just closed my corresponding PR https://github.com/segler-alex/RadioDroid/pull/515 yesterday, because @werman's full player, which provides more details, seems almost ready, but you can just pull it in the mean time.
