### ISSUE TITLE
Long titles are not shown fully after expanding

### ISSUE THREAD

**Issue by PersianAstroman** [segler-alex/RadioDroid#521]
While listening to radio '100% Souvenirs' I noticed that when the title doesn't fit in a line, the app uses three-dots (...) and sometimes two-dots (..). Naturally I expected to see the full title after expanding the notification panel. But nothing happened.
Moreover, for many titles that fit in a line, it still uses three-dots:
![IMG_20190519_212009](https://user-images.githubusercontent.com/29872642/58387520-e8894900-8024-11e9-89ec-bc0a0b5ebbbf.jpg)
![Screenshot_20190523-112245](https://user-images.githubusercontent.com/29872642/58387521-e921df80-8024-11e9-9d5d-5af2ca0248a1.jpg)
![Screenshot_20190523-153845](https://user-images.githubusercontent.com/29872642/58387522-e921df80-8024-11e9-9a6c-8c9dfe862d1c.jpg)

Radio stream url:
http://100radio-souvenirs.ice.infomaniak.ch/100radio-souvenirs-128.mp3

**Comment by morckx** [comment]
Thanks for the report and the detailed information! 

The actual rendering of the notifications is completely done by a Google/Android standard library and the OS, so that RadioDroid can't do much about it. 

Since a couple of betas, however, we use a new notification style looking roughly like this
:
<img width="320" src="https://user-images.githubusercontent.com/1309388/58419289-78151300-808a-11e9-8f41-38c5f4ea7c90.png"/>

Yo can try the betas by registering as beta user in the Play Store.

**Comment by PersianAstroman** [comment]
Aha, but apps like Telegram, WhatsApp, or Instagram use such short/full view of content in notification panel. So I thought the android library must have a functionality that lets developers implement such a behaviour.
And I've tried installing the beta version of the app (0.74) using Google Play, but the app seems to crash right after being opened 😐 so i uninstalled it and installed it again through FDroid which turned out to be version 0.73 which works fine.

**Comment by morckx** [comment]
RadioDroid uses  media style notifications and bahaves like comparable apps such as Google Play, VLC, YouTube , etc. I can't see any difference there:

https://youtu.be/-QDg-DquhiE

Thanks also for the 0.74 bug report. I think we know the reason, but could you provide a logcat?

**Comment by PersianAstroman** [comment]
Wow, that sounds awful. So I think I should put this issue for developers of this particular media style notification 😅
You're welcome. I'm afraid I don't know much about android development, but I try to provide that logcat thing ASAP 😉
