### ISSUE TITLE
Crash when clicking on station details

### ISSUE THREAD

**Issue by Vrihub** [segler-alex/RadioDroid#525]
The app crashes ("Unfortunately radiodroid has stopped") when clicking on the "v" icon at the right of the radio station item (to view station details IIRC).

Version 0.74 (from f-droid repo) on android 4.2.2

**Comment by morckx** [comment]
Sorry, and thanks for the report! The fix (#522) is already merged and should be in the next beta.

**Comment by morckx** [comment]
Fixed via #522. Can be closed, I guess.
