### ISSUE TITLE
App Crashes with Off-Wi-Fi Warning On

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#528]
When in mobile data with off-Wi-Fi warning on, click the station shortcut icon on the main screen, then the app crashes.

**Comment by morckx** [comment]
I'm not able to reproduce this. Please send a logcat, if you can.

**Comment by zo-shin** [comment]
It happened on an Android 8.1 device. I'll see if it still happens.

**Comment by zo-shin** [comment]
**Here’s part of the log, with the full one if required.**
E/AndroidRuntime( 5909): Process: net.programmierecke.radiodroid2, PID: 5909
E/AndroidRuntime( 5909): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 5909): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 5909): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 5909): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
E/AndroidRuntime( 6092): Process: net.programmierecke.radiodroid2, PID: 6092
E/AndroidRuntime( 6092): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 6092): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 6092): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 6092): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
E/AndroidRuntime( 6161): Process: net.programmierecke.radiodroid2, PID: 6161
E/AndroidRuntime( 6161): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 6161): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 6161): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 6161): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
E/AndroidRuntime( 6691): Process: net.programmierecke.radiodroid2, PID: 6691
E/AndroidRuntime( 6691): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 6691): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 6691): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 6691): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
E/AndroidRuntime( 6810): Process: net.programmierecke.radiodroid2, PID: 6810
E/AndroidRuntime( 6810): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 6810): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 6810): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 6810): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
I/chatty  ( 8924): uid=10005(net.programmierecke.radiodroid2) identical 43 lines
D/SurfaceFlinger(  746): duplicate layer name: changing net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain to net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain#1
I/chatty  ( 8924): uid=10005(net.programmierecke.radiodroid2) identical 43 lines
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10025, mForegroundPid=2504, mLastForegroundPackageName='net.programmierecke.radiodroid2', mLastForegroundUid=10005, mLastForegroundPid=8924, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
E/InstallShortcutReceiver( 2504): receive from net.programmierecke.radiodroid2 install shortcut for #Intent;action=com.android.launcher.action.INSTALL_SHORTCUT;S.android.intent.extra.shortcut.NAME=Beijing%20Classical%20Music%20Radio;end
D/Launcher.Model( 2504): Insert item net.programmierecke.radiodroid2 to database (2, 0) of screen 5
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='net.programmierecke.radiodroid2', mForegroundUid=10005, mForegroundPid=8924, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10025, mLastForegroundPid=2504, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10025, mForegroundPid=2504, mLastForegroundPackageName='net.programmierecke.radiodroid2', mLastForegroundUid=10005, mLastForegroundPid=8924, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
D/Launcher.AnalyticalDataCollector( 2504): back to home, packageName=net.programmierecke.radiodroid2
E/SurfaceFlinger(  746): Failed to find layer (net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain#0) in layer parent (no-parent).
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='net.programmierecke.radiodroid2', mForegroundUid=10005, mForegroundPid=8924, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10025, mLastForegroundPid=2504, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
E/AndroidRuntime( 8924): Process: net.programmierecke.radiodroid2, PID: 8924
E/AndroidRuntime( 8924): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime( 8924): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime( 8924): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime( 8924): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
D/Launcher.AnalyticalDataCollector( 2504): back to home, packageName=net.programmierecke.radiodroid2
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10025, mForegroundPid=2504, mLastForegroundPackageName='net.programmierecke.radiodroid2', mLastForegroundUid=10005, mLastForegroundPid=8924, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
D/ActivityTrigger( 1936): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{3803a1c net.programmierecke.radiodroid2}
E/ActivityTrigger( 1936): activityStartTrigger: not whiteListednet.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain/87
D/ActivityTrigger( 1936): activityResumeTrigger: The activity in ApplicationInfo{3803a1c net.programmierecke.radiodroid2} is now in focus and seems to be in full-screen mode
E/ActivityTrigger( 1936): activityResumeTrigger: not whiteListednet.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain/87
D/ActivityTrigger( 1936): activityResumeTrigger: The activity in ApplicationInfo{3803a1c net.programmierecke.radiodroid2} is now in focus and seems to be in full-screen mode
E/ActivityTrigger( 1936): activityResumeTrigger: not whiteListednet.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain/87
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='net.programmierecke.radiodroid2', mForegroundUid=10005, mForegroundPid=10013, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10025, mLastForegroundPid=2504, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
D/AccessibilityManager(10013): AccessibilityManager status: mPackageName = net.programmierecke.radiodroid2, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/zygote64(10013): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/base.apk"],nativeLibraryDirectories=[/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/lib/arm64, /system/lib64, /vendor/lib64]]
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/zygote64(10013): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/base.apk"],nativeLibraryDirectories=[/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/lib/arm64, /system/lib64, /vendor/lib64]]
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/zygote64(10013): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/base.apk"],nativeLibraryDirectories=[/data/app/net.programmierecke.radiodroid2-FzIYD7-h_0xX2_pqwXQe9w==/lib/arm64, /system/lib64, /vendor/lib64]]
I/zygote64(10013):   at void net.programmierecke.radiodroid2.ActivityMain.onCreate(android.os.Bundle) (ActivityMain.java:138)
I/ActivityManager( 1936): Displayed net.programmierecke.radiodroid2/.ActivityMain: +645ms
E/AndroidRuntime(10013): Process: net.programmierecke.radiodroid2, PID: 10013
E/AndroidRuntime(10013): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:258)
E/AndroidRuntime(10013): 	at net.programmierecke.radiodroid2.Utils.Play(Utils.java:233)
E/AndroidRuntime(10013): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:321)
E/AndroidRuntime(10013): 	at net.programmierecke.radiodroid2.ActivityMain$2.onPostExecute(ActivityMain.java:311)
D/Launcher.AnalyticalDataCollector( 2504): back to home, packageName=net.programmierecke.radiodroid2
D/PowerKeeper( 3517): PerfEngineController:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10025, mForegroundPid=2504, mLastForegroundPackageName='net.programmierecke.radiodroid2', mLastForegroundUid=10005, mLastForegroundPid=10013, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
D/ProcessObserver( 3517): onScreenAppChanged, PreTaskUid: 10005, PreTaskPackageName: net.programmierecke.radiodroid2
D/GameBoosterService( 3558): onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10025, mForegroundPid=2504, mLastForegroundPackageName='net.programmierecke.radiodroid2', mLastForegroundUid=10005, mLastForegroundPid=10013, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
D/PowerKeeper.Event( 3517): notifyActiveKilled processName: net.programmierecke.radiodroid2, pid:10013, reason:crash
