### ISSUE TITLE
Would it possible to change the icon to the old one in the settings?

### ISSUE THREAD

**Issue by KingArhturII** [segler-alex/RadioDroid#53]
I feel that the new logo doesn't have the elegant simplicity of the old one, and it doesn't work as well on dark backgrounds.

**Comment by Wikinaut** [comment]
I also prefer the previous icon.

**Comment by segler-alex** [comment]
i think the previous icon was very very blend. it did not say anything about the app.
the new one tells people 2 things: listening to something, and from all over the world.
i changed the background in the release 0.20, so it is better visible
but i am no graphics guy, if there is someone out there who can design an original icon, i would happily use it

**Comment by Cormak** [comment]
@Wikinaut @KingArhturII  @segler-alex If we are going to keep calling this app Radiodroid, why not just make a green robot head with a radio dial on it? As long as it has a Material Design look to it, that should be enough.
