### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [segler-alex/RadioDroid#535]
hello, the interface is very nice, however, the favorite button is yellow (on the radio icon) is very ugly, it is too big 

a white and much smaller (proportional) button would be better / setting to hide it 

same for trend icon

thank

**Comment by Wikinaut** [comment]
If you find that ugly, please simply supply a different design which we can discuss here. I actually created something which has contrast to dark and light stations icons.

**Comment by segler-alex** [comment]
closing this, please understand, that we are actually doing this in our free time without pay. we do not have artists helping at the moment and we will not pay anyone to do it. but everyone is welcome to help with building a better design.
