### ISSUE TITLE
Desktop Icons Not Displayed Correctly

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#536]
Some station desktop icons are not displayed correctly because of their sizes. See pictures below.
- Icons displayed correctly in favorites
![1](https://user-images.githubusercontent.com/38669548/59767815-b0002680-92d5-11e9-8b9b-4fb284c84516.JPG)
- Icons not displayed correctly on desktop
![2](https://user-images.githubusercontent.com/38669548/59767828-b68e9e00-92d5-11e9-823b-e0258034bc67.JPG)

**Comment by morckx** [comment]
If the icons have a size ratio that differs greatly from 1:1, it depends entirely on the padding whether they are displayed more or less correctly on  desktop than in the favorites. I'm afraid it's practically impossible to distinguish content from padding.

Ideally, the original logo icons should have a ratio of 1:1. If it's important for you, you can just add new instances of your favorite stations to radio-browser.info with proper size ratio icons.

**Comment by zo-shin** [comment]
OK.
