### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by 11fen** [segler-alex/RadioDroid#541]
http://www.radio-browser.info/gui/#!/byname/1111 Can play, but can't play in app

**Comment by morckx** [comment]
Thanks for the report!

Apparently, 1111 doesn't report proper content type, but we can probably guess it based on the file name extension.

**Comment by 11fen** [comment]
Thank you, how can I solve it?
I am currently using vlc to play https://rfahls-i.akamaihd.net/hls/live/226232/RFALive_1/index.m3u8 but it is very inconvenient

**Comment by zo-shin** [comment]
Go to settings, make sure enable external player is checked.

**Comment by morckx** [comment]
I guess the [fix](https://github.com/segler-alex/RadioDroid/pull/543) will be in the next beta so that then you'll be able to use the internal player again.
