### ISSUE TITLE
beta to production?

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#549]
hi, do you think that the current version in the beta channel can be pushed to the main channel on google play?

**Comment by werman** [comment]
Hi, from what I see there is one critical issue left #529. Without migrating history/favourite lists to the uuids we would have some angry users.

**Comment by morckx** [comment]
I can draft something.

**Comment by morckx** [comment]
> hi, do you think that the current version in the beta channel can be pushed to the main channel on google play?

With #552 id->uuid upgrading seems to work. To stay on the safe side, we should probably have a new beta that includes #552, first.

**Comment by segler-alex** [comment]
i just made a release, thank you for your help with uuids!

**Comment by segler-alex** [comment]
i pushed it to beta

**Comment by morckx** [comment]
> i pushed it to beta

Great, thank you!

**Comment by morckx** [comment]
Do you think #475 is also critical for a production release?

**Comment by morckx** [comment]
I'll better fix this, probably later today. It will then only resume playing if no-wifi warning is disabled or wifi is available.

**Comment by mailinglists35** [comment]
@segler-alex hi, I see lots of unanswered ideas in https://github.com/segler-alex/radiobrowser-api/issues/39, after your last reply on Apr 25, 2018; would you mind stepping in from time to time?

**Comment by segler-alex** [comment]
pushed 0.78 to beta

**Comment by segler-alex** [comment]
do you think that there are still problems that prohibit push to production?

**Comment by morckx** [comment]
I think it's ready for production now.
