### ISSUE TITLE
 Make Favorite list default start Tab

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#56]
Pls. allow users to set the Favorite as default tab when starting the app. Or, as an alternative, start RadioDroid with the Favorite tab, if there is any Favorite set.

**Comment by zoff99** [comment]
+1

**Comment by Neudrino** [comment]
I would even extend the suggestion of @Wikinaut so far as to make the menu items above the separation line (i.e. "Favourites", "History" and "Alarm clock") all into tabs.

In my eyes this would make the app more easy to use, as you would be able to chose your desired function by swipe. I find it cumbersome to open the menu to access these functions, which one uses probably more often than the other tabs (assuming that nearly everybody has favourite stations).

You could for example put them to the left of the existing tabs, such that you start the application with "favourites", to the right there are the "old tabs" and to the left there are the "new tabs" (history & alarm). If you want to further make them distinguishable, you might want to have the ones on the left in a different shade of blue or with a bold font, etc.

**Comment by corentin38** [comment]
After a very quick look at it, it seems more difficult to add yet another tab to radios fragment than to make an option to start favourite stations fragment if the user selected so in the preferences.

See pull request: #70

**Comment by hurzl** [comment]
It would be so much more convenient if the favourites would be a tab. What can be difficult about it? It*s the same type of list as the other ones.

**Comment by Wikinaut** [comment]
I reported this issue, it is solved in the recent version which allows to start RadioDroid with the "Starred stations at start"
