### ISSUE TITLE
API change: use countrycode instead of deprecated country name

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#560]
i added a new field to the database: countrycode
it is the dependable successor of the field country. with this in place, the mapping in the app to get countrycode from the name is not needed any more (this is needed for local station list, we only get the country code from the device)

the good things:
* the countrycode is standardized, no double/tripple countries anymore in the database
* it is not possible to add non-existing countries to the database anymore.

the bad things:
* everyone is using country at the moment
* i had to manually add country code information to every station in the database..

what do you think about changing radiodroid that it uses the field countrycode instead of country?

**Comment by zo-shin** [comment]
As I said, whatever the change is, the country list should be simple, snappy.
See https://github.com/segler-alex/radiobrowser/issues/163

**Comment by werman** [comment]
Should be easy, if anyone wants to do it - they are welcomed, I won't be able to look at it for some time. Also I think we should add some tags to the issues like priorities, "bug", "feature"; for things like this not to be lost.

**Comment by zo-shin** [comment]
I think it's worthwhile to spend some time making a new country code system instead of using someone else's.
