### ISSUE TITLE
ChromeCast capability

### ISSUE THREAD

**Issue by zorglube** [segler-alex/RadioDroid#562]
Is their any way to add an ChromeCast streaming capability to radio droid ?

**Comment by morckx** [comment]
> Is their any way to add an ChromeCast streaming capability to radio droid ?

Do you mean streaming radio with RadioDroid to Chromecast? That already works.

**Comment by morckx** [comment]
![Screenshot_20190908-215028_RadioDroid](https://user-images.githubusercontent.com/1309388/64494146-677b5800-d289-11e9-98f8-e362c3134734.png)

**Comment by zorglube** [comment]
I don't have the cast icon on the app... Weird! Does it need any setup?

**Comment by morckx** [comment]
> I don't have the cast icon on the app... Weird! 

Indeed.

> Does it need any setup? 

No, I don't think so.

**Comment by zorglube** [comment]
Damn... I'll make some research and maybe write you.

**Comment by segler-alex** [comment]
it only works in the version from the playstore. NOT in the version from f-droid.

**Comment by zorglube** [comment]
Thank you!

Le dim. 8 sept. 2019 à 23:29, segler-alex <notifications@github.com> a
écrit :
