### ISSUE TITLE
Feature request: sort favorites manually

### ISSUE THREAD

**Issue by andres99** [segler-alex/RadioDroid#566]
Would be nice to have. I use Radio Droid in car and cannot concentrate on browsing while I drive, so that it I would like to rearrange my favourites before the drive according to my mood (to have the moment’s preferred stations on top).

**Comment by Wikinaut** [comment]
You can already since a long time rearrange your favourites: simply drag and drop a station in the list and move where you want to have it.

**Comment by andres99** [comment]
Sorry, I did not realise it at once.
