### ISSUE TITLE
Feature request: a settings option to disable recording

### ISSUE THREAD

**Issue by andres99** [segler-alex/RadioDroid#568]
Sometimes I tap the wrong spot and the app begins recording when I don’t want it to (I just want to play or stop a station). It would be nice to have, in Settings, to disable Recording fully. And also it seems that under Recordings I cannot easily delete the accidental recordings.

**Comment by werman** [comment]
I don't think it would be a problem with https://github.com/segler-alex/RadioDroid/pull/495

**Comment by andres99** [comment]
Indeed, perhaps not (judging by the way it looks now). It will be, rather, a point of user convenience. There is a record button but it seems to be separate enough to avoid accidental tapping. Maybe only when I am driving (and I want to switch to the previous station) and cannot tap stuff precisely, but I do not know yet if it is a realistic concern.
