### ISSUE TITLE
About: version? 

### ISSUE THREAD

**Issue by ChiefMikeK** [segler-alex/RadioDroid#57]
The tab should list the version/date and maybe a short change-log(since last very.) √

**Comment by Wikinaut** [comment]
Implemented in https://github.com/segler-alex/RadioDroid/pull/180

**Comment by Wikinaut** [comment]
@segler-alex Issue can be closed.

**Comment by h3298** [comment]
Still not seeing change logs... can someone post a graphic, or a URL for the change log ?
