### ISSUE TITLE
[bug] cannot delete alarm & alarm refresh issue after deletion

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#570]
- I have searched the history issue list, and have not found similar issues. An related issue #191 was reported long time ago, but was already closed by #503.

- The bug was found in the latest release version 0.79 from Google Play, and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device

- Reproduction steps:  

1. Refreshly install the app

2. select any station under the ``Local`` tag, press the ``Alarm`` menu option at the bottom, click the ``Alarm Add`` button at the top, click ``OK``. At this time an alarm was created. 

3. Now, **long press** the ``Alarm Add`` button at the top, and then click the ``delete`` button of the alarm, the alarm cannot be deleted.  I find **long press** is not always necessary to reproduce this issue but it seems help reproduce this issue more deterministically. I can also successfully reproduce this issue without the **long press** action. In either situation, if we continue to create more alarms, all these alarms cannot be deleted.

4. If I click the ``station`` menu option, and return back to the ``Alarm`` menu option. The alarm was disappeared (deleted). 

- Reproducing video

On an Android 6.0 emulator:

  
![20191011_215935](https://user-images.githubusercontent.com/3156978/66683069-e132a700-ec76-11e9-8d4b-a86adce3c360.gif)

On an Google Pixel 3 device:

https://youtu.be/XTMMLlcs7zA

**Comment by junior291492659** [comment]
Hello, same issue here. I caught this bug on a real device Redmi Note 4X, Android 6.0 as well as an Android emulator 6.0 device.

Thanks for your wonderful app and it would be really appreciated to get your concern on this.

**Comment by werman** [comment]
@tingsu Thank you for the detailed report! I'll take a look at the issue soon.

**Comment by tingsu** [comment]
Thanks, @werman! I guess it may be related to the view update.

**Comment by tingsu** [comment]
I also tested this scenario on the latest code in the repo (the compiled apk named ``RadioDroid-free-debug-DEV-0.79-da50202.apk``), this issue still exists.

**Comment by tingsu** [comment]
Hi @werman , thanks for your previous reply.

I checked this issue on the latest code version (commit id: a214abe). I feel the issue may be just caused by the failure to refresh/reload the view.   Because, if I switch to another tab and come back, the alarm was correctly deleted.

Any plan to fix this issue? Just let me know if you need more help from my side. Thanks!

![RadioDroid-issue570-latest-commit-code](https://user-images.githubusercontent.com/3156978/67156490-6543f900-f31f-11e9-997b-ee155d77a90c.gif)

**Comment by tingsu** [comment]
Thanks for the fix @werman ! I will help to validate it.
