### ISSUE TITLE
[bug] "record" button and "request permissions for recording" button have inconsistent behaviors if enable and then disable "Use circular icons" 

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#572]
- I have searched the history issue list, and have not found any similar issues. 

- The bug was found in the latest release version 0.79 from Google Play, and were reproduciable on both a Google Plxel 3 (Android 9.0) and an Android emulator 6.0 device

- Background

When the user selects any station, it starts the playing. At this time, if the user presses the playing info bar at the buttom (just above the menu options), the bar will turn into the recording bar. It will show a black ``request permissions for recording`` button.  This is right behavior.

At this time, if the user presses the black button, the app will request permissions. After the user grants the permission, the black button will turn into a red ``Record`` button.  If the user presses the red ``Record`` button, the app will start the recording and the button turns into a red ``Stop`` button. When the ``Stop`` button was pressed, the button will return back to the ``Record`` button.

The issue is that if we **enable and then disable** the "Use circular icons" option in setting, the above behavior become incorrect/inconsistent.

- Reproduction steps:  

1. Refreshly install the app and start the app

2. select any station under the ``Local`` tag (the station begins to play)

3. press the ``setting`` menu option at the buttom, and then press the ``play`` button to pause the playing. 

4. select the ``Appreance`` option, and toggle twice (i.e., enable and disable) the ``Use circular icons`` checkbox

5. go back to the ``Stations`` menu option, and click on the playing info bar, it shows a red ``Record`` button. **This is incorrect because the user has never granted any permissions before. The app shoud still show a black ``request permissions for recording`` button**. Now, if the user presses the red ``Record`` button, nothing happens (neither permission request or recording)

- Reproducing video

![20191012_155638](https://user-images.githubusercontent.com/3156978/66702637-150adc80-ed0a-11e9-93ab-d7d6cda0b9bb.gif)

**Comment by werman** [comment]
The player was heavily reworked in master (it's not deployed anywhere), so if you want to report more bugs - it's better to test the latest code.  Thanks!

**Comment by tingsu** [comment]
Thanks for your quick reply! I just tried the latest commit, the GUI was totally reworked, and the function logic was also adjusted a lot. It now is impossible to reproduce this issue. Good rework on this station play module! I hope the latest version can be deployed on Google Play soon.
