### ISSUE TITLE
[bug] adding favorite stars to stations does not behave consistent (fail to sync?) between different tabs

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#573]
- I have searched the history issue list, and have not found any similar issues. 

- The bug was found in the latest code commit (``RadioDroid-free-debug-DEV-0.79-da50202.apk``), as well as in the latest released version on Google Play. It was reproduciable on both a Google Plxel 3 (Android 9.0) and an Android emulator 6.0 device

- Reproduction steps:  

1. select any station (e.g., ``Radio Paradise`` in this case) and add the  ``favorite`` star to it (e.g., under the ``Local`` tag)

2. switch to the ``Top Click`` tag, we can see the corresponding ``Radio Paradise`` is **not correctly** annotated as favorite station.

3. If we select any menu option at the buttom, and switch back to the ``Top Click`` tag, ``Radio Paradise`` now is annotated as favorite station.

- Reproducing video

![20191013_113325](https://user-images.githubusercontent.com/3156978/66713797-8cdf1280-edaf-11e9-82a3-298f000cc996.gif)

**Comment by tingsu** [comment]
Any update on this issue? I think the favorite star should be synced between different tabs. Maybe due to the view update issue?

**Comment by Wikinaut** [comment]
I have to check this. Not sure, if I have ever seen the effect.

**Comment by tingsu** [comment]
Thanks! I observed this by using the apk compiled from the latest code version.

**Comment by tingsu** [comment]
Hi @Wikinaut, thanks for your inspection on this issue. 

I just checked the issue on the latest code version (commit id: a214abe). I find this issue affects both the ``add`` and ``remove`` any station into or out of ``favorites``. When I add or remove any station into favorites, the green ``star`` icon (on the top cornor of the station image) is not consistently updated. I feel this root cause of this issue may be similar to #570 (due to the failure of refresh the view? @werman @segler-alex ).

I attached the reproduction video of this issue on the latest code version. Hope this can be useful for you to localize this issue.  Let me know if you need further info from my end. Thanks!

![RadioDroid-issue573-latest-code-commit](https://user-images.githubusercontent.com/3156978/67156666-fa47f180-f321-11e9-90eb-e2722a9e30d8.gif)

**Comment by werman** [comment]
When station is added to favourites only the current fragment is refreshed. The refresh of stations isn't handled well e.g. when added to favourites the whole station list is deserialized from json :man_shrugging:. So the consistency of the favourite status should  be solved as a broader problem (there is also inconsistency of highlighted station if playback is paused).

**Comment by tingsu** [comment]
Thanks, now I understand the root cause. I agree with you that the issue should be resolved in a global way. That will kill all similar issues.

**Comment by tingsu** [comment]
I tested this issue on the very recent code version (``RadioDroid-play-debug-DEV-0.79-a7f6c4a.apk``, modified on 2020-01-29). This issue still exists, although in some cases, the favorite star is correctly asynced. 

This is may be a minor issue, but do you have any plan to totally fix this issue? If you need to help, I would like to help test it.

**Comment by werman** [comment]
> This is may be a minor issue, but do you have any plan to totally fix this issue?

Speaking for myself - not at the any near future.
