### ISSUE TITLE
allowBackup should be "true"

### ISSUE THREAD

**Issue by 123unix** [segler-alex/RadioDroid#587]
Wondering what was the reasoning behind setting allowBackup="false" in the AndroidManifest.xml?

Now as I am switching the phone I am perplexed as to how to transfer settings and favourites.  The old phone is rooted, so backup was not an issue. The new phone is not rooted, therefore the restore doesn't proceed to completion.

For general non-technical public it must also be a headache being unable to bring your settings over to another device.

**Comment by werman** [comment]
The commit 9448fc52c78f8ef567f5df027f364640ac83d1fd that introduced the change doesn't tell why...

I agree that we should set `allowBackup` to true and test it.
