### ISSUE TITLE
Bug in menu

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#6]
There is a bug in the menu. In `RadioDroid/app/src/main/java/net/programmierecke/radiodroid2/MainActivity.java` the value `topclick` has been used twice resulting in one menu item less.

    		if (item.getItemId() == MENU_TOPCLICK) {
    			Log.v(TAG, "menu : topclick");
    			RefillList(itsAdressWWWTopClick);
    			setTitle("TopClick");
    			return true;
    		}
    		if (item.getItemId() == MENU_LAST_CHANGED) {
    			Log.v(TAG, "menu : topclick");
    			RefillList(itsAdressWWWChangedLately);
    			setTitle("Changed lately");
    			return true;
    		}

Please fix this a.s.a.p. and release a new version as this is the entry point to where contributors will see their stations appearing.

**Comment by segler-alex** [comment]
The wrong string is only used in the debug messages (Log.v)
You cannot see the last changed items in the app, because i did not release a new version yesterday. will do it today in the evening.

**Comment by PanderMusubi** [comment]
Ah, that explains it. Looking forward to a new version.
