### ISSUE TITLE
[Regression] Navigation bar symbol texts are shown incorrectly (cropped)

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#607]
I noticed that the current master branch (example https://github.com/segler-alex/RadioDroid/commit/3daa23757ea6b159285c25d09b395f2ce811c394 ) version incorrectly crops the texts in the navibar (first image) compared to the currently release 0.78 (second image):

<img src=https://user-images.githubusercontent.com/1151915/68626948-3287bd80-04e5-11ea-8575-380cbf2af605.jpg width=300/> <img src=https://user-images.githubusercontent.com/1151915/68626937-2ef43680-04e5-11ea-9d90-aa4c7b023c7b.jpg width=300 />

**Comment by werman** [comment]
I don't remember doing anything with nav bar... Probably needs to be explicitly stated not to shorten the line.

**Comment by Wikinaut** [comment]
@werman It's present since a while, have to use bisection to find the commit which causes the regression.

**Comment by Wikinaut** [comment]
@werman using git bisect, I identified

8ccb82814630727f9eb3111c3195b6cd31f5bc69 is the first bad commit.

whereas this is the last commit, which is okay:
commit 61e6f5f5e4de7851210a580a910e3a9c9f85eea5 (tag: 0.78, refs/bisect/good-61e6f5f5e4de7851210a580a910e3a9c9f85eea5)


I hope, this helps to indentify and fix the shown layout issue quickly.

**Comment by werman** [comment]
That's my commit,  `7,261 additions and 2,999 deletions.` =)

I'll fix it soon.

**Comment by Wikinaut** [comment]
@werman 
> That's my commit, `7,261 additions and 2,999 deletions.` =)
> I'll fix it soon.
Would be nice. I just tried to find the place to fix that, but I failed.

**Comment by werman** [comment]
Sometimes I think it's Android's intention to make developer life harder... 

The text is indeed doesn't fit the label at all. So the solution is to use `setAutoSizeTextType*` but the TextView in bottom view doesn't want to cooperate https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/res/layout/design_bottom_navigation_item.xml#L45 it is wrap_content which definitely doesn't work with auto sizing, making it match_parent from code also doesn't work.  It needs to wait until view is layouted to determine new text size.

 I didn't have time to make it work today - just tried a few things quickly.

**Comment by werman** [comment]
And looking at the screenshots I see that TextView did move other views aside before update. Maybe that's the answer.

**Comment by Wikinaut** [comment]
Great! Please merge a.s.a.p.
