### ISSUE TITLE
When switching output, sound plays on both outputs

### ISSUE THREAD

**Issue by X-dark** [segler-alex/RadioDroid#609]
When I switch on a Bluetooth device, my phone connects to it. Instead of stopping speaker playback and starting Bluetooth playback like other applications are doing, sound plays on both output. I have to pause/play to use only the Bluetooth output.

**Comment by werman** [comment]
Thanks for reporting this. Yes, this should be fixed.

**Comment by X-dark** [comment]
For some reasons, in some cases I don't hit this bug.
It looks like this bug is only present when the radio has been started by the alarm.

**Comment by werman** [comment]
Sorry for the delay. If it happens only when the playback is started by alarm, then it looks like intended Android behaviour. You don't want to miss an alarm. 

I'm not saying that playing alarm through headphones only is invalid use case, however it's not a default and I don't think it is withing our app scope to do this. From what I know it could be resolved by other apps which can force alarm to play on specific output.

**Comment by X-dark** [comment]
Sorry but, that is not exactly the problem.
Yes indeed, I understand the alarm being played **at start** from phone output.

My problem is **after**. When I switch the output, I expect the output to be switched and not to play simultaneously on both outputs. Now it keeps playing on phone speaker and starts playing on bluetooth device.
