### ISSUE TITLE
4 lint errors

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#61]
have you seen these (minor) lint errors:

https://9-61985475-gh.circle-artifacts.com/0//tmp/circle-artifacts.NmHsdBz/lint-results.html#MissingPrefix

with your version of app/build.gradle lint will give 4 erros and compliation will fail.
do you have these in android studio?

**Comment by zoff99** [comment]
#62

**Comment by segler-alex** [comment]
thank you for your work and time!

**Comment by segler-alex** [comment]
at the moment i ignore most of them ;)
