### ISSUE TITLE
crash on android 9

### ISSUE THREAD

**Issue by PhantomSW** [segler-alex/RadioDroid#619]
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord

**Comment by werman** [comment]
Hello, could you elaborate? How could this be reproduced? And what version are you using?

**Comment by mohamedmmh** [comment]
I am using the last version to the last commit
it happens on android 9 only ..
it crashes suddenly , could play for 5 min and crashes again.
I am trying to solve it using this article 
https://stackoverflow.com/questions/53014866/android-9-pie-only-context-startforegroundservice-did-not-then-call-service
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi91f3E_YLmAhWDBGMBHTBjDhkQFjAAegQIBxAB&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F44425584%2Fcontext-startforegroundservice-did-not-then-call-service-startforeground&usg=AOvVaw29zG1L6TwymvD3PRv04h0a
but no luck until now

**Comment by werman** [comment]
Yeah, I see. Thanks for reporting this. If you won't be able to resolve this I'll try to look at this later.
