### ISSUE TITLE
[Feature Request] Fade in for alarm (slowly raise volume)

### ISSUE THREAD

**Issue by ChrisP4** [segler-alex/RadioDroid#621]
Hello,
I discovered RadioDroid yesterday, why isn't this app more well known? It is indeed fucking awesome.

How do you feel about a fade in option for the alarm? Would it be hard to implement?

Android's default lowest volume is way too loud for me and I've been using an app that has a fade in option (and uses random songs from spotify playlists), starting with a really low volume and (I think you can change how long the fade in duration is - I've put it ~10s) slowly reaching android's default lowest volume. It has been, without exaggeration, life-changing. 

It'd be great if this could be done (would be easier for me to move away from Spotify and the proprietary app I use for the alarm), but thanks for this awesome app anyhow!

**Comment by werman** [comment]
It's being work in progress, see https://github.com/segler-alex/RadioDroid/pull/601

**Comment by Wikinaut** [comment]
Duplicate to https://github.com/segler-alex/RadioDroid/issues/102
I suggest to close this issue here.

**Comment by ChrisP4** [comment]
this was super fast!
