### ISSUE TITLE
App is not showing track info for some streams

### ISSUE THREAD

**Issue by gibcheesepuffs** [segler-alex/RadioDroid#625]
App is not showing track info for some streams however the stream is carrying track info since it shows up in VLC. 

Example of such stream(s):

Nightwave Plaza OGG 96:
http://radio.plaza.one/ogg 

Listen.Moe JPop Vorbis:
https://listen.moe/stream

**Comment by werman** [comment]
Thanks for providing examples!

http://radio.plaza.one/ogg provides metadata in ogg stream (https://xiph.org/vorbis/doc/v-comment.html) itself which could be seen in wireshark, we don't handle it at the moment.
