### ISSUE TITLE
let the user choose another server on connection error

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#629]
if there is an error on any server request, it should maybe do at least one retry and then open a dialog where the user can choose another server.

**Comment by WesRos** [comment]
An dialog to choose another server is also welcome without an connection error. Right now I've 2 server: kitchen and garden. But I can't make a choice for it.

**Comment by werman** [comment]
@WesRos I guess you talking about MPD server, it's a different thing from what this issue about. However handling of MPD is completely reworked in master, now you can see status and control all servers without selecting one.

**Comment by WesRos** [comment]
Is there an apk to see what you meant?

**Comment by werman** [comment]
@WesRos You can try the one from https://github.com/segler-alex/RadioDroid/pull/637#issuecomment-568929352 - it will be installed alongside your current installation. Also some other functionality may still have issues. If you find issues with MPD please open a new issue.

**Comment by segler-alex** [comment]
fixed

**Comment by segler-alex** [comment]
connection errors are now automatically retried with different servers
