### ISSUE TITLE
La Radio Redonda it's broken :(

### ISSUE THREAD

**Issue by wilycuestas** [segler-alex/RadioDroid#632]
[Official website](http://laradioredonda.ec/FM/) 

![Screenshot_20191209-175351_Chrome](https://user-images.githubusercontent.com/58643930/70480151-f37d6580-1aac-11ea-864c-d67fe5c20ec9.jpg)

Hi, maybe if you can check La Radio Redonda from Ecuador. The streaming on their official website it's all ok but on RadioDroid it doesn't work approximately 2 weeks ago. Thank you :)

**Comment by zo-shin** [comment]
Here is the link, feel free to add it and close this issue.
http://198.204.234.10:8378/live

**Comment by wilycuestas** [comment]
Thank you!
