### ISSUE TITLE
Separate Top Menu & Station List as Before

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#640]
Currently the top menu and station list are combined together. When scroll down the list, the top menu will be invisible, which is not convenient.

**Comment by werman** [comment]
That was done to increase the area of the stations list which was too small.
This is a common technique in such cases. The menu could easily be brought back but swiping in other direction and since it's a common pattern it won't confuse users.

**Comment by werman** [comment]
On the other hand on > 7" screen hiding the menu won't be really beneficial.
