### ISSUE TITLE
Remove Notification & Undo Button Not Show Up

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#650]
Swipe to delete any station in **favorites** or **history**, but the remove notification and undo button don’t show up.

**Comment by segler-alex** [comment]
at some point this worked already

**Comment by werman** [comment]
It gets behind other view so it's not visible...

**Comment by segler-alex** [comment]
sounds bad :( do you think this can be fixed?

**Comment by werman** [comment]
yeah, maybe it just needs to be anchored to other view. Having station's RecyclerView of proper size appeared to be not a trivial task.

**Comment by segler-alex** [comment]
to have a solution, maybe it would be better to just ask the user with a popup if the entry should really be removed?

**Comment by werman** [comment]
I don't think it's hard, I just didn't look at it closely.

**Comment by segler-alex** [comment]
it works again, thank you!
