### ISSUE TITLE
MPD password

### ISSUE THREAD

**Issue by UzixLS** [segler-alex/RadioDroid#662]
Please add ability to specify MPD password.

**Comment by werman** [comment]
Yep, forgot about them.

**Comment by segler-alex** [comment]
it supports passwords now, but no error output to the user on wrong passwords at the moment

**Comment by segler-alex** [comment]
i am closing this for now, because it works.
BUT it is not perfect, especially the lack of error detection.
maybe we should switch to an external library for mpd communication
http://finnyb.github.io/javampd/6.1.0-SNAPSHOT/using.html
