### ISSUE TITLE
Add expandable radio-player options

### ISSUE THREAD

**Issue by aha999** [segler-alex/RadioDroid#663]
When you press on a radio station it should expand the currently playing tab to full screen where you can easily control volume, see radio thumbnail and go to next/previous radio station. Also in the left top corner of the menu could be the "shrink" or "retract" button, which would minimize the player in the tab where it's currently just  the pause button.

The same player could expand when you press on a currently playing radio tab, pressing it currently just gives a red record circle button and recordings list button. Those options could be present in the expandable player. 

Example of concept:
![](https://i.imgur.com/Kw05EjK.jpg)

**Comment by werman** [comment]
There is a one, see #495 . It's not released because there are still several critical issues in master.

**Comment by aha999** [comment]
Oh, nice! thanks for making it. i hope issues get resolved.
