### ISSUE TITLE
App localization / translation

### ISSUE THREAD

**Issue by aha999** [segler-alex/RadioDroid#665]
As i can't find any information about app translation to contribute, so i assume it's currently not possible to translate the RadioDroid app to other languages. If that's the situation, please take my recommendation to put the project language strings to a localization platform like [Weblate](https://weblate.org), which has a good github integration, Weblate is free&opensource, free for open-source projects and simple for managing the languages, translated/untranslated strings etc.
Other similar platforms: Transifex, Crowdin...
If you do that, please add the Translation info/link to the Readme.

**Comment by werman** [comment]
I think people used whatever they know, there is the same issue opened https://github.com/segler-alex/RadioDroid/issues/345. But yes, thanks for reminder, we need a one "official" easy way to do this.

**Comment by segler-alex** [comment]
if you want to help translate please just download
https://raw.githubusercontent.com/segler-alex/RadioDroid/master/app/src/main/res/values/strings.xml
translate it
and send it back here

**Comment by aha999** [comment]
Sure but that's just temporary until the new strings get added... but over a platform like weblate its easily visible, and also free.
