### ISSUE TITLE
New beta release 0.80

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#667]
Hi,

i have invested a lot of time in the new backend servers, they have now the same features as the main one and even surpas the main server in some things.
so i start updating radiodroid again. i latest 2 commits make radiodroid now only use the new servers, and it chooses a random server on every app start. if a server goes down, it even does fallback requests to the other servers. which should make it very stable now.

i want to work towards a new radiodroid release, i really like the new station detail page, wow!! thank you all!

but there are also some bugs, especially the search is not working properly, i do not really understand how this filter and local/global search are meant. could you help out? also maybe post here a list of more bugs we have to fix to get it to a new release?

thank you again!

**Comment by werman** [comment]
High prio things to be fixed:

- https://github.com/segler-alex/RadioDroid/issues/634
- https://github.com/segler-alex/RadioDroid/issues/641- off-wifi warning crash, working on this
- From https://github.com/segler-alex/RadioDroid/issues/642:
  - User should be able to delete track history
  - If there is no lyrics-supported app installed, the lyrics command won’t respond.
- https://github.com/segler-alex/RadioDroid/issues/624
- Fix search by tag and https://github.com/segler-alex/RadioDroid/issues/580

**Comment by werman** [comment]
> especially the search is not working properly, i do not really understand how this filter and local/global search are meant.

It will search if you enter >= 3 symbols. And yes that's probably not a good behaviour, it should send request even if 1 character is typed but just limit the response.

`FilterType.GLOBAL` means search in ALL stations with request to server. `FilterType.LOCAL` means in currently displayed, e.g. for history and favourites, but there is no search there at the moment so only `FilterType.GLOBAL` is really used.

**Comment by segler-alex** [comment]
i will fix the filter and tags search

**Comment by werman** [comment]
> i will fix the filter and tags search

Just fyi: in search if new query starts with past query we won't launch new request to the server and will just filter locally for greater responsiveness, so if you will limit the stations amount for 1/2 character queries - keep this in mind.

**Comment by Wikinaut** [comment]
regrading search: I do not notice any bugs which prevent the suggestion search from being rolled-out.

**Comment by segler-alex** [comment]
i am currently investigating, but it seems to me suggestion search and the tags broke each other, they use the search fragment in different ways...

**Comment by segler-alex** [comment]
and as i found out, local search IS currently in use. it will come into effect if you refresh the search view by pulling it down with a gesture

**Comment by segler-alex** [comment]
ok, maybe technically it is not the "LOCAL" search, but it does filtering locally

**Comment by werman** [comment]
> and as i found out, local search IS currently in use. it will come into effect if you refresh the search view by pulling it down with a gesture

`FilterType.LOCAL` isn't used there unless I'm missing something. However swiping down in search doesn't make a new request to server, however we probably want to make one for it to be actually refresh of search

**Comment by segler-alex** [comment]
i think i found all crashes with search, and i made the search type more explicit (byname,bycountry,bytag,bylanguage)

**Comment by segler-alex** [comment]
now i have a problem with the refresh, when i do the pull down gesture the first time, a lot of stations get filtered out. :(

**Comment by segler-alex** [comment]
also clicking tags does produce an empty list when done from the favourites list.

**Comment by werman** [comment]
> now i have a problem with the refresh, when i do the pull down gesture the first time, a lot of stations get filtered out. :(

Because it triggers local filtering instead of actually making new call to a server.

**Comment by segler-alex** [comment]
what is the idea behind local filtering? is it intended to make the list shorter?

**Comment by segler-alex** [comment]
seems like a stupid question from me i know :) but the list is already filtered by the server, and then locally it gets filtered again. seems strange to me

**Comment by segler-alex** [comment]
maybe i don't understand the intention

**Comment by werman** [comment]
> what is the idea behind local filtering? is it intended to make the list shorter?
> seems like a stupid question from me i know :) but the list is already filtered by the server, and then locally it gets filtered again. seems strange to me

What you see is a bug. 

The intent is to when we already have a list from the server, as user types, instead of making new requests to narrow is further - we just filter it locally. Thus increasing responsiveness and reducing requests to server.

And when you force refresh the view logical behaviour would be actually fire new request to server, which doesn't happen because that case wasn't handled.

**Comment by segler-alex** [comment]
could it be used in your opinion for example, to click a country, then have a list of all stations of the country, and then do a narrow the search in this list by searching by name from the search input field locally?

**Comment by segler-alex** [comment]
i think i understand now how this is meant, it works again. i do force refetch on pull gesture

**Comment by werman** [comment]
Yes. The bigger issue is to communicate to user what's going on with search (we can do without it but having some indication would be nice)

**Comment by GeilerHeinz** [comment]
Sounds like beta version 0.80 has been released already. I would like to contribute and test it. Do I have to install it manually or will you release it for beta tester via play store as well?

**Comment by segler-alex** [comment]
there are still bugs to fix before an official beta
https://github.com/segler-alex/RadioDroid/milestone/1

if you would like to help, you could try the newest alpha. Thank you!
[RadioDroid-play-debug-DEV-0.79-aa0c7c5.zip](https://github.com/segler-alex/RadioDroid/files/4144141/RadioDroid-play-debug-DEV-0.79-aa0c7c5.zip)

please add "found in alpha" to bugs you may find, so that we know this is about this build.

**Comment by segler-alex** [comment]
there is another solution, we could just use exactly the name in writing in countries.json

**Comment by segler-alex** [comment]
newest version
[RadioDroid-play-debug-DEV-0.79-1b0022c.zip](https://github.com/segler-alex/RadioDroid/files/4145259/RadioDroid-play-debug-DEV-0.79-1b0022c.zip)

**Comment by zo-shin** [comment]
With the commit, the font color of **enable MPD** and **add MPD server** should also be changed.

**Comment by segler-alex** [comment]
new version:
[RadioDroid-play-debug-DEV-0.79-ba00fd1.zip](https://github.com/segler-alex/RadioDroid/files/4150469/RadioDroid-play-debug-DEV-0.79-ba00fd1.zip)

**Comment by segler-alex** [comment]
if somebody finds issues that are already fixed, please post them here, i will close them

**Comment by segler-alex** [comment]
i added a changelog, please add all things there that you think should be in it

**Comment by werman** [comment]
@segler-alex Sorry for the delay, I think the following could be added to the changelog:

Added:

- History of the played tracks
- Stations search now shows results as you type
- Option to resume on wired or bluetooth device reconnection

Changed:

- Reworked user interface for MPD which now allows explicit management of several servers
- Improved user interface of recordings

**Comment by segler-alex** [comment]
release is out

**Comment by segler-alex** [comment]
thank you for your help!!
