### ISSUE TITLE
still crashing on v0.21

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#67]
07-02 14:03:07.238: E/AndroidRuntime(11769): FATAL EXCEPTION: Thread-361
07-02 14:03:07.238: E/AndroidRuntime(11769): Process: net.programmierecke.radiodroid2, PID: 11769
07-02 14:03:07.238: E/AndroidRuntime(11769): java.lang.IllegalStateException: Unbalanced enter/exit
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:524)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:508)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.internal.Util.skipAll(Util.java:176)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.internal.Util.discard(Util.java:158)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:547)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:399)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:387)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at net.programmierecke.radiodroid2.StreamProxy.stop(StreamProxy.java:302)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at net.programmierecke.radiodroid2.PlayerService$3.run(PlayerService.java:342)
07-02 14:03:07.238: E/AndroidRuntime(11769): 	at java.lang.Thread.run(Thread.java:818)

**Comment by zoff99** [comment]
can you please put a "try {} catch {}" around the whole thing. it's really annoying. it still crashes all the time.
please fix this permanently. really bad while driving, to fiddle on the phone :-(

**Comment by segler-alex** [comment]
there was already a try catch, but not for all errors, i changed that :)
