### ISSUE TITLE
Reformat Items in Countries & Languages

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#673]
The initials of items in countries and languages should be capital letters.

**Comment by segler-alex** [comment]
it is maybe more complicated than that. what about multi word countries?
what about countries that have words in them that should be lower case, like "and"?

**Comment by segler-alex** [comment]
what do you think about writing it ALL upper case?

**Comment by segler-alex** [comment]
there is another solution, we could just use exactly the name in writing in countries.json :)

**Comment by zo-shin** [comment]
OK, that's what I want to suggest.

**Comment by zo-shin** [comment]
How about the languages field? Maybe there should be some changes on the server side.

**Comment by segler-alex** [comment]
i think they should stay this way or make them all uppercase for now. 

a more long term solution would need a server change, like you suggested and this would be adding features. but i want to only do bugs until 0.80. every feature pushes 0.80 more to the future.

serverchange that may help for this
https://github.com/segler-alex/radiobrowser-api-rust/issues/54

**Comment by zo-shin** [comment]
OK.

**Comment by zo-shin** [comment]
Is it possible to make the country names translatable?

**Comment by segler-alex** [comment]
yes, that would be possible now easier than before

**Comment by segler-alex** [comment]
we only need to map countrycodes to the translated country names

**Comment by zo-shin** [comment]
If that's not a hard job, could you make it possible in v0.80?

**Comment by segler-alex** [comment]
please add a new issue for that,
it will definitelly not happen for 0.80, because i don't want to add any more features, only bugfixes now.
