### ISSUE TITLE
Some History Items Fail to Be Saved

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#678]
In the debug release, the stations played by the external player are not saved in history.

**Comment by segler-alex** [comment]
i think externally played things cannot be put into the history. it would mean proxying the stream through our app.

**Comment by zo-shin** [comment]
It worked in the previous version. Maybe the option "save external player history" is needed.

**Comment by werman** [comment]
It's about station history, not the tracks one. Yes, I'll return it, it got lost during refactoring.
