### ISSUE TITLE
Do we still want pause button in app to mean "stop" and in notification to mean "pause"

### ISSUE THREAD

**Issue by werman** [segler-alex/RadioDroid#682]
When I pause playback from application UI - notification with controls disappear which in most cases I don't want to, notification already could be either swiped away, it has explicit stop button, and it will be also removed if I perform actual exit from application.

I don't think that current behaviour of pause is conveniently and could be expected by users. However I would like to listen to your opinions.

**Comment by morckx** [comment]
I absolutely agree with you. "Pause" means that I want to continue listening and get annoyed if RadioDroid is already killed. I also think that RadioDroid is about the only audio app that handles pause like this.

**Comment by segler-alex** [comment]
what would be the optimal behaviour?

**Comment by werman** [comment]
Make the pause button pause like the pause button in the notification.
