### ISSUE TITLE
Add Notification Before Jumping to Google Play

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#692]
Google Play is not necessarily all users’ preferred app market, and some devices may even not have it installed. It’s better to show a notification like “QuickLyric is not installed on your device. Would you like to get it from Google Play now?” before jumping to it.

**Comment by segler-alex** [comment]
it works also without google play, i get asked which store should be used on my old phone

**Comment by zo-shin** [comment]
I know it, but I think users should be told before jumping to any other app from radiodroid.
