### ISSUE TITLE
[Clarification request] Text in Player > Settings > "Headset disconnect" versus "wired connection"

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#698]
I wanted to translate the setting strings for

* "Pause on headset disconnect"
* "Resume on wired connection"

I suppose that "headset" (subtext ist "wired headset") is the very same as "wired connection".

Please can someone elaborate on that, thanks.

If this is the case (that the same is meant), then I will also harmonize the English text strings.

**Comment by werman** [comment]
"Pause on headset disconnect" -> On any headset/audio device disconnect, both wired and wireless.
"Resume on wired connection" -> Resume only when wired is re-connected.

**Comment by Wikinaut** [comment]
Ok.  I will try to harmonize/clarify all of them (including translations to German) a.s.a.p.
Closing this already now.

**Comment by Wikinaut** [comment]
@werman just a follow-up question:

The third setting is called "resume on bluetooth connection".#

So do I understand that correctly that we currently have *one* option for the disconnection action and *two* options for connection, like that:

* Pause on (wired or bluetooth) headset disconnect
* Resume on (wired) headset connection
* Resume on (bluetooth) headset connection

**Comment by werman** [comment]
Yes, because the pause option is really a "pause when becomes noisy", it's a system event telling us that device uses loadspeakers.
