### ISSUE TITLE
Service "PlayerService" runs forever

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#71]
if there is no radio station playing and i leave the app, the Service keeps running and does not stop.
please make the serivce stop itself when there is nothing to do.

**Comment by zoff99** [comment]
any comment on this issue?

**Comment by BatsellBarrettBaxter** [comment]
This basically makes the app unusable for me, or at least extremely inconvenient to use. Either provide a quit button, which is quick and easy, or use .bindService properly. Right now you call bind and then immediately call startService. Don't do that. Call start when media playback is requested, and stop when it is ended. The bind state is managed independently of this, meaning the service won't actually stop til there's no more bound clients. But it will stop when the user navigates away, which is how it should be done. 

Please fix this. There are so many apps that waste memory and CPU in this way, and we don't need more. I'd love to use your app but this is extremely problematic for me.

**Comment by Cormak** [comment]
@zoff99 @BatsellBarrettBaxter I notice this as well. The player service keeps running even the player is closed, the notification has been swiped away, and Radiodroid has been cleared from the recents menu. 

At the very least, it should fully close when cleared from recents. This is unacceptable, especially in an open source app. This is app behavior I would expect from a closed source app with ads and other analytics.
