### ISSUE TITLE
Allow user to import and export favorites and history.

### ISSUE THREAD

**Issue by gibcheesepuffs** [segler-alex/RadioDroid#717]
Allow user to import and export favorites and history as a file to filesystem for backup an restore purpose.

**Comment by Wikinaut** [comment]
Import and export of Favorites is already implemented: got to tab "Favorites" and click onto the extensions menu ("Import/Export as Playlist").

**Comment by shoukolate** [comment]
Please implement something for history backup too.

**Comment by werman** [comment]
@shoukolate Could you describe why do you need to backup the history? And does it mean you want to be able to restore it back?

**Comment by Wikinaut** [comment]
Personally (as a developer), when switching between locally compiled versions and the Play Store version, and when distributing to other phones in my house, I also wished to reset (and set other devices) to the very same state.

Having this in mind, I also support the wish to have not only the favorites but also the history store- and restorable.

**Comment by werman** [comment]
@Wikinaut I see, thanks. However I think the better option would be full export of app
's data. Because we have:
- Settings
- Favourites
- Stations history
- Tracks history

I'm not opposing exporting of the history alone, but would like to add a full solution instead of half-baked measures.

**Comment by Wikinaut** [comment]
@werman I am in favour of a Full export, given, that the "light export" of the Favorites as playlist.m3u remains.

Rationale: Sometimes I use the m3u to feed my tiny https://shop.pimoroni.com/products/pirate-radio-pi-zero-w-project-kit with that list!

**Comment by werman** [comment]
I agree, exporting m3u is useful.

**Comment by segler-alex** [comment]
m3u import/export serves another purpose than a full backup/restore. 
it helps people moving their lists to different apps, because i try to push a standardized m3u format that has added radiobrowserheaders.

**Comment by segler-alex** [comment]
for example shortwave should also be able to import/export m3u in this format
