### ISSUE TITLE
feature request: easily reorder bookmarked stations

### ISSUE THREAD

**Issue by dtcg** [segler-alex/RadioDroid#72]
Wouldn't it be nice to, say, long-tap on a bookmarked station to enter some sort of "rearrange mode"?
Maybe in a note-taking app fashion?
Stations tend to accumulate in the order they were added to the bookmark session and it gets pretty confusing over time.
Keep up the great libre work!

**Comment by Wikinaut** [comment]
Implementation idea:

I suggest to implement the code of https://github.com/bauerca/drag-sort-listview to allow a manual reordering of "starred" radio stations (the "Favorites").

I found https://github.com/bauerca/drag-sort-listview being used in my favourite Music Player App which is https://github.com/vanilla-music/vanilla Vanilla Music.

**Comment by PanderMusubi** [comment]
Hope to see this features added as, at the moment, there is no way to organize favorites.

**Comment by treestryder** [comment]
As I have added my favorites haphazardly, even the ability to alphabetize them would be an improvement.

**Comment by segler-alex** [comment]
this has been implemented in beta
