### ISSUE TITLE
App Notification starts when I turn Bluetooth on

### ISSUE THREAD

**Issue by getwet** [segler-alex/RadioDroid#724]
Hi.

since the last update the App notification starts when I turn Bluetooth on an I cannot close it. I need to force the App close.

**Comment by werman** [comment]
Several issues with the notifications would be fixed in the next beta update.

**Comment by segler-alex** [comment]
i was also thinking about releasing 0.81 with the additional fixes

**Comment by werman** [comment]
> i was also thinking about releasing 0.81 with the additional fixes

I want to land at least #715 and #721 before 0.81. With them I don't have any critical issues left in sight.

**Comment by getwet** [comment]
Sounds good! :-)
I was not shure if I'm the only one having this problem.

**Comment by FrancescoCappio** [comment]
Same problem here. 
Thanks to all the contributors this app is wonderful!
