### ISSUE TITLE
Some icons are invisible after libraries update 

### ISSUE THREAD

**Issue by werman** [segler-alex/RadioDroid#729]
![image](https://user-images.githubusercontent.com/3993671/75486538-5e0bb680-59b5-11ea-8c80-b344729b991e.png)
![image](https://user-images.githubusercontent.com/3993671/75486557-6663f180-59b5-11ea-8dd8-d40a253de144.png)

At least on API 28

@morckx

**Comment by morckx** [comment]
I can confirm this, also on API 29. I'll have a look.

**Comment by morckx** [comment]
Record button should only be shown when playback is started?

**Comment by werman** [comment]
I don't think so. I don't like that it is doing nothing when playback is paused and it would be better to have a toast instead of unresponsive button, but I think it should be always be shown, otherwise there will be strange empty space.

**Comment by morckx** [comment]
OK, I wasn't sure if it was there before, but you are right. I'll add it tomorrow.
BTW: I have no idea why the buttons disappeared.

**Comment by werman** [comment]
I think it worth investigating, we cannot set everything in code. What if something else disappears next =)
