### ISSUE TITLE
Connection to the station list failed

### ISSUE THREAD

**Issue by Maskulinum** [segler-alex/RadioDroid#739]
RadioDroid Version 0.80 (git 82c3994) on Android 9
When i start RadioDroid i get the message: "Die Verbindung zur Stationsliste (Radio-Browser-Server) schlug fehl." The connection to the station list failed.

So i can't find any radio station. Internet connection is on. Since last update (1 week ago) over F-Droid.

**Comment by werman** [comment]
Hi, could you post logs from the logcat at the time you launch the app? We had a similar report https://github.com/segler-alex/RadioDroid/issues/718 but it wasn't reproducible.

**Comment by Maskulinum** [comment]
Here a log
[logcat_02-29-2020_19-59-16.txt](https://github.com/segler-alex/RadioDroid/files/4270813/logcat_02-29-2020_19-59-16.txt)

**Comment by werman** [comment]
Thanks you! Relevant excerpt from the log:

```
Url=https://all.api.radio-browser.info/json/stations/bycountrycodeexact/de?order=clickcount&reverse=true

Url=https://all.api.radio-browser.info/json/stations/bycountrycodeexact/de?order=clickcount&reverse=true (not cached)

downloadFeed() javax.net.ssl.SSLPeerUnverifiedException: Hostname all.api.radio-browser.info not verified:
    certificate: sha256/BmqvQqbRe61XESmnLsZPkqvR26F7d1DHVOe9T2vC/r8=
    DN: CN=de1.api.radio-browser.info
    subjectAltNames: [de1.api.radio-browser.info]
```

**Comment by werman** [comment]
It looks like for some reason
```
InetAddress.getAllByName("all.api.radio-browser.info")
```

returns `all.api.radio-browser.info` in an array of addresses.

**Comment by segler-alex** [comment]
this is very strange, it should not happen. when you do the following commands it works:
```
# this gets 3 ips
dig all.api.radio-browser.info
# this gets the names of the ips
dig -x 91.132.145.114
dig -x 45.77.62.161
dig -x 95.179.139.106
```
for now we have to filter out all.api.radio-browser.info

**Comment by werman** [comment]
It really looks like some internet providers doing some strange things. Maybe we also can switch server when getting such error.

**Comment by segler-alex** [comment]
my dns server settings are correct. so it has to be something in the middle i think

**Comment by segler-alex** [comment]
i now also tried ipv6 dns entries, they also work...

**Comment by segler-alex** [comment]
it should be an easy fix to filter out all.api.radio-browser.info
