### ISSUE TITLE
Pause radio when receiving a phone call

### ISSUE THREAD

**Issue by valvin1** [segler-alex/RadioDroid#74]
I am using RadioDroid with the Bluetooth system of my car. When I receive a phone call I have to stop manually RadioDroid. And after the call find the app and launch my stream again (while i'm driving ... oops !)

When I am using other streaming player (Spotify for example) if I receive a call application pause the stream during the call and starts it back when the call is finished.

It should be great if we can have such feature :) 
-> link to #73

**Comment by tanty** [comment]
This is an important one.

**Comment by erazer1** [comment]
I have implemented this and will make a pull request...
The music will be paused during a call and resumed upon hangup.
Also, the music will be lowered when another app requests it - very useful if you use
a navigation app at the same time.
BR, erazer

**Comment by Wikinaut** [comment]
Yes, please, a fix is urgently needed.

**Comment by Mikrofarad** [comment]
Would be really nice 👌

**Comment by akeif** [comment]
Also having this problem.
Please fix :)

**Comment by werman** [comment]
It was fixed by #148

**Comment by Cormak** [comment]
@segler-alex you may want to confirm and close this issue, judging from the comments above.

**Comment by Mikrofarad** [comment]
Fixed :-)
