### ISSUE TITLE
bugfix release 0.81

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/RadioDroid#746]
what do we need still?
this should just be a bugfix release for 0.80

**Comment by segler-alex** [comment]
please post things that should be added to the changelog

**Comment by werman** [comment]
I think we should check how alarm interacts with metered connection warning #744

**Comment by werman** [comment]
Beside #748 I don't have anything to add to the release, unless someone finds some critical error.

**Comment by zo-shin** [comment]
#395 still exists on some devices.

**Comment by werman** [comment]
I'll also take a look at #743 (no days selection for alarm) which looks like regression.

**Comment by segler-alex** [comment]
i will create 0.81 tomorrow, if nothing bad happens

**Comment by werman** [comment]
I think we would have to make 0.82 because now auto resume after call is broken...

**Comment by werman** [comment]
I've made two PRs which I want to be in a bugfix release for bugfix release =)

**Comment by segler-alex** [comment]
please test it, i will make another release either tomorrow or friday evening.

**Comment by werman** [comment]
I'm testing it, however without automated tests we need everyone to test it. @Wikinaut @zo-shin @morckx

**Comment by morckx** [comment]
I'm already testing. Resume after phone call works for me.

**Comment by zo-shin** [comment]
Resume after call has no problem.

**Comment by morckx** [comment]
Seems to be rock solid for me on Android 10. Also with #759
