### ISSUE TITLE
[Version 0.80] Radiodroid starts running automatically when I enable Bluetooth. 

### ISSUE THREAD

**Issue by ArmitageShanks** [segler-alex/RadioDroid#747]
With the latest update (0.80), everytime I enable Bluetooth the app starts automatically, and I get a notification its running in the pull-down menu. Even more annoyingly is that you can't swipe it away without manually starting the app and exiting it.

I have reverted back to 0.79 which does not have this issue.

I'm on LOS 16.1.

**Comment by werman** [comment]
Thanks for reporting. Will be fixed in 0.81. Duplicate of #724
