### ISSUE TITLE
RadioDroid doesn't go away in notifications

### ISSUE THREAD

**Issue by aha999** [segler-alex/RadioDroid#760]
Although the radiodroid is turned off, it randomly opens the player in the notifications bar. I close it, or close the program and the notification player immediately reappears.

![](https://i.imgur.com/agr7Emk.png)

**Comment by werman** [comment]
Hi, I assume you have RadioDroid 0.80. The issue is fixed in 0.82 which isn't in f-droid yet. At the moment you can download it from our releases page https://github.com/segler-alex/RadioDroid/releases

**Comment by aha999** [comment]
Yes, i'm using a F-Droid version 0.80. Will update when it becomes available on F-Droid.

**Comment by GambaJo** [comment]
Have the same problem. Also from F-Droid.

**Comment by aha999** [comment]
@werman Werman, thanks for the tip. i updated the f-droid RadioDroid now that it has become available and it looks like the problem is solved. I see it has been fixed in verision[ 0.81](https://github.com/segler-alex/RadioDroid/releases/tag/0.81):
bug fixes:
- Stop notification relaunch after stop
- Autostart of notification

Closing issue.
