### ISSUE TITLE
Removing stations from favorites should be confirmed

### ISSUE THREAD

**Issue by Vrihub** [segler-alex/RadioDroid#768]
Removing stations from favorites, by clicking on the star icon below the station (or on the station icon) is currently done immediately.

It should trigger a Confirm/Undo dialogue instead, like we currently do for the delete-by-swipe feature (which in turn should be removed, see #767).

If you choose to use the current "Undo" dialogue, please make it last infinitely: the current time (3 secs) is way too short.

**Comment by werman** [comment]
> It should trigger a Confirm/Undo dialogue instead

You are right

> If you choose to use the current "Undo" dialogue, please make it last infinitely

I don't think that having no timeout is a good idea, but extending it to like 6 seconds could be good.

**Comment by Wikinaut** [comment]
No confirm dialog, please - or make the confirmation a user option. I want to be able to remove stations very quickly. So, when I will be able to generally opt-out from a (new) confirmation-to-delete, I would support this feature request.

**Comment by werman** [comment]
I think improving the swipe, adding undo toast to this way of removal and making it linger for longer time will greatly improve removal usability.

**Comment by Wikinaut** [comment]
Yes (similar to the undo possibility when swiping).
