### ISSUE TITLE
History Items Sometimes Fail to Be Saved

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#775]
I have searched the history issue list, and have not found any similar issues.  The issue I reported here is **totally different** from this previous issue #678. 

The issue was found in the latest released version on Google Play (0.82, ``git e19de92``). It was reproduciable on both a Google Plxel 3 (Android 9.0) and an Android emulator 6.0 device. This issue was also found in a previous released version (0.79, ``git 92de9af``). 

Reproduction video (reproduced on v8.2 on a Google Pixel 3 phone)

- Correct functionality

Note that: two stations ``Prambors otopulsa.com`` and ``Bollywood Radio and Beyond`` were played, and both of them (corresponding to ``THE WEEKEND`` and ``Dj Arvee`` in this history list) are correctly saved in the history list. Perfect!

![RadioDroid-8 2-7 9-seed-test](https://user-images.githubusercontent.com/3156978/77861480-85081300-7215-11ea-8f91-c0d47772e23d.gif)

- Incorrect functionality

Note that: although two stations ``Mosaique FM`` and ``Bollywood Radio and Beyond`` were played. Only ``Bollywood Radio and Beyond`` (corresponding to ``Dj Arvee`` in this history list) was saved, and **the history item of ``Mosaique FM`` was lost**.

![RadioDroid-8 2-7 9-mutant-test](https://user-images.githubusercontent.com/3156978/77861765-4ffcc000-7217-11ea-8815-0c731c78784c.gif)

**Comment by werman** [comment]
You are referring to the track history (in the fullscreen player).

It is a track history, meaning that if there is no track - there is no item in the list. I'm not sure if we should add one if station doesn't supply track metadata, because it won't contain any useful information.

**Comment by tingsu** [comment]
Thanks for your quick reply. Do you mean this issue is due to ``Mosaique FM`` has no track information?  How to know a station does not have track information?  But on my hand, I have the same issue with a station with track information.

**Comment by werman** [comment]
> Do you mean this issue is due to Mosaique FM has no track information? How to know a station does not have track information?

Yes. On your video when `Mosaique FM`  is playing there is no other label with current track title (you can see this in both small and fullscreen player), only a name of the current station. 

> But on my hand, I have the same issue with a station with track information.

And which station is it?

**Comment by tingsu** [comment]
Thanks for your explanation, @werman ! I understand.  I checked another issue on my hand, and it also does not have the track information... so, you are right. 

As a user, to be honesty, I probably do not know this mechanism enforced behind the app. I just hope it can record the station I have ever played with so that it would be easy for me to look up.  So, I mean, it would be quite useful and straightforward to record any played station here.  Do you have any other considerations when you designing this feature?

**Comment by tingsu** [comment]
Or, do you think, it would be better to revise the ``History`` title to ``Track History``  (in the fullscreen player)? To be honesty, I have used and tested this app for a long time. But until now, I note there are in fact two different kinds of history lists (``History`` and ``Track History``). Do you think it will be better to make these two more distinct for users on the GUI page? 

Anyways, thanks a lot for building and maintaining this app.

**Comment by tingsu** [comment]
How do you think my suggestions? In fact, this "issue" was previously spotted on an old version 0.79. From that version, no words like "track history" can be found (Thus, I assume ``History`` is history, no difference) .  So I think, one very simple way, is to explicitly write ``Track History`` (in the full screen player) to avoid any confusion.

**Comment by werman** [comment]
There is already a PR doing renaming "History" -> "Track history". I don't know why I even left it named as plain "History". 

 The intent of this history is to save information about all played tracks, allowing user to see and copy their names, see album art (disabled at the moment), view lyrics and playback time.

**Comment by tingsu** [comment]
Okay, thanks for your info and reply, @werman. I did not know this issue was noted and had a PR. I agree with you on the intention of this ``Track History``.

**Comment by werman** [comment]
It's a new PR https://github.com/segler-alex/RadioDroid/pull/777 after our discussion in this issue.

**Comment by tingsu** [comment]
Hi @werman , I saw the PR #777 fixed this issue. Can I close this issue?

**Comment by werman** [comment]
> Hi @werman , I saw the PR #777 fixed this issue. Can I close this issue?

Yes
