### ISSUE TITLE
[Suggestion for improvement] DragSortListView for Favorites

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#78]
I suggest to implement the code of https://github.com/bauerca/drag-sort-listview to allow a manual reordering of "starred" radio stations (the "Favorites").

I found https://github.com/bauerca/drag-sort-listview being used in my favourite Music Player App which is https://github.com/vanilla-music/vanilla Vanilla Music.

**Comment by Wikinaut** [comment]
I think this is no longer needed, since the list can be somehow pruned by using the new swipe-removal feature since version 0.43.

**Comment by Wikinaut** [comment]
duplicate of #72

**Comment by kxrob** [comment]
The swipe-removal feature is not really a solution for list reordering so far. A change at the top of the list would require a complete rebuild. A swipe-move 
, optionally a gripper, is essential to make the favorites usable. 
One of the closed issues should be reopened?

**Comment by kxrob** [comment]
(A good example: Antennapod's Play list)

**Comment by TheMax99** [comment]
Agree swipe and remove does not have the required functionality. Drag to re-order is favoured here too.

**Comment by hfel** [comment]
Coming from Simple Radio, would like to have the possibility to order favorite stations as well.

**Comment by Vrihub** [comment]
+1 this is very needed

**Comment by TheMax99** [comment]
+1 Biggest missing feature. Currently artist and track information often cuts off, and font a little too small..... frequently very frustrating! Or maybe better, just re-size bigger the bottom panel to accommodate one line for artist, and separate line for track. The box could be as big as the station list boxes above it instead of half the vertical height as it is now. Why so small?

**Comment by knut-hildebrandt** [comment]
I just can repeat that it would be great to have the possibility to reorder the stations by dragging them to the preferred position. Automatic alphabetic ordering would be nice too, but not necessary.

**Comment by Wikinaut** [comment]
fixed in https://github.com/segler-alex/RadioDroid/commit/d16e4b90c93e91ad4270d130ca4510f4ff8de848 . @morckx T h a n k   y o u  v e r y   m u c h

**Comment by morckx** [comment]
> fixed in [d16e4b9](https://github.com/segler-alex/RadioDroid/commit/d16e4b90c93e91ad4270d130ca4510f4ff8de848) . @morckx T h a n k y o u v e r y m u c h

Thanks for the feedback! I had completely overlooked that there already was an issue, but the need was  obvious and the solution quite simple.

**Comment by knut-hildebrandt** [comment]
> fixed in [d16e4b9](https://github.com/segler-alex/RadioDroid/commit/d16e4b90c93e91ad4270d130ca4510f4ff8de848) . @morckx T h a n k y o u v e r y m u c h

Great, thanks.
