### ISSUE TITLE
Recording button fails to change its state if the station was paused outside of the full screen player

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#782]
I have searched the history issue list, and have not found any similar issues. 

The issue was found in the latest release version 0.82 from Google Play, and were reproduciable on both a Google Plxel 3 (Android 9.0) and an Android emulator 6.0 device. This issue also exists in a previous released version 0.79.

Bug description
- The recording button fails to change its state if the station was paused outside of the full screen player (i.e., was paused in the small screen player).

Reproducing video

- Correct functionality

![20200331_104153](https://user-images.githubusercontent.com/3156978/78006537-6f8e0880-733d-11ea-8b4d-ff4ee4df7baa.gif)

- Incorrect functionality  (the recording button does not react to clicks)

![20200331_104224](https://user-images.githubusercontent.com/3156978/78006569-79177080-733d-11ea-8056-12d56d721d8f.gif)

**Comment by tingsu** [comment]
Any update on this issue? Thanks.

**Comment by werman** [comment]
It will be fixed, thanks.

**Comment by tingsu** [comment]
Thanks for your confirmation and quick reply.
