### ISSUE TITLE
M3U8 stream recorded as .ts and .ts was not played

### ISSUE THREAD

**Issue by rkpapps** [segler-alex/RadioDroid#791]
When we Record M3U8 stream this recorded as .ts and .ts was not played inside app
try to make a solution to play .ts directly in app without rename it..

**Comment by werman** [comment]
Being somewhat pedantic - RadioDroid doesn't play local music files, when you click on recording in RadioDroid it just sends to the system "anyone, play this audio file".

I think major audio players (like VLC) should open such files. So you can play the recorded audio file only if you rename it? What extension you are renaming it to? And what player do you use?

However there are issues with recording such streams that will result in unplayable files.

**Comment by zo-shin** [comment]
Is it better and possible to make the app also a simple local music player?

**Comment by werman** [comment]
> Is it better and possible to make the app also a simple local music player?

No, and it wouldn't really solve any issues. The biggest issue with recording now is that some recordings are not really playable. We just dump the stream into the file and hope it would be playable, and it looks like there are certain cases where it won't be.

**Comment by zo-shin** [comment]
I mean to make the app play local music files, not recorded files.

**Comment by werman** [comment]
> I mean to make the app play local music files, not recorded files.

This would be just adding complexity where we already have enough. And wouldn't solve any tangible problem.

**Comment by rkpapps** [comment]
My suggestion is rename .ts recording to .mp3 inside coding and it will be playable

**Comment by werman** [comment]
> My suggestion is rename .ts recording to .mp3 inside coding and it will be playable

This shouldn't make a difference for most players. So:
1) What music player do you have?
2) What station do you record?
3) Does changing extension from .ts to mp3 helps?
4) What if you play file with .ts extension with VLC player?

Changing to mp3 might work in some cases, however mp3 is only one of codecs possible in .ts - see https://en.wikipedia.org/wiki/HTTP_Live_Streaming

**Comment by rkpapps** [comment]
Why not play recording again in app inside because app support .ts and other player not support some .ts work after rename to mp3 in other players

**Comment by werman** [comment]
We wouldn't support playing recordings in the app because it adds a lot of additional code and cases to handle - we have enough of complexity. 

Players like VLC should be able to play these recordings if they are valid (as I said before, some are invalid and we need to investigate why is that the case). Also we may probably infer what is in TS stream and save with appropriate extension.
