### ISSUE TITLE
Misleading "Add to favorites" menu item when station is already favorite will remove station

### ISSUE THREAD

**Issue by Vrihub** [segler-alex/RadioDroid#799]
How to reproduce:
- Tune into a station from your favorites
- Go into fullscreen mode
- The upper-right "three dots" menu contains an "Add to favorites" item
- If you click on it, the station will actually be _removed_  (with no possibility of undo)

Expected result:
- When a station is already favorite, the menu item should be called: "Remove from favorites"
- The user should be able to undo.

Version 0.83 on android 9.

**Comment by morckx** [comment]
> How to reproduce:
> 
> * Tune into a station from your favorites
> * Go into fullscreen mode
> * The upper-right "three dots" menu contains an "Add to favorites" item
> * If you click on it, the station will actually be _removed_  (with no possibility of undo)
> 
> Expected result:
> 
> * When a station is already favorite, the menu item should be called: "Remove from favorites"
> * The user should be able to undo.
> 
> Version 0.83 on android 9.

Thanks! The menu entry is obsolete here anyway having already the large star button at the bottom for (un-)bookmarking. A simple solution would  be to simply remove the entry here.
 
An entry that could make sense here, is one to create a shortcut on the home screen.
