### ISSUE TITLE
Add an option to start with the Favorites panel

### ISSUE THREAD

**Issue by Tratoschek** [segler-alex/RadioDroid#80]
At the moment the app always shows the "Radios" panel when starting. It would be nice, if you add an option to start with the "Favorites" or "History" panel.

**Comment by segler-alex** [comment]
This option is already there. you can start with favourites.

**Comment by Tratoschek** [comment]
Oops, fail, thank you. Could be, that I missed it, because it is not translated into German and I've though starred stations and favorites are different things (beside of this my display is not that big, so there only stands: "Starred stations at star...")

Maybe it could be translated as:
"Starred stations at startup" -> "Starte mit Favoriten"
""Show starred stations when starting RadioDroid" -> "Zeige Favoriten, wenn RadioDroid gestartet wird"
