### ISSUE TITLE
Build failed: Found item String/settings_record_name_formatting_default_display more than one time

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#810]
https://github.com/segler-alex/RadioDroid/commit/91cb71f62c162c6099e82a549adf6f53e76e802a is broken

**Comment by zo-shin** [comment]
See #806

**Comment by Wikinaut** [comment]
Please revert this commit a.s.a.p. - it breaks the code build.

**Comment by morckx** [comment]
> Please revert this commit a.s.a.p. - it breaks the code build.

I'd rather merge #806. It fixes the build and keeps the new translations.

**Comment by Wikinaut** [comment]
Thank you!
