### ISSUE TITLE
Stream plays on Firefox and Rhytmbox but not on Radiodroid

### ISSUE THREAD

**Issue by rdlmda** [segler-alex/RadioDroid#813]
I can open `https://s05.w3bserver.com:4212/live` (http://www.radio-browser.info/gui/#!/byname/internova) on Firefox and also on Rhytmbox, which correctly displays the radio name and song being played. But Radiodroid keeps showing "connecting" on the notification bar, be it on Wi-Fi or mobile data.

**Comment by morckx** [comment]
> I can open `https://s05.w3bserver.com:4212/live` (http://www.radio-browser.info/gui/#!/byname/internova) on Firefox and also on Rhytmbox, which correctly displays the radio name and song being played. But Radiodroid keeps showing "connecting" on the notification bar, be it on Wi-Fi or mobile data.

With the current master, I can play the stream without problems. Maybe the issue was fixed via #722 

Can you re-check it with the current master?

**Comment by rdlmda** [comment]
That's weird, I have v0.83 from F-Droid and when I opened this issue I tried to open the stream from different connections (mobile or wifi), with or without VPN, different DNS servers, and the stream wouldn't open. I haven't updated the app or made any changes to the OS or the network, and now it opens fine.

I'm closing the issue.
