### ISSUE TITLE
Suggestion: Transform 'History' into 'Recent' and use it as starting page?

### ISSUE THREAD

**Issue by feluxe** [segler-alex/RadioDroid#82]
I love the app! I use it every day.

One thing I would suggest is to use 'History' as the starting page for the app, because most of the time a user would go there to continue listening to one of the stations she used before. This seems to be the common behavior for most apps (Messengers, Phone calls, etc.) and it makes a lot of sense.

Another thing I would suggest is to remove duplicate entries from the 'History' page. It doesn't help you to find the same station multiple times. If that is done a more appropriate name for the 'History' page would be 'Recent'.

What do you think? :)

**Comment by Wikinaut** [comment]
The duplicate issue is solved now; In https://github.com/segler-alex/RadioDroid/commit/b72ec9472e5bb864f30b5aad8adcd0e339038201 I introduced a setting so that you can define one of three start views.

I think this solves your issues; if you think it does, you could consider to close the issue.

**Comment by feluxe** [comment]
Awesome! I already found it. Works great. Thanks! :)
