### ISSUE TITLE
Warning sound on network disconnect uses loudspeaker

### ISSUE THREAD

**Issue by iexos** [segler-alex/RadioDroid#820]
When the connection stops and "metered connection detected" appears, a warning sound is played both on bluetooth headphones and loudspeaker. This is irritating to other people around, it should only be played on the headphones which are playing the music.

Version: 0.83 (git 828b7e5) 2020-04-24 13:13:51 (F-Droid)
OS: current LineageOS 16.0
Device: OnePlus 5

**Comment by morckx** [comment]
Right, we should probably use `STREAM_MUSIC` here instead of `STREAM_ALARM`: https://github.com/segler-alex/RadioDroid/blob/f675bbfa0f8e08d3fcfe381526756a7c1c28359c/app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java#L1086

**Comment by werman** [comment]
> Right, we should probably use `STREAM_MUSIC` here instead of `STREAM_ALARM`:
> 
> https://github.com/segler-alex/RadioDroid/blob/f675bbfa0f8e08d3fcfe381526756a7c1c28359c/app/src/main/java/net/programmierecke/radiodroid2/service/PlayerService.java#L1086
> 
> EDIT:
> It would be played with media volume instead of alarm volume, but also that would be fine, I think. There is also a dialogue and playback pauses, anyway.
> 
> What do you think?
> 

I don't remember why is it `STREAM_ALARM`, `STREAM_MUSIC` should be fine.

> EDIT2: BTW: What do you think about using something like:
> 
> ```
> tts.speak("Wifi connection lost", TextToSpeech.QUEUE_FLUSH, null);
> ```
> 
> here. We could use this also for letting the user no when playback is resumed after connection is regained.

TTS is a good idea, I did want to add it (https://github.com/segler-alex/RadioDroid/issues/641#issuecomment-569449717) but didn't have time. We just need to check if we have localization for user's locale and whether TTS could play it.

**Comment by morckx** [comment]
> TTS is a good idea, I did want to add it ([#641 (comment)](https://github.com/segler-alex/RadioDroid/issues/641#issuecomment-569449717)) but didn't have time. We just need to check if we have localization for user's locale and whether TTS could play it.

OK, exactly what I thought and didn't have time for. Checking if a string is localized for the current locale seems at least possible. However, TTS might also need network :/

Anyway, I've tried already on my mobile without localization checking and was quite happy with my RadioDroid talking to me.

**Comment by iexos** [comment]
Thank you! :)
