### ISSUE TITLE
Stream works on Radio-Browser.info site / does not play in RadioDroid

### ISSUE THREAD

**Issue by kekukui** [segler-alex/RadioDroid#833]
**RadioDroid 0.83** (git 828b7e5)

https://www.radio-browser.info/gui/#!/byname/kfbx
https://www.radio-browser.info/gui/#!/byname/khvh

**Comment by morckx** [comment]
> **RadioDroid 0.83** (git [828b7e5](https://github.com/segler-alex/RadioDroid/commit/828b7e57898b2561f2bf91af5361160d850f9bcc))
> 
> https://www.radio-browser.info/gui/#!/byname/kfbx
> https://www.radio-browser.info/gui/#!/byname/khvh

Thanks for the report!
