### ISSUE TITLE
What is MPD in your source code ? and why you are using it ? & more

### ISSUE THREAD

**Issue by satyres** [segler-alex/RadioDroid#868]
Hi
First i want to thank you for this amazing job. i don't have any issue  but i'm trying to understand your code .
if you don't mind i have some question.
What is MPD ? i tried googling for it and i didn't understand it.
where is the Code for conneting to an Audio Chormecast ? not on TV just with speakers.
How did you enable your Android App to work with Ethernet not wifi ?
Where is the source code to enable the app to work with Android TV / DLNA ? 
I hope i don't bother you , just want to learn more from your code.
Thanks so much for taking time to read and respond to my questions ?

**Comment by werman** [comment]
MPD is a [Music Player Daemon](https://en.wikipedia.org/wiki/Music_Player_Daemon)

E.g. you launch it on PC and you would be able to play radio stations from RadioDroid on your PC.

Regarding Chromecast - see `CastHandler`

> How did you enable your Android App to work with Ethernet not wifi ?

I don't understand the question, we don't care much in what way Android connects to the internet.

> Where is the source code to enable the app to work with Android TV / DLNA ?

We don't have such.

**Comment by satyres** [comment]
Thank you so much for taking time to respond to my questions.
i'm so grateful
best regards

**Comment by werman** [comment]
RadioDroid doesn't work on PC. 

There is a Music Player Daemon installed on PC which can receive commands over the network, RadioDroid could connect to such server and command it to play radio station.

**Comment by satyres** [comment]
Thanks for your time
one last question please , is there any special code to let your app work with Android TV like [Zidoo Android TVBOX](https://www.zidoo.tv/)
Thanks so much and sorry for bothering you
Best regards

**Comment by werman** [comment]
No we don't support it.

**Comment by zo-shin** [comment]
I have been running the app on the Android set-top box for over a year and it has been working well. Since the app is not specially adapted for Android TV, a mouse is required to be able to click any place of the screen.

**Comment by satyres** [comment]
@werman @zo-shin 
Thanks you so much for your comment , really appreciate it.
Best regards

**Comment by zo-shin** [comment]
It doesn’t matter if the device is connected to the Wi-Fi or the cable.
