### ISSUE TITLE
Alsa device on mpd server not getting released after streaming from radiodroid.

### ISSUE THREAD

**Issue by djbarnat** [segler-alex/RadioDroid#870]
Hi would it be possible to add a stop button into the mpd functionality of radiodroid?. 

Currently when you stream to an mpd server, when pausing the mpd stream from the client the sound stops but the alsa device is not released on the mpd server. Mpd retains its "lock" on the pcm device even after exiting radiodroid. This means that any other process attempting to access that alsa device cannot.

For example my default alsa device is hw:2,0 and mpd is configured to output sound to this device. But i run other applications on my mpd server such as librespot to provide spotify connect that also need to access hw:2,0. If mpd is using the device then librespot cannot,  Normally MPD clients handle this by providing a "Stop" button which instructs the mpd server to release the alsa device which makes it available to other applications.

Currently after using radiodroid to play radio via mpd I have to go into another MPD client that has a stop button in order to release the alsa device.

Am I missing something in the client? Someway to instruct mpd to release the alsa device that I have not noticed?

I realize that this can be mitigated by using pulseaudio but there are other application I use that do not integrate with pulse and I think the client should really gracefully release the device after use.

Love this app btw 👍

**Comment by werman** [comment]
I don't think you are missing something, we never actually send the stop command, only pause. I don't think we thought about plain alsa.

It's easy to add a "Stop" button, the question is where... I'd welcome any suggestions.

Thank you for raising this issue.

**Comment by djbarnat** [comment]
I was thinking perhaps it could just go next to the pause button on the little square at the bottom 
![Screenshot_20200804-232340](https://user-images.githubusercontent.com/14138408/89351593-3dedcb00-d6aa-11ea-9d7a-ba60d4d282bf.png)

**Comment by djbarnat** [comment]
I guess the other option is make the the code behind pause button into a stop button as a the moment it doesnt actually "pause the" the stream (becasue its a radio station.)

**Comment by werman** [comment]
> I was thinking perhaps it could just go next to the pause button on the little square at the bottom

Looks like there is enough place here.

> I guess the other option is make the the code behind pause button into a stop button as a the moment it doesnt actually "pause the stream" (because its a radio station.)

Fair enough, I think my intent was to have an ability to resume the playback from another client, but I'm not sure how useful it is.

**Comment by djbarnat** [comment]
I see what you mean about resuming on another client i guess there would be a use case for that.

Either of the above would be gratefully received if they could be implemented. 

Thanks for your response on this, much appreciated.

**Comment by djbarnat** [comment]
Another thought I had is that the stop code could be put behind the "disable mpd" button. This would not require and interface change (interface change that may not be useful to everyone)  and would still serve the purpose.

**Comment by werman** [comment]
I think the least "magical" solution is to add a "Stop" button. All other variants are "magical", meaning they add some implied meaning for loosely related actions, without any way for user to infer this implied meaning.

Personally I try to reduce the amount of "magic" (unless it makes interaction much easier for user), it's hard to support it and if it doesn't match user's expectation - they just feel lost (and without telemetry it's hard for us to judge how user interact with our app). 

Our previous MPD implementation had a fair amount of "magic" and I found it's easier to just rewrite it than handle all use cases I wanted to have.

**Comment by djbarnat** [comment]
Good point, i suppose too much magic can be difficult to maintain also, the source magic could get lost :)
