### ISSUE TITLE
Languages already translated? 

### ISSUE THREAD

**Issue by aevw** [segler-alex/RadioDroid#875]
How can I find out which languages were already translated?

This is the latest [language string](https://raw.githubusercontent.com/segler-alex/RadioDroid/master/app/src/main/res/values/strings.xml)?

Thanks

**Comment by aevw** [comment]
So I looked around and only found these languages translated:

Indonesian, Danish, Spanish, German, Catalan, Polish, French, Turkish, Norwegian, Slovak, Greek,  Russian, Finnish, Czech

I did not find translation for pt_BR, 

so here it is:

[pt_BR](https://github.com/aevw/aevw/blob/master/radiodroid_pt_BR.txt)


Btw great app.

**Comment by werman** [comment]
Hi, not all of the languages are fully translated.

Your link isn't working.

Thanks.

**Comment by aevw** [comment]
It was set private, it's available now 
thanks

**Comment by werman** [comment]
Thanks a lot!
