### ISSUE TITLE
Crashes when playing

### ISSUE THREAD

**Issue by FrankEular** [segler-alex/RadioDroid#88]
Here's the logcat:
[radio1.txt](https://github.com/segler-alex/RadioDroid/files/560138/radio1.txt)

It crashes while playing RFI Monde.
Build: 0.24 (installed from F-Droid)
OS: cm13.0

**Comment by segler-alex** [comment]
this is also because you have not enough ram, is this related to your other bug maybe?
which mobile phone do you have?

**Comment by FrankEular** [comment]
kltechnduo, with 1.8 GB RAM. Whether it's related, I cannot tell, but this issue is very occasional. Maybe we can close this issue for the moment.
