### ISSUE TITLE
Auto stop/play a stream that was interrupted

### ISSUE THREAD

**Issue by ZeZiNhOo** [segler-alex/RadioDroid#9]
Thank you for your work, I am using this app for a few days. It does not restart playing automaticaly if the stream is interrupted. This is very annoying as a simple stop/play fix it. It should be done automaticaly!

**Comment by segler-alex** [comment]
Hi, thank you! I am happy that people are using my webservice.
Is there a radio station that gets interupted very often? it would be good to know when i try to find a fix for this behaviour.
greetings from vienna

**Comment by ZeZiNhOo** [comment]
Le 05/04/2016 23:16, segler-alex a écrit :
>
> Hi, thank you! I am happy that people are using my webservice.
> Is there a radio station that gets interupted very often? it would be 
> good to know when i try to find a fix for this behaviour.
> greetings from vienna
>
>
Well, less than the station that gets interrupted, it is my Wifi 
connection that is interrupted when I walk around the phone, which is 
already slightly far from the AP.
So the best option is probably to stop/start WiFi, then player should 
restart the stream automatically. As it may be annoying that stream 
restarts one hour later because I arrived somewhere where this is Wifi 
again, a timer should stop reconnections after something like 3 minutes.

This may be a configurable option : restart interrupted streams, with 
the timer minutes.



*****************************************************
"Le contenu de ce courriel et ses eventuelles pièces jointes sont confidentiels. Ils s'adressent exclusivement à la personne destinataire. Si cet envoi ne vous est pas destiné, ou si vous l'avez reçu par erreur, et afin de ne pas violer le secret des correspondances, vous ne devez pas le transmettre à d'autres personnes ni le reproduire. Merci de le renvoyer à l'émetteur et de le détruire.

Attention : L'Organisme de l'émetteur du message ne pourra être tenu responsable de l'altération du présent courriel. Il appartient au destinataire de vérifier que les messages et pièces jointes reçus ne contiennent pas de virus. Les opinions contenues dans ce courriel et ses éventuelles pièces jointes sont celles de l'émetteur. Elles ne reflètent pas la position de l'Organisme sauf s'il en est disposé autrement dans le présent courriel."
******************************************************

**Comment by ZeZiNhOo** [comment]
I updated to version 0.9 and could listen for more than one hour without hitting again the play button.
Sound has paused 3/4 times for 1 or 2 seconds, so I don't know if you worked on this, but it seems fixed?

**Comment by Zecas** [comment]
It is not fixed in fact, with version 0.14. I will update to 0.14.2 when it hits f-droid as I have seen some related commits ;-)

**Comment by segler-alex** [comment]
i think this should be fixed, i try reconnecting for 30 seconds now.
