### ISSUE TITLE
Please consider adding itch.fm to the channel list

### ISSUE THREAD

**Issue by heydojo** [segler-alex/RadioDroid#925]
Hi there!
Great app. https://www.itch.fm/ have a radio stream which I think might be nice to add to the channel list. It's a UK Hip Hop station. Please see the site for more information. They've been around for sometime now, if a little under the radar.

I tried searching in the app for "itch.fm" and nothing appeared in the results. 👍

**Comment by werman** [comment]
Hi, RadioDroid source the stations from public database https://www.radio-browser.info - you could add a station via https://www.radio-browser.info/#!/add

**Comment by MarshmelloSUCKS** [comment]
I went ahead and added them, you should be able to tune in 10 minutes after this comment
