### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#95]
Typos: Spelling error
../../src/main/res/values/strings.xml:81: "Transfered" is a common misspelling; did you mean "Transferred" ?

  78     <string name="player_info_status">STATUS:</string>
  79     <string name="player_info_status_stopped">Stopped</string>
  80     <string name="player_info_status_playing">Playing</string>
  81     <string name="player_info_transfered">Transfered data: %1$s</string>
  82     <string name="player_info_record_to">Recording to: %1$s</string>
  83

**Comment by segler-alex** [comment]
thank you, i corrected it
