### ISSUE TITLE
Radio-Browser-Info api soon unsupported, use new API

### ISSUE THREAD

**Issue by aha999** [segler-alex/RadioDroid#957]
from a radio-browser-info website:
 

> Alert!
>  If you still use the api at www.radio-browser.info/webservice you should switch as soon as possible to the new one at [api.radio-browser.info](https://api.radio-browser.info/). The old one is not supported anymore and will not receive any more updates on the software side. The new one is in place and stronger than ever (multiple servers). The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020. 

![slika](https://user-images.githubusercontent.com/50620416/103479387-a3ff8b00-4dcd-11eb-95a3-aed705708e02.png)

**Comment by segler-alex** [comment]
this already happened
