### ISSUE TITLE
External Player Not Work

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#959]
In v0.84, **play in external player** doesn’t work. The browser is activated instead of the player.

**Comment by werman** [comment]
@morckx https://github.com/segler-alex/RadioDroid/pull/827 broke it... Upon a more careful look - a lot of streams don't have an extension so Android doesn't have a way to infer the mime type. With the commit reverted I see VLC and other player being offered.

> [...] Without apparently only apps that handle urls in general.

For me it is the other way around.
