### ISSUE TITLE
Playback stops on screen orientation change when app has focus.

### ISSUE THREAD

**Issue by ricardomvdcosta** [segler-alex/RadioDroid#972]
v 0.84
When the app is opened in frontground, rotating the phone, thus making screen rotate, will cause play to stop. Rotating it back makes it reconnect (notification on top) and play back again. This happens in both modes, if you start it horizontally or vertically screen orientated.

Does not happen when: app is in the background and screen is active; neither when screen is off (changing mobile orientation). As far as I noticed it didn't happen on previous versions and I'm not aware of any options settings related to this.

**Comment by Baryczka** [comment]
Is that latest fix for this issue is released yet? According to the dates not yet right? When we can expect new release?
