### ISSUE TITLE
Add Chromecast support

### ISSUE THREAD

**Issue by bobo71dream** [segler-alex/RadioDroid#98]
Hello alex.

Can you add please support for Chromecast streaming in your app? It will be very nice.

Regards.

**Comment by segler-alex** [comment]
i have to buy a chromecast for that. what do you know about it? do i have to program a special app for the chromecast ?

**Comment by bobo71dream** [comment]
Hmm, also. Ich würde Dir ggf. einen von meinem Chromecasts borgen. https://developers.google.com/cast/ steht einiges dazu. Ich habe es in Python implementiert. Du musst in deiner APP den Chromecast einbauen. Dann ubergibst Du die URL an den Chromecast. Ich hoffe das die cast API da eingebaute Funktionen zur Verfügung stellt. Wenn das dann läuft, ist das eine tolle Sache...
Gruß.

**Comment by segler-alex** [comment]
i added some basic chrome cast support in beta channel.
Please feel free to test :)

**Comment by Cormak** [comment]
@segler-alex isn't this issue resolved with https://github.com/segler-alex/RadioDroid/releases/tag/0.36

**Comment by bobo71dream** [comment]
Hi Alex, Support Forum Chromecast basicly work. Bitte if i tune an another Station Chromecast Stream not playing new Stream. I have time Close Cast anderen reopen it. Regrads.

**Comment by segler-alex** [comment]
ich bin nicht sicher ob ich verstehe was du meinst.

**Comment by bobo71dream** [comment]
also,

wenn ich eine Station höre und dann auf casten gehe, dann läuft der Sound auf dem Handy weiter und auf dem Chromecast sieht man den Radiobrowser Skin. Wenn ich dann einen neuen Sender tune, dann spielt der Chromecast den neuen Sender und mein Handy weiter den ersten Stream. Wenn ich aber vor dem ersten abspielen auf Cast gehe dann funktioniert es top. Danke nochmals für dein Plugin. Ich denke du musst zum Start des castens den Stream auf dem Hand killen und ein reconnect anschupsen...

MfG.

**Comment by segler-alex** [comment]
das sollte auf der version im beta channel schon funktionieren

**Comment by Wikinaut** [comment]
@segler-alex Wann updatest Du die "Non-Beta"-Version im Playstore?

**Comment by segler-alex** [comment]
stream aufnahme produziert im beta kaputte dateien. das muss vorher noch repariert werden

**Comment by Wikinaut** [comment]
@segler-alex Gibt's dazu ein Ticket? (Gerne würde ich auch - unrelated - https://github.com/segler-alex/RadioDroid/issues/231 haben wollen.)
