### ISSUE TITLE
[Question] How do we detect local stations

### ISSUE THREAD

**Issue by q3e** [segler-alex/RadioDroid#988]
First time user and I am curious how RadioDroid detects local stations displayed in the Local Tab. Does it detect country IP and use that to query www.radio-browser.info? or does it actually analyze local radio broadcasts metadata? I'd appreciate if you point me in the file that handles this logic.

**Comment by werman** [comment]
We use `TelephonyManager` to get the country code from network or sim.

https://github.com/segler-alex/RadioDroid/blob/f9edae5cb6d39048c9f7c71b3757240a3e6f8a8e/app/src/main/java/net/programmierecke/radiodroid2/FragmentTabs.java#L121-L125

And the stations in the database have their country specified.

**Comment by q3e** [comment]
Thanks @werman this is very good
