### ISSUE TITLE
Silent through app but playing on http://www.radio-browser.info

### ISSUE THREAD

**Issue by 2SI3NX** [segler-alex/RadioDroid#99]
Hi
These two stations were added recently: DI Tech House and DI House.
They play perfectly through the browser but when i go to the app, it says preparing stream and in the player info i can see that the Transfered Data is moving but there is no sound.
Please help ? is this a bug on this **type** of stream?

**Comment by segler-alex** [comment]
the streams are not existing anymore. maybe send me the stream urls?

**Comment by segler-alex** [comment]
i am closing, because of no response

**Comment by 2SI3NX** [comment]
i think they or someone deleted them after i posted.
